import type { BlogPost } from "./blog-types";

export const BLOG_REVIEWS_EXTRA: BlogPost[] = [
  {
    slug: "featurebase-alternatives",
    title: "The best Featurebase alternatives in 2026",
    description:
      "Featurebase bundles feedback, roadmap and a help centre, but AI is metered and seats climb fast. Compare five alternatives, pricing and what each trades off.",
    date: "2026-08-17",
    keyword: "featurebase alternative",
    category: "Reviews",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and spends a surprising amount of her week reading other companies' pricing pages.",
    image: "https://images.unsplash.com/photo-1516910817563-4df1c1b69058?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Support agent working at a desk with a laptop, representing a combined feedback and help desk tool",
    readMins: 6,
    blocks: [
      { p: "Featurebase earned its popularity honestly: a feedback board, public roadmap, changelog and a help centre module in one product, with a free plan that does not cap end-users. The catch shows up once you actually turn features on. AI is metered as a paid add-on rather than included, and seats scale from $29 to $99 a month as you add languages and automation. This guide compares five alternatives, what each costs once the free plan runs out, and where Featurebase still wins for teams that specifically want a combined support and feedback hub." },
      { h2: "Why teams look for a Featurebase alternative", ul: [
        "AI features, including auto-tagging and suggested replies, sit behind a metered add-on rather than a flat seat price",
        "Seat pricing climbs from $29 to $99 a month across tiers, which adds up fast for a growing support team",
        "The broader support-suite scope means more menus and settings than teams that only want a feedback board actually need",
        "Some teams only ever use the board, roadmap and changelog, and end up paying for a help centre module they never touch",
        "Onboarding takes longer than a single-purpose feedback tool because there is simply more to configure",
      ] },
      { h2: "Feedlark", p: "Feedlark is the closest swap for teams that use Featurebase for its feedback board, roadmap and changelog but not its help centre. The free plan covers all three with no cap on end-users, and the Pro plan is [$19 per admin seat](/pricing), ten dollars cheaper than Featurebase's entry tier, with no metered AI add-on to budget around separately. Ship an item and the changelog entry publishes itself, with every voter notified automatically, so the 'you asked, we shipped' loop closes without a support agent doing it by hand. Setup takes under ten minutes, and teams can [try it free](/signup) before adding paid seats." },
      { h2: "Canny", p: "Canny is the more established name in this space, with wider integrations and a longer track record. It bills per tracked user rather than per seat, though, and our [breakdown of Canny's 2026 pricing](/blog/canny-pricing-explained) shows how that adds up once a board gets real traffic. The free plan caps at 25 tracked users, which a single popular post can exceed on its own. Worth comparing if deep integrations matter more to you than predictable billing." },
      { h2: "Productboard", p: "Productboard sits a level up in scope: discovery, prioritisation frameworks and strategy tooling built for larger product organisations, not just a feedback board with a help desk attached. Our [Productboard alternatives guide](/blog/productboard-alternatives) covers this in more depth, but the short version is that it solves a different problem than Featurebase does, and it costs more to solve it. Consider it only if your team genuinely runs a formal discovery process today." },
      { h2: "Nolt", p: "Nolt trades Featurebase's breadth for simplicity: a clean feedback board with flat per-board pricing around $29 a month, no per-seat scaling and no metered add-ons. Our [look at Nolt alternatives](/blog/nolt-alternatives) has the full picture, but Nolt has no AI deduplication and no help centre module at all, so it suits a very early product more than a team already using Featurebase's fuller feature set." },
      { h2: "Frill", p: "Frill covers the same core ground as Feedlark, ideas, roadmap and changelog, with pricing starting around $25 a month and scaling to tiers with white-labelling. It does not include a help centre module, so teams switching from Featurebase specifically for that reason should look elsewhere. For teams that only ever used Featurebase's board and roadmap, Frill is a reasonable, similarly priced option." },
      { h2: "What Featurebase's metered AI actually costs", p: "The part of Featurebase's pricing that catches teams out is not the seat fee, it is the AI usage sitting on top of it. Auto-tagging, suggested replies and summarisation are billed per resolution once you go past the included allowance, so a support-heavy month can add a meaningful, unpredictable line to the bill on top of the base seat price. That variability is the opposite of what most small teams want from a tool bill. A flat per-seat price, even a slightly higher one, is easier to plan around than a metered add-on that scales with how much your customers actually use the product, which is exactly when you can least afford a surprise invoice." },
      { h2: "Questions worth asking before you switch", ul: [
        "Do you actually use the help centre module, or has it sat untouched since setup?",
        "How much of your Featurebase bill is the base seat price versus metered AI usage?",
        "Does the alternative you are considering notify existing voters automatically, or does that need doing by hand?",
        "Can you export your board, votes and roadmap items in a format the new tool actually accepts?",
        "Will your embedded widget need replacing across your site, or can it be swapped in place?",
      ] },
      { h2: "How to choose", p: "If the help centre module is genuinely part of your daily workflow, Featurebase remains the most complete option and switching away means losing real functionality. If you have only ever used the feedback board, roadmap and changelog, Feedlark or Frill deliver the same day-to-day workflow for less, without a metered AI bill to watch. Canny is worth a look if wide integrations matter more than predictable per-seat pricing. Closing the loop with customers matters more than any single feature list: [Zendesk's 2026 CX Trends report](https://cxtrends.zendesk.com/) found 63% of people say demand for transparency from companies has risen, and a public roadmap with a connected changelog is one of the more direct ways to answer that. That kind of visible follow-through compounds over time: Bain's oft-cited analysis found that [lifting customer retention by five points can raise profits by 25 to 95%](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers), and a tool that automatically tells voters what shipped is a small, low-effort lever toward that." },
      { h2: "What migration actually looks like", p: "Moving off Featurebase is a lighter job than it looks. Export existing posts, votes and roadmap items, most alternatives accept a CSV import or a quick manual copy for a small board, and rebuild your status categories and board structure in the new tool. The larger task is communication: point existing voters and any embedded widget to the new location, and keep a note on the old board for a few weeks so returning visitors do not land on a dead page. Most teams complete the switch inside a few days, since the tool setup itself is quick and the rest of the time goes into making sure nothing important gets lost." },
      { h2: "A realistic timeline for switching", p: "Day one is usually spent exporting existing data and recreating board categories and statuses in the new tool, which rarely takes more than an afternoon even for a busy board. The next couple of days go into a soft launch: pointing a small group of existing voters to the new location and confirming nothing important was lost in the move, particularly older posts with long comment threads. By the end of the week, the old board can carry a short note directing everyone to the new one, and normal posting resumes on the replacement without much disruption to people who were already using it." },
      { quote: { text: "Teams rarely regret leaving a metered AI bill behind. They regret not checking, before they switched, whether the replacement still notifies every voter automatically when something ships.", cite: "Priya Shah, Head of Product at Feedlark" } },
      { table: {
        caption: "Featurebase alternatives at a glance",
        head: ["Tool", "Entry paid price", "Free tier", "AI features", "Best for"],
        rows: [
          ["Feedlark", "$19/seat", "Unlimited end-users, roadmap and changelog", "Included, not metered", "Teams that skip the help centre and want lower cost"],
          ["Canny", "From $79/mo", "25 tracked users", "Included on paid plans", "Established teams needing wide integrations"],
          ["Productboard", "~$19/maker", "Limited / trial", "Credit-based", "Larger teams running a formal discovery process"],
          ["Nolt", "~$29/mo per board", "Trial only", "None", "Very small teams wanting one simple board"],
          ["Frill", "From $25/mo", "Trial only", "None", "Teams replacing only the board, roadmap and changelog"],
          ["Featurebase", "From $29/seat", "Unlimited end-users (AI excluded)", "Metered add-on", "Teams that actively use the help centre module"],
        ],
      } },
    ],
    takeaways: [
      "Featurebase's free plan excludes AI, and paid seats scale from $29 to $99 a month with AI metered separately.",
      "Feedlark and Frill cover the same board, roadmap and changelog workflow for less, without a metered AI add-on.",
      "Canny and Productboard solve different problems: wider integrations, or full product discovery and strategy.",
      "Keep Featurebase if the help centre module is part of your daily workflow; switch if you only ever use the board.",
    ],
    faqs: [
      { q: "Is there a free Featurebase alternative?", a: "Yes. Feedlark's free plan covers a feedback board, public roadmap and changelog with no cap on end-users, similar to Featurebase's free tier, but without AI features gated behind a metered add-on." },
      { q: "Why does Featurebase get expensive as teams grow?", a: "Seats scale from $29 to $99 a month across tiers, and AI features such as auto-tagging and suggested replies are billed separately as a metered add-on rather than included in the seat price." },
      { q: "Do I need the help centre module Featurebase includes?", a: "Only if you use it. Teams that solely collect feedback, publish a roadmap and post a changelog typically never touch the help centre, and a focused tool like Feedlark covers that core workflow for less." },
      { q: "How long does it take to switch away from Featurebase?", a: "Exporting posts, votes and roadmap items typically takes an afternoon for a small board. Most teams complete the full switch, including pointing existing voters to the new location, within a few days." },
    ],
  },
  {
    slug: "online-roadmap-tools-compared",
    title: "6 online roadmap tools compared for 2026",
    description:
      "A side-by-side comparison of six online roadmap tools for 2026, covering pricing, free tiers, public roadmap support and how each handles user votes.",
    date: "2026-07-18",
    keyword: "online roadmap tool",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Laptop displaying an online roadmap tool dashboard with charts and status columns",
    readMins: 8,
    blocks: [
      { p: "An online roadmap tool needs to do more than draw a timeline. For most SaaS teams, it needs to connect to where feature ideas actually come from, show status publicly if you want customer trust, and stay affordable as your user base grows rather than penalising you for success. Here is how six commonly considered tools compare on exactly those points." },
      { h2: "Feedlark", p: "Feedlark combines a feedback board, public roadmap and auto-generated changelog in one connected system. Unlimited end-users are free forever, with paid seats [from $19 a month](/pricing) for teams that want custom branding or private boards. Moving a roadmap item to Shipped automatically notifies every voter and drafts a changelog entry, closing the loop without manual follow-up. Setup typically takes under ten minutes." },
      { h2: "Productboard", p: "Productboard is a full enterprise product management platform with deep discovery, insight tagging and prioritisation scoring built in. It is genuinely powerful for large product organisations juggling many stakeholders, but it is priced per 'maker' seat and carries a steeper learning curve than most small teams need for a straightforward public roadmap." },
      { h2: "Aha!", p: "Aha! offers one of the deepest strategic planning feature sets in the category, including scorecards, goals and initiative tracking layered above the roadmap itself. It suits larger product organisations that want a formal strategic planning process, though the depth of configuration options can feel like overhead for a team that mainly wants a simple public-facing view." },
      { h2: "Roadmunk", p: "Roadmunk focuses specifically on visual roadmap presentation, with strong timeline and swimlane views aimed at stakeholder communication. It is a solid choice if presentation quality to leadership is the primary need, though it leans lighter on the collection and voting side that feeds prioritisation in the first place." },
      { h2: "ProductPlan", p: "ProductPlan is another presentation-focused tool, well suited to teams that need to communicate a roadmap clearly across departments via polished, exportable views. Like Roadmunk, it is less oriented toward direct user feedback collection, so many teams pair it with a separate feedback tool rather than relying on it alone." },
      { h2: "Fider", p: "Fider is open source and free if you are willing to self-host it. It covers voting, statuses and a public roadmap view, and gives full control of your own data, at the cost of taking on server setup and ongoing maintenance yourself rather than paying a vendor to handle it." },
      { table: { caption: "Online roadmap tools compared", head: ["Tool", "Starting price", "Free tier", "Best for"], rows: [
        ["Feedlark", "$19/seat", "Unlimited end-users", "Connected feedback, roadmap and changelog"],
        ["Productboard", "Per maker seat", "None", "Large product orgs with deep discovery needs"],
        ["Aha!", "Per user, tiered", "Trial only", "Formal strategic planning and goals tracking"],
        ["Roadmunk", "Per editor", "Trial only", "Polished stakeholder presentation views"],
        ["ProductPlan", "Per editor", "Trial only", "Cross-department roadmap communication"],
        ["Fider", "Free (self-hosted)", "Unlimited", "Full data control for technical teams"],
      ] } },
      { h2: "How to choose between them", p: "If your priority is a single connected system, feedback in, votes counted, roadmap updated, users notified when it ships, look at Feedlark first. If your team already runs a heavier strategic planning process with goals and scorecards, Aha! or Productboard fit that need more directly. If presentation to leadership matters more than direct user collection, Roadmunk or ProductPlan are built for that specifically. And if data ownership matters more than convenience, Fider is worth the self-hosting effort." },
      { h2: "Pricing structure matters as much as the sticker price", p: "Several tools in this category price primarily by editor or maker seat, which keeps costs predictable for the internal team regardless of how many customers engage with the public roadmap. Others, more common among dedicated feedback tools than pure roadmap tools, bill by tracked end-user, which can climb quickly once a board takes off. When comparing an online roadmap tool, check specifically what triggers a price increase, not just the advertised starting number." },
      { h2: "What a short trial should test", ul: [
        "Can a non-technical stakeholder read the public roadmap view without a walkthrough?",
        "Does moving an item to Shipped do anything automatically, or does someone have to remember a manual step?",
        "How many clicks does it take to go from a new idea to a scheduled roadmap item?",
        "Is the free tier, where one exists, genuinely usable or a crippled trial in disguise?",
      ] },
      { quote: { text: "Most teams compare roadmap tools on how the timeline looks. The tools that hold up over a year are the ones where updating status is genuinely no more effort than the update itself.", cite: "Feedlark Team" } },
      { h2: "The bottom line", p: "There is no single best online roadmap tool for every team. A small SaaS product wanting a connected, affordable, customer-facing system fits Feedlark's model closely. A large enterprise product organisation with a formal planning cadence has different needs entirely, and tools like Aha! or Productboard are built with that scale in mind. Match the tool to your actual team size and process, not to whichever one has the most features listed on its homepage." },
      { h2: "Migration effort between these tools", p: "Most online roadmap tools let you export existing items in a CSV or similar format, and importing into a new tool typically takes an afternoon for a small to mid-sized roadmap. The larger task is usually redirecting a public-facing link and letting existing subscribers or voters know where things moved, ideally with a short overlap period where both old and new pages stay live so nobody's bookmark leads to a dead page during the switch." },
      { h2: "A note on mobile-friendliness", p: "A meaningful share of users check a public roadmap from a phone, often after clicking a link in an email or changelog notification. Before committing to any of these six tools, check the public roadmap view specifically on a mobile browser, not just the admin dashboard. Some tools that look polished on desktop render awkwardly on a small screen, which quietly undermines the transparency a public roadmap is meant to provide." },
    ],
    takeaways: [
      "Six tools compared here range from lightweight connected systems to deep enterprise planning platforms.",
      "Pricing structure, per seat versus per tracked user, matters more long term than the advertised starting price.",
      "Feedlark and Fider offer genuinely usable free tiers; the others are trial-only before a paid commitment.",
      "Match the tool to your team's actual planning process rather than choosing on feature count alone.",
    ],
    faqs: [
      { q: "What is the cheapest online roadmap tool with a real free tier?", a: "Feedlark offers unlimited end-users for free, charging only for admin seats. Fider is also free if you are willing to self-host it, which trades licensing cost for server and maintenance responsibility." },
      { q: "Which online roadmap tool is best for a large enterprise team?", a: "Productboard and Aha! both offer deeper strategic planning features suited to larger product organisations juggling multiple stakeholders and a formal goals process." },
      { q: "Do online roadmap tools need to be public-facing?", a: "Not necessarily, but a public view tends to build more customer trust than an entirely internal roadmap, particularly for SaaS products where transparency is a competitive factor." },
      { q: "How important is a changelog when choosing a roadmap tool?", a: "Very, if closing the loop with users matters to you. A roadmap tool without a connected changelog and notification system leaves the most valuable step, telling people their request shipped, as a manual afterthought." },
    ],
  },
  {
    slug: "customer-feedback-analysis-tools",
    title: "7 customer feedback analysis tools worth a look",
    description:
      "A practical comparison of seven customer feedback analysis tools for 2026, covering what each one measures well, pricing, and where each genuinely fits.",
    date: "2026-07-18",
    keyword: "customer feedback analysis tools",
    category: "Reviews",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and spends a surprising amount of her week reading other companies' pricing pages.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Laptop on a glass table displaying statistics, representing customer feedback analysis",
    readMins: 8,
    blocks: [
      { p: "Customer feedback analysis tools range from simple vote-and-tag boards to heavyweight sentiment platforms that mine calls, tickets and reviews automatically. Picking the right one depends less on features and more on where your feedback actually lives today, and what shape of pattern you most need to see. Here are seven worth considering, and where each genuinely fits." },
      { h2: "Feedlark", p: "Feedlark's analysis strength comes from structure rather than heavy natural language processing: votes, categories and status give a clean, always-current view of what customers want most, directly tied to a roadmap and changelog. It suits teams that want prioritisation clarity more than deep sentiment mining, and unlimited end-users are free with paid seats [from $19 a month](/pricing)." },
      { h2: "Zendesk QA / Explore", p: "For teams already running Zendesk for support, its analytics layer can mine ticket data for recurring themes without needing a separate tool. It is a strong option if most of your feedback signal already flows through support tickets rather than a dedicated feedback channel, though it is less suited to collecting structured, votable feature requests directly." },
      { h2: "Delighted", p: "Delighted focuses specifically on NPS and CSAT survey analysis, with clean trend dashboards over time. It is a good complement to a feedback board rather than a replacement, since it measures sentiment well but does not structure specific, buildable feature requests the way a voting board does." },
      { h2: "MonkeyLearn (Medallia)", p: "Now part of Medallia, this tool offers genuine text-mining capability for unstructured feedback, useful for larger organisations processing high volumes of open-text survey responses or reviews. The depth comes with enterprise-scale pricing and setup complexity that is often more than a small SaaS team needs." },
      { h2: "Canny", p: "Canny's board and basic analytics cover collection and voting well, similar in spirit to Feedlark, though its pricing is based on tracked users rather than admin seats, which our [detailed pricing breakdown](/blog/canny-io-pricing-breakdown-2026) covers in full. Worth a look if you are already comparing feedback boards specifically." },
      { h2: "Qualtrics", p: "Qualtrics is a heavyweight enterprise experience management platform covering surveys, analytics and predictive modelling. It is genuinely powerful, but its scale and pricing are built for large enterprises with dedicated CX teams rather than a mid-sized SaaS product looking for a straightforward feedback analysis tool." },
      { h2: "Google Sheets plus manual tagging", p: "Worth naming honestly: for very early-stage teams with low feedback volume, a well-organised spreadsheet with manual tagging is a legitimate starting point. It has obvious limits once volume grows past what a human can tag consistently, but it costs nothing and avoids over-investing in tooling before the pattern of need is clear." },
      { table: { caption: "Customer feedback analysis tools by primary strength", head: ["Tool", "Primary strength", "Best fit"], rows: [
        ["Feedlark", "Structured votes tied to roadmap", "SaaS teams wanting prioritisation clarity"],
        ["Zendesk Explore", "Mining existing support tickets", "Support-heavy teams with high ticket volume"],
        ["Delighted", "NPS/CSAT trend tracking", "Sentiment tracking alongside a feedback board"],
        ["MonkeyLearn (Medallia)", "Deep text mining at scale", "Large orgs with high open-text survey volume"],
        ["Canny", "Voting board with tracked-user pricing", "Teams comparing feedback boards directly"],
        ["Qualtrics", "Enterprise-wide experience management", "Large enterprises with dedicated CX teams"],
        ["Spreadsheet + manual tagging", "Zero cost, full control", "Very early-stage teams with low volume"],
      ] } },
      { h2: "Structured versus unstructured analysis", p: "There is a meaningful split in this category between tools that analyse structured data, votes, categories, statuses, and tools that mine unstructured text, open survey responses, call transcripts, reviews. Structured tools tend to give clearer, more immediately actionable output; unstructured tools surface patterns you would not have thought to ask about directly, at the cost of more setup and interpretation effort." },
      { h2: "How to pick based on where your feedback already lives", p: "If most of your feedback already arrives through a public board or widget, a structured tool built around votes and categories, like Feedlark, gets you useful analysis with almost no extra setup. If most feedback is buried in support tickets or open-text survey responses, a mining tool like Zendesk Explore or MonkeyLearn earns its cost by surfacing patterns you would otherwise need to read manually." },
      { quote: { text: "The best feedback analysis tool is the one that matches how your feedback already arrives, not the one with the most impressive dashboard in a demo.", cite: "Priya Shah, Head of Product at Feedlark" } },
      { h2: "A note on cost versus team size", p: "Enterprise-grade tools like Qualtrics and Medallia carry pricing and implementation timelines built for large organisations with dedicated analytics staff. For most SaaS teams under fifty people, a lighter, structured tool tied directly to a roadmap tends to deliver more practical value per pound spent than a heavyweight platform whose deeper capabilities go largely unused." },
      { h2: "Trial questions worth asking regardless of which tool you pick", ul: [
        "Can a non-technical stakeholder read the output and understand the top three themes without a walkthrough?",
        "Does the tool distinguish a genuine pattern from a handful of loud but unrepresentative comments?",
        "How much manual tagging or setup is required before the tool produces useful output?",
        "Does the analysis connect back to a specific, actionable next step, or does it stop at an interesting chart?",
      ] },
      { h2: "Why analysis quality depends on collection quality", p: "No feedback analysis tool, however capable, can produce a clear signal from messy or duplicated raw data. Before investing heavily in analysis tooling, it is worth checking whether your underlying collection process, however feedback actually arrives, has basic hygiene in place: consistent categorisation, deduplication of near-identical requests, and a single canonical destination rather than five scattered channels. Analysis layered on top of a clean, structured feedback board tends to outperform a more sophisticated tool layered on top of a messy one." },
      { h2: "A note on team size and tool depth", p: "It is tempting to reach for the most feature-rich tool on a shortlist, but depth only pays off if someone on the team has the time to actually use it. A solo founder or a two-person product team is usually better served by a structured, low-maintenance tool like Feedlark than by a heavyweight analysis platform whose dashboards go unopened after the first month. Match the tool's depth to the time your team genuinely has available to review it, not to the size of the problem you would ideally like to solve." },
    ],
    takeaways: [
      "Seven tools compared here split roughly between structured, vote-based analysis and unstructured text mining.",
      "Match the tool to where feedback already arrives: a board favours structured tools, ticket-heavy teams favour mining tools.",
      "Enterprise platforms like Qualtrics and Medallia carry depth and cost most mid-sized SaaS teams do not need.",
      "A simple spreadsheet is a legitimate starting point for very early-stage teams before investing in dedicated tooling.",
    ],
    faqs: [
      { q: "What is the difference between structured and unstructured feedback analysis?", a: "Structured analysis works on organised data like votes and categories, giving clear, immediately actionable output. Unstructured analysis mines free text like survey comments or call transcripts, surfacing patterns you might not have thought to ask about, at greater setup cost." },
      { q: "Do I need a dedicated feedback analysis tool if I already use a feedback board?", a: "Often not separately. A well-structured board with votes and categories already provides a clear, useful form of analysis without needing an additional dedicated tool layered on top." },
      { q: "Which customer feedback analysis tool is cheapest to start with?", a: "Feedlark is free for unlimited end-users, and a manually tagged spreadsheet costs nothing at all, though it does not scale well past a modest volume of feedback." },
      { q: "Is enterprise feedback analysis software worth it for a small team?", a: "Rarely. Tools like Qualtrics and Medallia are built for large organisations with dedicated CX staff, and their cost and complexity usually outweigh the benefit for a smaller SaaS team." },
    ],
  },
  {
    slug: "canny-io-pricing-breakdown-2026",
    title: "Canny.io pricing in 2026: every tier explained",
    description:
      "A full breakdown of Canny.io's 2026 pricing tiers, Core vs Pro, tracked-user costs at each level, and how the bill compares to a per-seat alternative.",
    date: "2026-07-18",
    keyword: "canny io pricing",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1604594849809-dfedbc827105?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Miniature figure sitting on a stack of coins, representing tiered software pricing",
    readMins: 8,
    schemaType: "Review",
    blocks: [
      { p: "Canny.io runs two paid tiers, Core and Pro, each priced on a sliding scale by tracked users, alongside a capped free plan. This is a full tier-by-tier breakdown of what each level actually costs in 2026 and where the jump between them happens, complementing our broader [Canny pricing overview](/blog/canny-pricing-explained) with the specific numbers at each tracked-user threshold." },
      { h2: "The free plan", p: "Canny's free plan caps accounts at 25 tracked users, anyone who posts, votes or comments on a board. That ceiling is easy to cross with even modest engagement: a single feature mentioned in a newsletter or a popular request thread can push a new account past 25 within days, at which point an upgrade becomes necessary to keep the board functioning." },
      { h2: "Core tier: entry-level paid pricing", p: "Canny's Core plan starts at $19 a month when billed annually, covering up to 100 tracked users. From there the price climbs in steps as tracked users grow: $49 a month at 200 tracked users, $125 a month at 500, and $249 a month at 1,000. Core covers the essential feedback board and roadmap features without some of the more advanced admin controls reserved for Pro." },
      { h2: "Pro tier: added controls, added cost", p: "Canny's Pro plan starts at $79 a month annually for the same 100-tracked-user baseline, rising to $129 at 200 tracked users, $279 at 500, and $529 at 1,000. Pro unlocks features Core does not, typically things like single sign-on, more granular admin permissions and priority support, but the jump from Core's equivalent tier is substantial, more than four times the price at the entry level." },
      { table: { caption: "Canny.io pricing by tracked-user tier, 2026", head: ["Tracked users", "Core (annual)", "Pro (annual)"], rows: [
        ["Up to 25", "Free", "Free"],
        ["100", "$19/mo", "$79/mo"],
        ["200", "$49/mo", "$129/mo"],
        ["500", "$125/mo", "$279/mo"],
        ["1,000", "$249/mo", "$529/mo"],
      ] } },
      { h2: "What counts as a tracked user", p: "A tracked user is anyone who has given feedback, whether by creating a post, voting or commenting, and that action can be taken by the user directly, by an admin logging it on their behalf, or by automated tooling. This definition matters because it means tracked-user count is not simply your paying customer count; it is anyone who has engaged with the board at all, including free-tier users and even prospects browsing a public roadmap before signing up." },
      { h2: "Monthly versus annual billing", p: "Most Canny customers purchase annual subscriptions specifically to access the lower per-month pricing shown above. Monthly billing is available but typically runs 20 to 30% more per month than the annualised rate, which is worth factoring in if you are budgeting month to month rather than committing upfront for a full year." },
      { h2: "Spend limits as a safety net", p: "Canny lets accounts set a monthly spend limit, pausing automatic upgrades once that ceiling is hit rather than silently billing a higher tier. This is a genuinely useful control for teams worried about an unexpected tracked-user spike, though it comes with a tradeoff: hitting the limit means the board stops accepting new engagement past that point until someone manually raises it." },
      { h2: "Why Core-to-Pro is a bigger jump than it first looks", p: "At every tracked-user threshold shown above, Pro costs roughly four times what Core does for the same tracked-user allowance. That gap is worth scrutinising closely before committing, since it means the decision between Core and Pro matters as much to your total bill as the tracked-user tier itself. If your team only needs single sign-on or one specific Pro-only feature, it is worth checking whether that single feature justifies quadrupling the monthly cost." },
      { quote: { text: "Tracked-user pricing means the bill is really a function of how well your feedback board works. A board that gets ignored stays cheap. A board that succeeds gets expensive, which is a strange incentive to build into a feedback tool.", cite: "Feedlark Team" } },
      { h2: "How this compares to a per-seat model", p: "Feedlark charges only for admin seats, [from $19 a month](/pricing), with unlimited end-users included free on every plan. A team of five admins managing a board with 2,000 engaged voters pays the same flat rate as a team of five managing a board with twenty. Under Canny's tracked-user model, that same growth from twenty to two thousand voters would move an account through several pricing tiers automatically, regardless of team size." },
      { h2: "Forecasting your own likely tier", p: "Before signing up for either Core or Pro, estimate your tracked-user count six months out rather than today. Look at current active users, assume a modest share, typically two to ten percent, will eventually engage with an embedded feedback widget, and check where that lands against the tier boundaries above. Budgeting for the tier above your current estimate avoids the unpleasant surprise of an unplanned upgrade mid-quarter." },
      { h2: "Who Canny's pricing still works well for", p: "A team with a genuinely small, stable user base, unlikely to grow much past a few hundred tracked users, can stay comfortably on Core for a long time without much cost pressure. The calculation changes once meaningful growth is the actual goal, which describes most SaaS teams evaluating a pricing page in the first place." },
      { h2: "What Canny includes regardless of tier", p: "Both Core and Pro include the fundamentals: a public feedback board, voting, a roadmap view and integrations with common tools like Slack and Jira. The distinction between tiers is less about core functionality and more about administrative depth, single sign-on, granular permissions and support response times, which matters more for larger, more security-conscious organisations than for a small SaaS team just getting a feedback board off the ground." },
      { h2: "A checklist before signing up for either tier", ul: [
        "Estimate your tracked-user count six months out, not today, before picking a starting tier",
        "Confirm which specific Pro-only feature you actually need, if any, before paying the roughly 4x premium over Core",
        "Set a monthly spend limit from day one if unpredictable billing is a genuine concern for your team",
        "Compare the total annual cost at your projected tracked-user count against a flat per-seat alternative",
      ] },
    ],
    takeaways: [
      "Canny's free plan caps at 25 tracked users; Core starts at $19/mo and Pro at $79/mo, both for up to 100 tracked users.",
      "Pro costs roughly four times Core at every tracked-user tier, for single sign-on, deeper permissions and priority support.",
      "A tracked user is anyone who posts, votes or comments, not just paying customers, which makes the count grow faster than expected.",
      "A per-seat alternative like Feedlark keeps costs flat regardless of tracked-user growth.",
    ],
    faqs: [
      { q: "What is the actual difference between Canny Core and Pro?", a: "Pro adds features like single sign-on, more granular admin permissions and priority support on top of Core's base feedback board and roadmap functionality, at roughly four times the price for the same tracked-user allowance." },
      { q: "How much does Canny cost for 500 tracked users?", a: "$125 a month on Core, or $279 a month on Pro, both billed annually. Monthly billing runs 20 to 30% higher per month than these annualised rates." },
      { q: "Does Canny's free plan ever expire?", a: "It stays free indefinitely as long as the account stays under 25 tracked users. Crossing that threshold requires an upgrade to Core or Pro to keep the board fully functional." },
      { q: "Is there a way to avoid tracked-user pricing entirely?", a: "Yes. Tools billed per admin seat instead of tracked user, such as Feedlark, keep costs flat regardless of how many end-users vote or comment, which avoids the growth-linked billing model tracked-user pricing creates." },
    ],
  },
  {
    slug: "free-roadmap-creator-tools",
    title: "6 free roadmap creator tools compared for 2026",
    description:
      "A comparison of six free roadmap creator tools for 2026, covering what is genuinely free versus trial-limited, and which fits different team sizes.",
    date: "2026-07-19",
    keyword: "free roadmap creator",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1586974710160-55f48f417990?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Stacked coins on a wooden surface, representing free versus paid roadmap creator tools",
    readMins: 7,
    blocks: [
      { p: "'Free roadmap creator' searches usually turn up a mix of genuinely free tools and time-limited trials wearing the word 'free' loosely. Here is an honest comparison of six options, split clearly between what is actually free indefinitely and what is a trial with a countdown clock, so you know exactly what you are signing up for." },
      { h2: "Feedlark (genuinely free)", p: "Feedlark's roadmap, feedback board and changelog are free forever for unlimited end-users, with paid seats [from $19 a month](/pricing) only for teams wanting custom branding or private boards. There is no trial clock and no tracked-user cap forcing an upgrade as your board grows, which makes it a genuinely free roadmap creator rather than a disguised trial." },
      { h2: "Fider (genuinely free, self-hosted)", p: "Fider is open source and free if you host it yourself. It covers voting, statuses and a public roadmap view with full control over your own data, at the cost of taking on server setup and ongoing maintenance, which is a real cost even though no licence fee is involved." },
      { h2: "Trello with a public board (genuinely free, informal)", p: "A public Trello board with columns for Planned, In Progress and Shipped is a genuinely free way to create a basic roadmap, and plenty of small teams start here. It lacks voting, deduplication and any notification automation, so it works best as a temporary starting point rather than a long-term system once request volume grows." },
      { h2: "Canny (trial only)", p: "Canny's entry tier requires payment past 25 tracked users, so while it advertises a free plan, it is better understood as a capped free tier rather than an unlimited free roadmap creator. Our [full Canny pricing breakdown](/blog/canny-io-pricing-breakdown-2026) covers exactly where that cap bites." },
      { h2: "Productboard (trial only)", p: "Productboard offers a time-limited trial rather than an ongoing free tier, after which pricing moves to a per-maker-seat model aimed at larger product teams. It is a strong tool for that audience but not a genuinely free option for an indefinite roadmap creator use case." },
      { h2: "ProductPlan (trial only)", p: "ProductPlan similarly offers a trial period rather than a lasting free tier, with pricing structured per editor seat afterward. It is worth considering if presentation-quality roadmap views for stakeholder communication are the primary need, once you are ready to pay." },
      { table: { caption: "Free roadmap creator tools: genuinely free versus trial-limited", head: ["Tool", "Free status", "Catch, if any"], rows: [
        ["Feedlark", "Genuinely free, unlimited end-users", "Paid seats needed for branding or private boards"],
        ["Fider", "Genuinely free, self-hosted", "You manage the server and maintenance yourself"],
        ["Trello (public board)", "Genuinely free", "No voting, dedup or notification automation"],
        ["Canny", "Free up to 25 tracked users", "Upgrade required once that cap is crossed"],
        ["Productboard", "Trial only", "Converts to per-maker-seat pricing after trial"],
        ["ProductPlan", "Trial only", "Converts to per-editor pricing after trial"],
      ] } },
      { h2: "Why the distinction matters", p: "A tool advertised as 'free' that actually caps out at a small user count, or expires after a trial window, can create a costly mid-project surprise if you build your process around it assuming it will stay free indefinitely. Checking this distinction before committing, not after your board is already live and growing, avoids a forced, disruptive migration later." },
      { quote: { text: "'Free' should mean free, not 'free until it starts working, at which point please pay us.' Read the actual cap before you build a process around a tool.", cite: "Feedlark Team" } },
      { h2: "What a genuinely free tool gives up, if anything", p: "It is fair to ask what a genuinely free roadmap creator sacrifices to offer that. In Feedlark's case, the free plan covers the full core loop, feedback, roadmap and changelog, with paid seats reserved for things like custom branding and private boards rather than core functionality. That is a different tradeoff than a capped free tier, which limits the core functionality itself once you cross a user threshold." },
      { h2: "Choosing based on your actual constraint", p: "If your constraint is budget with no appetite for server maintenance, Feedlark is the more direct fit. If your constraint is budget but your team is comfortable running infrastructure, Fider's self-hosted model is worth the setup time. If you just need something today with no roadmap features beyond a visual status board, a public Trello board genuinely works as a stopgap, provided you accept its limits early rather than being surprised by them later." },
      { h2: "What happens when you outgrow the free option", p: "It is worth thinking one step ahead: a public Trello board or a capped free tier will eventually need replacing once request volume or user engagement grows past what it can comfortably handle. Migrating early, before frustration sets in, tends to be far less disruptive than migrating under pressure once a board has become genuinely unmanageable. If you start on a free stopgap deliberately, revisit the decision every quarter rather than letting inertia decide for you." },
      { h2: "Small business software spending context", p: "Small businesses reportedly waste a meaningful share of their software budget on underutilised tools, according to industry research on small business technology spending, which makes a genuinely free roadmap creator with no hidden cap a particularly good fit for early-stage teams still validating whether a formal roadmap process is worth the investment at all before committing real budget to it." },
      { h2: "How to avoid the trial-window trap", p: "Before starting a trial-only tool's clock, have a specific evaluation plan ready rather than a vague intention to 'try it out'. Decide in advance what you need to confirm, ease of setup, whether your team will actually use it, whether the public view looks right, and run through that checklist deliberately within the trial window. Teams that start a trial without a plan often let it lapse into a default paid subscription simply because nobody got round to a proper evaluation before the countdown ran out." },
    ],
    takeaways: [
      "Six tools compared here split into genuinely free, capped-free, and trial-only, with meaningfully different long-term costs.",
      "Feedlark and Fider are genuinely free indefinitely; Canny's free tier caps at 25 tracked users.",
      "Productboard and ProductPlan are trial-only, converting to paid seat pricing once the trial ends.",
      "Check exactly what 'free' means for a tool before building your process around it, to avoid a forced migration later.",
    ],
    faqs: [
      { q: "Is Feedlark actually free, or is there a hidden catch?", a: "The core loop, feedback board, roadmap and changelog, is free forever for unlimited end-users. Paid seats are only needed for extras like custom branding or private boards, not core functionality." },
      { q: "What is the most limited genuinely free roadmap creator?", a: "A public Trello board is free with no cap, but it lacks voting, deduplication and notification automation, making it best suited to a temporary or very early-stage setup." },
      { q: "Does Canny have a genuinely free plan?", a: "It has a free tier capped at 25 tracked users. Past that threshold, an upgrade to a paid plan is required, so it functions more as a limited trial than an indefinitely free roadmap creator." },
      { q: "Is a self-hosted free tool like Fider worth the maintenance effort?", a: "It depends on your team's comfort with running infrastructure. For a technical team prioritising full data control, yes. For a team without spare engineering capacity, a hosted free option is usually the more practical choice." },
    ],
  },
  {
    slug: "open-source-roadmap-tools-compared",
    title: "Open source roadmap tools: 5 options compared",
    description:
      "A comparison of five open source roadmap tools for 2026, covering setup effort, feature depth, and what self-hosting actually costs beyond licensing.",
    date: "2026-07-19",
    keyword: "open source roadmap tools",
    category: "Reviews",
    author: "Tom Whitfield, Feedlark co-founder",
    authorBio: "Tom co-founded Feedlark after years of watching product teams lose good ideas in messy spreadsheets.",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Computer screen showing lines of code, representing an open source roadmap tool codebase",
    readMins: 8,
    blocks: [
      { p: "Open source roadmap tools trade licensing cost for setup and maintenance responsibility, a tradeoff that genuinely suits some teams and genuinely does not suit others. Here is a comparison of five options, with an honest look at what 'free' really costs once server time and ongoing upkeep are factored in, alongside where trends in open source adoption more broadly are heading." },
      { h2: "Fider", p: "Fider is the most directly comparable open source option to a dedicated feedback and roadmap SaaS tool: voting, statuses, comments and a public roadmap view, all self-hostable. It is actively maintained and reasonably straightforward to deploy for a team with basic DevOps capability, though updates and uptime become your responsibility entirely once it is running." },
      { h2: "Focalboard", p: "Focalboard, from the team behind Mattermost, is a broader project and task management tool that can be configured as a lightweight roadmap view, though it is not purpose-built for public-facing feedback collection the way Fider is. It suits teams already using Mattermost's ecosystem who want a roadmap view without adding another separate system." },
      { h2: "Wekan", p: "Wekan is an open source Kanban board that can be adapted into a simple roadmap view with columns for Planned, In Progress and Shipped. It is general-purpose rather than roadmap-specific, so it lacks voting or public feedback collection out of the box, making it better suited to internal roadmap tracking than a customer-facing board." },
      { h2: "Taiga", p: "Taiga is a fuller open source project management platform with sprint planning and backlog features alongside a roadmap-style epic view. It fits teams that want an open source alternative to a tool like Jira with roadmap visualisation included, more than teams specifically looking for public feedback collection." },
      { h2: "OpenProject", p: "OpenProject offers Gantt-style roadmap and timeline views as part of a broader open source project management suite, with both a free community edition and a paid enterprise tier for additional support and features. It suits teams wanting formal project timeline management more than lightweight public roadmap communication." },
      { table: { caption: "Open source roadmap tools compared", head: ["Tool", "Best for", "Public feedback collection"], rows: [
        ["Fider", "Direct feedback-and-roadmap replacement", "Yes, built in"],
        ["Focalboard", "Teams already using Mattermost", "No, general task boards"],
        ["Wekan", "Simple internal Kanban-style roadmap", "No, general Kanban board"],
        ["Taiga", "Open source Jira alternative with roadmap view", "No, internal sprint focus"],
        ["OpenProject", "Formal timeline and Gantt-style planning", "No, project management focus"],
      ] } },
      { h2: "What open source adoption looks like right now", p: "Open source usage is not a niche choice; 98% of organisations increased or maintained their use of open source software in the past year, with nearly half reporting genuine year-over-year growth, according to the [2026 State of Open Source Report from OpenLogic and the Open Source Initiative](https://www.openlogic.com/resources/state-of-open-source-report). Notably, avoiding vendor lock-in has surged as a stated motivation, up sharply year over year and cited by a majority of respondents, particularly in Europe and the UK, alongside the more familiar cost-saving rationale." },
      { h2: "The real cost of 'free'", p: "The same research found that nearly half of organisations spend 50% or more of their engineering time on maintenance and bug fixes rather than new development, a figure that rises to 60% among large enterprises specifically working with open source components. Self-hosting a roadmap tool inherits a small share of that same burden: server provisioning, security patching, and the occasional weekend spent debugging a failed update are real costs, even without a licence fee attached." },
      { quote: { text: "Open source roadmap tools are not free. They are free of licensing cost and expensive in engineering time, and which of those two currencies your team has more of should decide the choice.", cite: "Tom Whitfield, Feedlark co-founder" } },
      { h2: "When self-hosting genuinely makes sense", p: "Self-hosting an open source roadmap tool makes the most sense for teams with existing DevOps capacity who value complete data control, often for compliance or data residency reasons, and who are willing to treat the tool as one more service to maintain alongside everything else they already run. It makes less sense for a small product team without dedicated infrastructure support, where the maintenance burden competes directly with time that could go toward the product itself." },
      { h2: "A middle path worth considering", p: "If the appeal of open source is avoiding vendor lock-in specifically, rather than avoiding cost, it is worth checking whether a hosted tool offers a clean, complete data export. Feedlark, for instance, is not open source but does not lock feedback and roadmap data into a proprietary format that resists export, which addresses the lock-in concern without taking on server maintenance directly." },
      { h2: "Security patching: the least visible ongoing cost", p: "Security updates and patching remain one of the most persistent challenges cited in open source adoption research regardless of organisation size, and a meaningful share of organisations that failed a compliance audit in the past year had end-of-life open source software still running in their stack. An open source roadmap tool left unpatched for a year is a real, if easy to overlook, security liability, not just a maintenance inconvenience." },
      { h2: "A short anecdote on the maintenance tradeoff", p: "A technical team we spoke with self-hosted Fider for just over a year, drawn by full data control and no per-seat cost. It worked well until a routine dependency update broke the deployment during a busy sprint, costing a full day of engineering time to diagnose and fix, time that had nothing to do with their actual product. They kept the tool in the end, judging the tradeoff worth it for their specific compliance needs, but the incident became the moment the team stopped treating 'free' as the same thing as 'costs nothing'." },
      { h2: "A quick decision guide", ul: [
        "Choose Fider if you specifically want a feedback-and-roadmap replacement and have DevOps capacity to spare",
        "Choose a general platform like Taiga or OpenProject if you want an open source alternative to a broader project management suite",
        "Choose a hosted SaaS tool if engineering time is your scarcer resource relative to budget",
        "Choose a hosted tool with clean data export if vendor lock-in, not cost, is your primary concern",
      ] },
    ],
    takeaways: [
      "Five open source options compared here range from dedicated feedback tools like Fider to general project platforms adapted for roadmap use.",
      "98% of organisations grew or maintained open source usage in the past year, with vendor lock-in avoidance rising sharply as a motivation.",
      "Nearly half of organisations spend 50%+ of engineering time on maintenance rather than new development, a real hidden cost of self-hosting.",
      "A hosted tool with clean data export can address lock-in concerns without taking on server maintenance directly.",
    ],
    faqs: [
      { q: "Which open source tool is closest to a dedicated feedback and roadmap platform?", a: "Fider, since it includes voting, statuses and a public roadmap view natively, unlike the more general project management tools on this list which need adapting for that specific use case." },
      { q: "Is self-hosting an open source roadmap tool actually free?", a: "Not entirely. There is no licence fee, but server hosting, security patching and ongoing maintenance are real, ongoing costs in engineering time, which research shows consumes a significant share of teams' capacity." },
      { q: "Why are organisations increasingly choosing open source software?", a: "Cost saving remains the top reason, but avoiding vendor lock-in has surged as a motivation recently, particularly among European and UK organisations, according to the 2026 State of Open Source Report." },
      { q: "Is there a middle ground between open source and a proprietary SaaS tool?", a: "Yes. A hosted tool that offers clean, complete data export addresses the lock-in concern that drives many teams toward open source, without requiring them to take on server maintenance themselves." },
    ],
  },
];
