import type { BlogCategory, BlogPost } from "./blog-types";

type Guide = {
  slug: string;
  title: string;
  description: string;
  date: string;
  keyword: string;
  supportingKeywords: string[];
  longTailKeywords: string[];
  category: BlogCategory;
  image: string;
  imageAlt: string;
  hook: string;
  context: string;
  workflowTitle: string;
  workflow: string;
  example: string;
  pitfall: string;
  next: string;
  quote: string;
};

const IMAGE = {
  widget: "https://images.unsplash.com/photo-1551651653-c5186a1fbba2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
  board: "https://images.unsplash.com/photo-1532622785990-d2c36a76f5a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
  // Selected through the Pipedream Unsplash integration (photo ID p0lRVTkrfpE, Sandisk).
  analysis: "https://images.unsplash.com/photo-1779896412431-3160ade4ca01?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NTAzODN8MHwxfGFsbHx8fHx8fHx8fDE3OTAyMDU1MTZ8&ixlib=rb-4.1.0&q=80&w=1080",
  roadmap: "https://images.unsplash.com/photo-1503551723145-6c040742065b-v2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
  release: "https://images.unsplash.com/photo-1575024357670-2b5164f470c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

function guide(post: Guide): BlogPost {
  const isHowTo = post.category === "Academy";
  return {
    slug: post.slug,
    title: post.title,
    description: post.description,
    date: post.date,
    keyword: post.keyword,
    supportingKeywords: post.supportingKeywords,
    longTailKeywords: post.longTailKeywords,
    category: post.category,
    author: "Feedlark Team",
    authorBio: "The Feedlark team builds the feedback boards, public roadmaps and changelogs used in the workflows described here.",
    schemaType: isHowTo ? "HowTo" : "BlogPosting",
    image: post.image,
    imageAlt: post.imageAlt,
    readMins: 9,
    takeaways: [
      `${post.keyword[0].toUpperCase()}${post.keyword.slice(1)} works best when it is part of a clear loop, not another isolated place for comments to disappear.`,
      "Make one route obvious, keep the first action small, and give people a visible way to follow what happens next.",
      "Votes and repeated reports are useful demand signals, but they need context from customer conversations, strategy and delivery effort.",
      "A short weekly review prevents small pieces of feedback becoming an unsearchable pile by the end of the quarter.",
    ],
    blocks: [
      { p: post.hook },
      { h2: `What ${post.keyword} means in practice`, p: post.context },
      { h2: "Start with the job, not the screen", p: `Before adding ${post.keyword} to a product or website, write down the moment that should trigger it. Is somebody stuck, deciding whether to renew, trying a new feature, or responding to a release? That answer determines the prompt, the right amount of context and where the response should land. A blank box labelled “Feedback” asks people to do the sorting for you. A specific invitation, such as “What stopped you completing this step?”, produces a more useful first sentence and makes triage far less painful.` },
      { table: { caption: `A practical scorecard for a ${post.keyword} setup`, head: ["Check", "A useful default", "Warning sign"], rows: [
        ["First action", "One short prompt and a clear submit button", "A long form before someone can explain the issue"],
        ["Destination", "One queue where the team can search, merge and assign", "Comments split between inboxes, chat and spreadsheets"],
        ["Demand signal", "People can add a vote or join an existing request", "Every similar suggestion starts a fresh thread"],
        ["Follow-through", "Reporter can see a status or receives a shipping update", "The message disappears after submission"],
      ] } },
      { h2: post.workflowTitle, p: post.workflow },
      { h2: "A small operating rhythm that keeps it useful", ul: [
        `Review new ${post.keyword} items on a fixed weekly slot, even when there are only a few. Consistency makes ownership visible.`,
        "Merge genuine duplicates early and keep the clearest title, so demand gathers on one item instead of being split across lookalikes.",
        "Add a plain status only when it has a clear owner: under review, planned, in progress or shipped are usually enough for customers.",
        "When an item ships, connect it to a release note and tell the people who asked. That is the bit most teams leave on the cutting-room floor.",
      ] },
      { quote: { text: post.quote, cite: "Feedlark Team" } },
      { h2: "A realistic example", p: post.example },
      { h2: "The mistake that makes this feel like a black hole", p: post.pitfall },
      { h2: "Make the next step visible", p: `${post.next} Link the collection point to a [feature request tracking workflow](/blog/how-to-track-feature-requests), then make its priorities visible on a [public roadmap](/blog/how-to-build-public-roadmap). When work is finished, a readable [changelog](/blog/how-to-write-a-changelog) is the final hand-off. These links matter because they show a customer the route their idea takes after they press submit, rather than asking them to trust an invisible internal process.` },
      { h2: "What good looks like after the first month", p: `After four weeks, ${post.keyword} should leave a clear trail: new input is acknowledged, similar items have been grouped, the highest-signal themes have a decision or an owner, and contributors can see at least one honest update. Do not judge the setup by raw submission volume. Judge it by whether a product teammate can explain the evidence behind a priority and a customer can understand what happened to their idea.` },
      { h2: "Sources worth keeping nearby", p: `Good feedback collection should be understandable and usable by more than the loudest people in a customer base. The [W3C introduction to web accessibility](https://www.w3.org/WAI/fundamentals/accessibility-intro/) is a sound starting point for accessible controls and clear interaction. For the research side, the [GOV.UK Service Manual on user research](https://www.gov.uk/service-manual/user-research) is a useful reminder to learn from real users in the context of their task. Neither source is a product-management playbook, but both help keep the collection step honest.` },
    ],
    faqs: [
      { q: `What should a ${post.keyword} process include?`, a: `At minimum, it needs an obvious place to submit or vote, one shared queue, a named review cadence and a way to tell contributors what happened. The tool matters less than those four habits, because each fixes a different point where customer input otherwise gets lost.` },
      { q: `How do I get more useful ${post.keyword} input?`, a: `Ask about the specific task or moment someone has just experienced, rather than asking for general opinions. Let people add context in their own words, then give them the option to vote on an existing item. Specific prompts create better signal without making the form feel like homework.` },
      { q: `Should every request be added to the roadmap?`, a: `No. A roadmap is a commitment to focus, not a public copy of every idea. Keep the request visible, assess its demand and strategic fit, then move only the work you intend to pursue into a clear public status. Saying “under review” is more credible than quietly overpromising.` },
      { q: `How often should a team review feedback?`, a: `Weekly suits most small SaaS teams because it is frequent enough to acknowledge new input before it goes stale without turning into a daily meeting. Higher-volume products may need a short daily pass, but the important thing is that someone owns the cadence and the queue remains searchable.` },
    ],
  };
}

const GUIDES: Guide[] = [
  {
    slug: "feedback-widget-guide", title: "Feedback widget: how to choose and launch one", date: "2026-09-17", keyword: "feedback widget", category: "Academy",
    description: "Choose and launch a feedback widget that captures useful product signal without interrupting customers or creating another unowned inbox for your team.",
    supportingKeywords: ["website feedback widget", "embedded feedback", "product feedback", "feedback button", "customer suggestions", "in-app feedback", "feedback board"],
    longTailKeywords: ["how to add a feedback widget to a website", "where should a feedback widget appear", "what makes a feedback widget useful"],
    image: IMAGE.widget, imageAlt: "Feedback widget on a product screen for collecting customer feedback",
    hook: "A feedback widget looks like a tiny addition, usually a button tucked into a corner. In practice, it decides whether a useful observation turns into product signal or vanishes after a customer mutters ‘that was annoying’ and moves on. The best widgets are quiet until they are needed, quick when they are opened, and connected to a process somebody actually owns.",
    context: "A feedback widget is an embedded entry point for product ideas, questions and friction reports. It is not a survey in miniature and it should not pretend to replace customer interviews. Its job is to capture an observation while the screen, task and language are still fresh. That makes it particularly helpful for SaaS teams whose best feedback currently arrives late, stripped of context, in support tickets or sales calls.",
    workflowTitle: "Choose the placement from the customer journey", workflow: "Map the first version to one or two moments with genuine uncertainty. A floating button on every page is fine for broad discovery, but a contextual prompt beside an export, invite or payment action often produces clearer feedback. Add the product area or current URL automatically if the implementation allows it, then ask one short question. Start with a small placement set and compare the quality of submitted items before expanding it.",
    example: "Imagine a customer reaches an integration settings page, clicks through the connector list, and cannot find the system they use. A widget beside that list can ask ‘Which connection are you looking for?’. One answer is anecdotal. Ten similar answers, gathered against the same context, point to a category worth investigating. That is much stronger than a generic ‘please add integrations’ request sent weeks later.",
    pitfall: "The common mistake is treating a widget as an unattended suggestion box. If a submitted item has no status, no duplicate check and no route into planning, people learn that the button is decorative. Another easy miss is using it for every question on every screen. The result is noise, reduced trust and a team that starts ignoring its own queue.",
    next: "Launch with one visible owner, a weekly review slot and a simple acknowledgement message. Watch which screens generate repeat themes, not only which button gets the most clicks. Once the first set of requests has an owner and a status, add the widget to another high-intent part of the journey.",
    quote: "A widget earns its place when it catches a thought at the exact moment somebody has it, then gives the team enough context to act without asking the customer to reconstruct the scene later.",
  },
  {
    slug: "user-feedback-widget-guide", title: "User feedback widget: a practical setup guide", date: "2026-09-17", keyword: "user feedback widget", category: "Academy",
    description: "Set up a user feedback widget that turns in-context comments into organised product decisions, with clear prompts, ownership and follow-up every week.",
    supportingKeywords: ["in-app feedback", "user feedback tool", "feedback prompt", "contextual feedback", "product discovery", "customer feedback widget", "feedback collection"],
    longTailKeywords: ["how to set up an in-app feedback widget", "what should a feedback widget ask", "how to collect contextual user feedback"],
    image: IMAGE.widget, imageAlt: "User feedback widget in an app interface for contextual product feedback",
    hook: "People are rarely at their most articulate after they have closed the tab, opened a support ticket and tried to remember what went wrong. A user feedback widget shortens that distance. Used well, it captures a sentence while a customer is still looking at the awkward screen, which gives a product team a much fairer chance of understanding the problem.",
    context: "The difference between a user feedback widget and a general contact form is context. A widget belongs inside the product and should inherit the moment around it: the page, feature area and sometimes the state of a task. It is useful for qualitative signal, not a substitute for error tracking or a quantitative usability study. Think of it as an always-available doorway into your product discovery process.",
    workflowTitle: "Write prompts that give people a useful starting point", workflow: "Match the prompt to the screen. On a new workflow, ask what felt unclear. On a reporting page, ask what decision someone could not make. Avoid the broad ‘How can we improve?’ prompt until you have learnt the specific jobs that matter. Keep free text available, because forcing customers into a neat category too early can hide the language that reveals a real issue.",
    example: "A small finance app added a feedback control to its invoice editor after seeing users abandon drafts. Instead of asking for a rating, it asked what stopped them finishing. The replies split into two themes: missing tax fields and uncertainty over who could see a draft. The team could then test those issues directly, rather than spending a sprint polishing the editor’s colours because that was the easiest visible change.",
    pitfall: "Do not make the widget a shortcut for skipping conversations. A short response can tell you where to look; it rarely tells you the whole reason behind a customer’s decision. The other trap is an aggressive pop-up. If the control blocks the job it is meant to learn from, the feedback you collect will mostly be about the widget itself. Bit of an own goal.",
    next: "Start with one contextual question on a key workflow and review replies alongside support contacts from the same area. Save the exact words customers use, merge repeated requests and invite a few people to a follow-up conversation. That combination preserves the speed of a widget without mistaking a comment for the final answer.",
    quote: "Context is the quiet advantage of in-app feedback. The closer the question sits to the task, the less a customer has to translate their experience into a generic product suggestion.",
  },
  {
    slug: "customer-feedback-widget-guide", title: "Customer feedback widget for SaaS teams", date: "2026-09-18", keyword: "customer feedback widget", category: "Academy",
    description: "Build a customer feedback widget into your SaaS product to collect actionable requests, avoid duplicate reports and close the loop after shipping.",
    supportingKeywords: ["SaaS feedback", "customer feedback software", "feature requests", "feedback collection", "product feedback board", "customer voice", "feedback workflow"],
    longTailKeywords: ["how should a SaaS feedback widget work", "how to collect customer feature requests", "how to close the customer feedback loop"],
    image: IMAGE.board, imageAlt: "Customer feedback widget feeding requests into a SaaS feedback board",
    hook: "A SaaS customer feedback widget should do more than collect messages. It should give customers a route to see an existing idea, add their support to it and follow its progress. Otherwise every thoughtful suggestion becomes a new thread, a new support task and eventually a new bit of evidence someone must hunt down during planning.",
    context: "For SaaS teams, a customer feedback widget is a front door to a shared product record. The useful version connects three things: a quick submission, a place to vote or discuss an existing request, and a visible outcome when the work moves. That is what separates it from a generic support bubble. Support needs a response to one customer. Product needs a pattern across many customers.",
    workflowTitle: "Connect the widget to a public record", workflow: "Let the initial widget action search or show relevant open requests before it creates a new one. Keep the match suggestions modest and let an admin confirm duplicates, because similar wording is not always the same need. When a request is accepted, connect it to a roadmap status. When it ships, publish a short changelog note in language a customer will recognise, then notify the people who supported it.",
    example: "Take a team that keeps hearing ‘I need better reporting’. On its own, that phrase is too broad to plan. A widget that invites people to add a use case surfaces sharper requests: exporting by month, filtering by account owner, or scheduling an email. Those requests can gather votes separately. The roadmap then reflects a genuine decision rather than a vague promise to improve reporting someday.",
    pitfall: "Avoid using vote totals as an automatic build order. A loud feature might matter to a small segment, while a lower-voted problem may block an important customer journey. Use votes as one input alongside interviews, usage, support burden and strategy. Equally, do not hide every item from customers until it is built. A quiet ‘under review’ status can be more helpful than silence.",
    next: "Define what happens after a submission before publishing the widget. Who checks it, how fast, where does it sit, and what message does the customer receive? Once those answers are in place, the widget becomes a reliable customer-facing part of planning rather than a hopeful little button in the corner.",
    quote: "The moment a customer can see their request beside similar requests and later receive a shipping update, feedback stops feeling like a favour they did for your team and starts feeling like a relationship.",
  },
  {
    slug: "free-feedback-widget-guide", title: "Free feedback widget: what to check first", date: "2026-09-18", keyword: "free feedback widget", category: "Reviews",
    description: "Compare what a free feedback widget needs to include, from no-login voting and public boards to accessible embed options and useful follow-up.",
    supportingKeywords: ["free feedback tool", "feedback widget for website", "no-login voting", "free product feedback", "embedded feedback", "feature voting", "public roadmap"],
    longTailKeywords: ["what is included in a free feedback widget", "is a free feedback widget enough for SaaS", "how to compare free feedback tools"],
    image: IMAGE.widget, imageAlt: "Free feedback widget displayed on a website for collecting product suggestions",
    hook: "Free can mean genuinely useful, carefully limited, or merely a short trial with the price hidden one click away. That is why a free feedback widget is worth evaluating as a workflow rather than a badge on a pricing page. If it captures ideas but locks the board, voting or follow-up behind a paywall, you may only discover the real cost after customers have started using it.",
    context: "A free feedback widget is enough for many early-stage teams when it provides the full basic loop: collect, organise, decide and notify. The questions are practical. Can customers submit without creating yet another account? Can they vote on an idea rather than write it again? Can your team maintain a public roadmap and changelog? And will the tool introduce a growth charge for the very customers you are trying to listen to?",
    workflowTitle: "Compare the workflow, not just the free-plan headline", workflow: "Put three or four candidate tools through the same short scenario. Add a widget to a test page, submit a request, find it again, vote from a second browser, move it to a roadmap status and publish a shipping note. Note where friction appears. A product that has every feature in a comparison table can still make the basic path needlessly fiddly, while a simpler option may get the important bits right.",
    example: "A two-person SaaS team compared tools after collecting requests in a shared inbox. One tool offered a free widget but required visitors to register before voting, so most people abandoned the flow. Another kept submissions and votes simple but had no public view of status. The team chose the option that made it easy for a customer to contribute and later see an outcome, even though its dashboard had fewer decorative extras.",
    pitfall: "The usual mistake is selecting a free plan for features that are irrelevant in the first month, then finding that the core activity is capped later. Check whether limits apply to voters, boards, posts, team members, branding or notifications. Also look for a clear export path. You are building a customer record, so it should not become a hostage situation if your needs change.",
    next: "Run the test with a real colleague acting as a customer and make them complete the loop without coaching. If they cannot find the button, understand the request list or see what changed, keep looking. A free tool should help you learn before you need a more complex process, not force you to relearn the basics later.",
    quote: "The best free plan is not the one with the longest feature list. It is the one that lets a customer make a useful contribution, lets a small team act on it, and does not charge more simply because people participate.",
  },
  {
    slug: "no-login-feedback-guide", title: "No-login feedback: remove the voting barrier", date: "2026-09-18", keyword: "no-login feedback", category: "Academy",
    description: "Learn when no-login feedback and voting increase useful product signal, how to protect quality, and where a light identity check still makes sense.",
    supportingKeywords: ["no-login voting", "anonymous feedback", "customer feedback", "feature request board", "feedback widget", "product suggestions", "vote on features"],
    longTailKeywords: ["should customers need an account to vote", "how to collect no-login feature requests", "how to prevent spam in anonymous feedback"],
    image: IMAGE.board, imageAlt: "No-login feedback board where customers can vote on product requests",
    hook: "Every extra account screen is a small negotiation with a customer: is this idea important enough to create a password for? Often, it is not. No-login feedback lowers that barrier and makes it easier to spot early demand. It also asks a team to be sensible about quality controls, because open doors need good housekeeping.",
    context: "No-login feedback means someone can submit or vote without first creating a full product account. It is especially useful for prospect-facing roadmaps, embedded widgets and products where a user’s attention is already stretched. It does not mean ‘no safeguards’. You can rate-limit actions, use a honeypot field, ask for an optional email for shipping updates and reserve stronger identity checks for sensitive or account-specific conversations.",
    workflowTitle: "Decide which actions need identity", workflow: "Separate public product signal from private support. Let a visitor support a broad request such as ‘export to CSV’ with minimal friction. For a billing issue, data request or account-specific report, route them to authenticated support instead. Make that distinction visible in the interface so people know why one path is quick and another asks for more detail. This protects customer privacy while preserving an easy way to share product ideas.",
    example: "A company launching a new integration page wanted feedback from trial users as well as paying accounts. Registration-first voting produced very little response. After moving the board behind a no-login widget, requests increased, but a few were duplicates. The team added automatic match suggestions and an admin review queue. They got broader signal without turning the board into a free-for-all.",
    pitfall: "Do not treat anonymous volume as proof by itself. Several votes can indicate interest, but you still need to understand who is asking and what problem they are trying to solve. The opposite mistake is overcorrecting with a wall of verification. If the idea is harmless to collect, the cost of asking for a full account may exceed the benefit of certainty.",
    next: "Start by opening one low-risk board or widget action to no-login voting, then monitor the ratio of useful items to spam and duplicates for a fortnight. Tune the guardrails from actual behaviour. If you later invite contributors to a roadmap or release update, make the email opt-in clear and optional.",
    quote: "No-login feedback is not about lowering standards. It is about removing an unnecessary hurdle from the moment a customer has a useful thought, then applying proportionate checks where the risk actually sits.",
  },
  {
    slug: "product-feedback-board-guide", title: "Product feedback board: build one people use", date: "2026-09-19", keyword: "product feedback board", category: "Academy",
    description: "Build a product feedback board that turns customer suggestions into visible demand, clearer priorities and credible updates from your product team.",
    supportingKeywords: ["feature request board", "customer feedback board", "feature voting", "product feedback", "roadmap", "customer suggestions", "feedback management"],
    longTailKeywords: ["how to make a product feedback board", "what should a feature request board include", "how to organise customer suggestions"],
    image: IMAGE.board, imageAlt: "Product feedback board showing customer feature requests and voting",
    hook: "A product feedback board is deceptively simple: a place to submit an idea, a vote count and a few statuses. Its value comes from the discipline behind it. When customers can see the same board their peers use, recognise an existing request and later watch work move, the board becomes shared evidence instead of another place to park opinions.",
    context: "A product feedback board is a public or private record of requests, ideas and sometimes bugs. It should make repeated demand visible without pretending that popularity is the only thing that matters. Unlike a conventional backlog, its language is customer-facing. The item names should describe outcomes customers recognise, while internal implementation detail remains in the engineering system where it belongs.",
    workflowTitle: "Design the board for scanning, not for your database", workflow: "Use clear titles, a short explanatory sentence and a small number of statuses. Help people find existing items with search and suggested matches before they submit. If you use categories, choose product areas customers understand instead of team names. Finally, make vote counts and updates legible from the list view. A board with good content buried behind five clicks is still hard to use.",
    example: "A reporting product received eight variations of the same request across support: export, download, spreadsheet, CSV and monthly report. Its new board presented the clearest version, ‘Export report data to CSV’, then linked similar submissions to it. Within two weeks, the combined vote count was more informative than eight isolated ticket tags. The PM still interviewed a few voters to understand format and permissions, but the board made the opportunity visible.",
    pitfall: "A feedback board becomes unhelpful when teams copy every internal task into it. Customers do not need an implementation diary. They need clarity about the problems you are considering and the work you have chosen to pursue. The other mistake is leaving rejected requests untouched. A short, respectful explanation can preserve trust; a silent graveyard does not.",
    next: "Seed the board with a modest set of well-understood existing requests, not dozens of half-written items. Add a link from support and your product navigation, then establish the weekly routine before promoting it widely. The board will get better as customers use their own language, as long as the team keeps it tidy.",
    quote: "A strong feedback board does not outsource product strategy to a vote count. It gives strategy better evidence and gives customers a visible answer to the question they are really asking: did anybody hear this?",
  },
  {
    slug: "customer-feedback-portal-guide", title: "Customer feedback portal: a sensible setup", date: "2026-09-19", keyword: "customer feedback portal", category: "Academy",
    description: "Set up a customer feedback portal that brings ideas, votes, roadmap updates and release notes into one clear, customer-facing destination for customers.",
    supportingKeywords: ["customer feedback platform", "feedback portal", "feature requests", "public roadmap", "product changelog", "customer voice", "feedback board"],
    longTailKeywords: ["what is a customer feedback portal", "how to create a customer feedback portal", "what should a feedback portal include"],
    image: IMAGE.roadmap, imageAlt: "Customer feedback portal with feedback board, roadmap and changelog",
    hook: "Customers should not have to know which internal team owns a question before they can share an idea. A customer feedback portal gives them one recognisable place to make a suggestion, support an existing request and check what happened next. It is a small piece of product infrastructure that can save a lot of awkward ‘we have passed that on’ replies.",
    context: "A customer feedback portal combines an intake board with visible progress. For many SaaS products, the useful core is straightforward: a request list, votes or comments, a public roadmap, and a changelog or release feed. It is not a replacement for support, account management or research. It is the common record for product-facing feedback that would otherwise be scattered across those teams.",
    workflowTitle: "Give each part of the portal a clear purpose", workflow: "The board answers ‘what are people asking for?’. The roadmap answers ‘what are you working on?’. The changelog answers ‘what changed?’. Keep those purposes distinct while linking items between them. A request can move to planned without promising a date. A shipped roadmap item can link to a release note explaining the practical outcome. This simple chain helps a customer orient themselves without reading internal process jargon.",
    example: "A team with a successful support centre kept receiving feature suggestions in help articles. It created a portal link in the support navigation and trained support staff to add a request or share the existing one. Six weeks later, common suggestions were no longer buried in closed tickets. Customers who had voted for a bulk-edit feature received a note when it shipped, and support had a simple answer for the next person who asked.",
    pitfall: "Do not set up a portal as a marketing promise and then update it quarterly. The absence of movement is visible. Also resist adding every possible destination on day one: community discussions, support articles, bug status, ideas, internal beta and sales resources. Start with the product loop, make it reliable, then broaden only when there is a clear owner for each new area.",
    next: "Choose a memorable URL, explain the portal’s purpose in one sentence and connect it from places customers already look for help. Populate it with live requests and one or two recent release notes so it feels active from the start. A portal becomes credible through small, regular updates rather than a grand launch.",
    quote: "The useful portal is not a showcase of how organised a company is. It is a practical map for customers who want to know where an idea belongs and whether there is any movement after they share it.",
  },
  {
    slug: "feature-voting-software-guide", title: "Feature voting software: what to look for", date: "2026-09-19", keyword: "feature voting software", category: "Reviews",
    description: "Evaluate feature voting software with a practical checklist covering voter friction, duplicate handling, roadmap connection and post-release follow-up.",
    supportingKeywords: ["feature voting tool", "feature request software", "product feedback tool", "customer votes", "duplicate feature requests", "public roadmap", "changelog"],
    longTailKeywords: ["how to choose feature voting software", "what should a feature voting tool include", "does feature voting improve prioritisation"],
    image: IMAGE.analysis, imageAlt: "Feature voting software dashboard for comparing customer demand",
    hook: "Feature voting software can turn a busy set of customer opinions into a useful demand signal. Or it can simply make the loudest requests look official. The distinction comes down to workflow. Before comparing dashboards, look at how the tool handles friction, duplicate ideas, context and the all-important moment after a team has made a decision.",
    context: "Feature voting software lets customers support product ideas, usually through an upvote on a request board. It is most useful when it gathers equivalent requests into one place and makes the count visible. It should not be treated as a democratic product backlog. Votes show interest; they do not include effort, strategic fit, technical risk or the needs of customers who cannot easily vote.",
    workflowTitle: "Use a realistic test case when comparing tools", workflow: "Create three similar requests in each candidate product, then see how easy it is to search, suggest a match and merge duplicates. Try a vote from a new browser. Move the winning request into a public status, then publish a short release note. This scenario exposes the difference between a basic list with thumbs-up icons and a connected feedback system. It also keeps a sales call from becoming the main source of truth.",
    example: "A product manager was choosing between two voting tools after a surge of requests for better permissions. In the first tool, every customer created a new post because search results were hard to scan. In the second, similar requests were shown before submission and an administrator could merge them while retaining voters. The second option produced a truer picture of demand, even though its charting was less flashy.",
    pitfall: "Avoid comparing feature lists without checking the journey for a voter. Login requirements, confusing public links and weak mobile layouts can dramatically reduce participation. On the team side, look for a humane way to close a request, explain a decision and notify supporters. A raw vote total with no follow-up turns a promising tool into an expectation machine.",
    next: "Pick the tool that makes the ordinary path feel simple: a customer finds or creates an idea, a team member understands the demand, and contributors hear when work progresses. Run a limited pilot on one product area before migrating every historical request. It is easier to refine the process with real behaviour than a perfect spreadsheet.",
    quote: "The quality of a vote is shaped long before the count appears. If people cannot find the existing request, understand what it means or trust the outcome, the number is only pretending to be product evidence.",
  },
  {
    slug: "feedback-inbox-guide", title: "Feedback inbox: turn input into decisions", date: "2026-09-20", keyword: "feedback inbox", category: "Academy",
    description: "Create a feedback inbox that brings requests, support notes and customer comments into one reviewable process without losing valuable context.",
    supportingKeywords: ["customer feedback inbox", "feedback management", "feedback triage", "product feedback", "customer notes", "feature requests", "feedback analysis"],
    longTailKeywords: ["how to organise a customer feedback inbox", "how to triage product feedback", "what should go into a feedback inbox"],
    image: IMAGE.analysis, imageAlt: "Feedback inbox dashboard for organising customer product feedback",
    hook: "A feedback inbox is where product signal goes to either become a decision or quietly lose its shape. The hard part is not collecting the messages. It is preserving enough context to understand them, combining the ones that describe the same need, and giving every item a sensible next step without creating a meeting that eats Tuesday morning.",
    context: "A feedback inbox is a shared holding place for product-facing input from boards, support, sales, interviews and in-app prompts. It is not necessarily a single software screen. What matters is that the team can review a consistent record, see the source and customer context, and route an item into a more specific system. Without that discipline, feedback exists but cannot reliably influence planning.",
    workflowTitle: "Make source and context part of the record", workflow: "When a support teammate adds a note, keep the original wording, product area and a link to the source conversation. When a sales call reveals a request, note the customer segment and the job they are trying to do rather than just the proposed feature. This is a useful distinction: feature wording is often a suggested solution; the job and context tell the product team what to investigate.",
    example: "A small team had a spreadsheet titled ‘feedback’ with hundreds of rows and no consistent source. During triage, it could not tell whether ‘sharing’ meant inviting a colleague, sharing a report or publishing a link. It started using a shared inbox with source labels and short context fields. Within a month, the team found three separate themes hiding under that one word and could plan research instead of guessing.",
    pitfall: "The failure mode is turning the inbox into a second backlog. An inbox should be a place for intake and triage, not a permanent resting place for every thought. If items sit there for months, decide whether they need a research follow-up, a public request, a support reply, an archive or a clear no. Ambiguity is what makes an inbox feel endless.",
    next: "Define a weekly twenty-minute triage with one product owner and a source-aware checklist. Capture new input, merge duplicates, tag the product area and choose an owner or status. Keep detailed delivery tasks in your engineering tracker. That separation lets the inbox stay readable enough for patterns to emerge.",
    quote: "A feedback inbox becomes valuable when it keeps the original customer story attached to the request. Without that story, a backlog is full of proposed fixes and surprisingly little understanding of the problem.",
  },
  {
    slug: "product-feedback-system-guide", title: "Product feedback system: collect to close loop", date: "2026-09-20", keyword: "product feedback system", category: "Academy",
    description: "Build a product feedback system that connects collection, prioritization, roadmap visibility and release updates into one repeatable customer loop.",
    supportingKeywords: ["product feedback", "feedback management system", "feedback loop", "feature requests", "roadmap planning", "customer updates", "changelog tool"],
    longTailKeywords: ["how to build a product feedback system", "what is a product feedback loop", "how to close the loop on customer feedback"],
    image: IMAGE.roadmap, imageAlt: "Product feedback system connecting customer requests, roadmap and changelog",
    hook: "Most teams already collect product feedback. The gap is between collection and closure. A product feedback system gives every stage a home: capture the customer’s words, recognise repeated demand, make a prioritisation decision, show what is moving and tell people when the work is done. Nothing fancy is required, but the hand-offs need to be deliberate.",
    context: "A product feedback system is the operating model around the tools. A board alone is not a system, and neither is a spreadsheet of requests. The system exists when people know where input arrives, who reviews it, how duplicates are handled, what evidence informs priority and how the outcome reaches the customer. This is why small teams can often outperform bigger ones: the path is clear.",
    workflowTitle: "Draw the loop before choosing more tooling", workflow: "Use four plain stages: collect, decide, build, notify. Under each stage, name the artifact and owner. For example, a widget and board collect; a weekly triage and planning session decide; the delivery tracker builds; a roadmap and changelog notify. Where a stage has two unconnected places, note the hand-off. That is where feedback tends to disappear or be retyped without context.",
    example: "A B2B team gathered requests in account-manager notes and planned work in quarterly meetings. Customers kept asking for updates because there was no shared view of status. The team began adding the highest-signal requests to a board, linking planned items to a roadmap and sending a short release note to voters. It did not change the engineering capacity overnight, but it made the decisions understandable and reduced repeated status chasing.",
    pitfall: "Do not make the system so elaborate that nobody follows it. A complex scoring model, five review committees and a collection channel for every department can look rigorous while ensuring feedback arrives too late to matter. Keep the loop short enough to maintain, then add detail only where it changes a decision or protects an important customer promise.",
    next: "Write the four stages on one page and test them against the latest three customer requests. Can you find the original context, the decision, the status and the final update? If not, fix the missing hand-off first. A small repair to the loop usually beats another dashboard.",
    quote: "The test of a feedback system is not how much input it stores. It is whether a customer can follow a real request from their first observation to a clear, honest outcome.",
  },
  {
    slug: "feedback-prioritisation-guide", title: "Feedback prioritisation: use signal wisely", date: "2026-09-20", keyword: "feedback prioritisation", category: "Academy",
    description: "Prioritise customer feedback with a practical method that combines votes, context, strategy and delivery effort without pretending any score is automatic.",
    supportingKeywords: ["feature prioritisation", "customer feedback analysis", "feature voting", "product roadmap", "RICE prioritisation", "product strategy", "feedback triage"],
    longTailKeywords: ["how to prioritise customer feedback", "should votes decide product priorities", "how to score feature requests"],
    image: IMAGE.roadmap, imageAlt: "Feedback prioritisation board connecting customer demand to a product roadmap",
    hook: "Prioritising feedback is where a product team proves it is listening without promising to build everything. That balance is awkward because a vote count feels tidy and a customer story feels urgent. Good prioritisation makes both visible, then adds strategy, effort and timing before a team commits precious delivery capacity.",
    context: "Feedback prioritisation is the practice of deciding which customer problems deserve research, roadmap space or a response now. It is not a formula for choosing every feature. A request with twenty votes may be important, but the score does not reveal whether those voters are in a strategic segment, whether an existing workflow solves the problem, or whether a small fix would remove a much larger source of friction.",
    workflowTitle: "Separate demand from the decision", workflow: "Record votes and repeated reports as demand evidence. Next, add a short note on the customer problem, affected segment, business or product goal, confidence and likely delivery effort. Discuss these inputs in a regular planning session rather than only when someone senior remembers a request. A lightweight RICE or ICE score can make assumptions visible, but the important outcome is the conversation around those assumptions, not a false sense of mathematical certainty.",
    example: "A team saw two requests near the top of its board: SSO and a colour-picker. The colour-picker had more votes, but most came from free users asking for cosmetic control. SSO had fewer votes from larger teams blocked from adopting the product. The team prioritised discovery and delivery for SSO, explained the decision on the board and kept the colour-picker visible. The vote count was honoured as evidence, not obeyed as a command.",
    pitfall: "The biggest pitfall is letting a scoring sheet replace human judgment. Teams sometimes give made-up reach and impact values a veneer of precision, then claim the result is objective. Another is losing sight of the underlying problem. Customers may ask for a feature because they cannot complete a task; a different solution can sometimes solve it better and faster.",
    next: "Start with the top ten open requests, not the whole historical backlog. Add source, repeated-demand evidence and a sentence about the job each customer is trying to do. Use the next planning session to make three clear calls: investigate, plan or leave visible but uncommitted. Then publish the status changes so customers see that review led somewhere.",
    quote: "Votes tell you where to look. Context tells you what people are trying to achieve. Strategy tells you whether now is the right time. Prioritisation needs all three, even when the answer is uncomfortable.",
  },
  {
    slug: "changelog-communication-guide", title: "Changelog communication that customers read", date: "2026-09-21", keyword: "changelog communication", category: "Academy",
    description: "Write changelog communication that helps customers understand what changed, why it matters and where to find the feature without burying the point.",
    supportingKeywords: ["product changelog", "release communication", "release notes", "customer updates", "changelog tool", "product announcements", "feature launches"],
    longTailKeywords: ["how to communicate product updates", "what should a customer changelog include", "how to write release notes customers read"],
    image: IMAGE.release, imageAlt: "Changelog communication page explaining a customer product update",
    hook: "A changelog is often written at the end of a release, when the team is tired and eager to move on. That is precisely why many updates read like a commit summary: technically accurate, easy to publish and largely useless to a customer. Good changelog communication does a different job. It tells somebody what changed in their day-to-day work and what they can do next.",
    context: "Changelog communication is the customer-facing explanation of product changes. It does not need a grand announcement for every small fix. It does need a regular, findable home and language that connects an implementation to an outcome. The reader is asking: do I need to care, what does this change for me, and how do I use it? Answer those questions before describing the architecture.",
    workflowTitle: "Write from the customer’s before-and-after", workflow: "Start with the outcome in the title: ‘Export reports by month’ is clearer than ‘Reporting improvements’. In the first paragraph, say what was hard before and what is possible now. Add the exact screen or path if a customer needs to find it. If the work arose from a public request, link it and notify the voters. Then add a brief implementation detail only if it affects setup, availability or compatibility.",
    example: "A team released a new role for finance managers. Its first draft said ‘Added scoped permissions’. The final note said finance managers can now view invoices without editing billing settings, with a link to Settings → Team. That one change made the release useful to the administrator who needed to configure it and understandable to everyone else. The technical term still appeared lower down for people who needed it.",
    pitfall: "Do not turn the changelog into either a sales email or an engineering dump. Hyperbole makes routine releases feel untrustworthy; raw ticket language makes meaningful work invisible. The other common mistake is publishing without distribution. If customers who asked for a feature never hear about it, the update has not closed the loop, no matter how polished the page looks.",
    next: "Create a release-note checklist: outcome-led title, who benefits, where to find it, any action required, and a link back to the request if relevant. Keep the note short enough to scan. Then decide the audience: all customers, a segment, administrators or the exact people who voted. Matching the message to the reader is more effective than sending everything to everyone.",
    quote: "A changelog earns attention when it respects the reader’s time. Tell them what changed in their world, show them where it lives, and leave the internal story for the people who need it.",
  },
  {
    slug: "release-notes-for-customers-guide", title: "Release notes for customers: a practical guide", date: "2026-09-21", keyword: "release notes for customers", category: "Academy",
    description: "Create release notes for customers that explain what changed in plain language, support adoption and make the next step easy to find after launch.",
    supportingKeywords: ["customer release notes", "product updates", "changelog", "release communication", "feature announcement", "software release notes", "customer education"],
    longTailKeywords: ["how to write release notes for customers", "what makes customer release notes useful", "how long should release notes be"],
    image: IMAGE.release, imageAlt: "Release notes for customers showing a clear product feature update",
    hook: "Customers do not read release notes because a team shipped something. They read them because they want to know whether a change affects their work. The best notes reward that attention quickly: a clear headline, a concrete outcome and one obvious route to the feature. The rest is supporting detail, not the main event.",
    context: "Release notes for customers are a form of product education. They sit between a full help article and a headline announcement. A good note can introduce a small improvement, point to a new workflow or reassure someone that a reported problem is fixed. It should be written for the person using or administering the product, not for the team that completed the technical work.",
    workflowTitle: "Use a repeatable, reader-first draft", workflow: "Draft a one-sentence ‘before and after’ first. Then write a title using the outcome, followed by where to find the change and any action needed. Add a screenshot or short example only when it removes ambiguity. For a larger release, link to a help article with setup detail. This structure works because it lets customers stop reading when they have the answer they came for.",
    example: "A collaboration product fixed an issue where invited users could not see a shared workspace until they refreshed. Rather than publish ‘Improved invitation consistency’, it wrote: ‘New teammates now see shared workspaces as soon as they accept an invite.’ Existing customers immediately understood whether the note affected them. Support could link the note when closing related tickets, and the team avoided another round of confused questions.",
    pitfall: "Avoid hiding a breaking change in a cheerful title. If someone needs to update a setting, change an integration or expect a different behaviour, say so plainly and put the action near the top. On the other hand, do not inflate every maintenance improvement into a major launch. Over-announcing trains customers to ignore the notes that genuinely matter.",
    next: "Ask a colleague outside the delivery team to read the note and say what they think changed and what they should do. If they cannot answer in ten seconds, tighten the opening. Build a light release-note rhythm so customers know where updates appear, then use email or in-product notices selectively for changes with a clear audience.",
    quote: "Useful release notes are not a victory lap for the team. They are a small act of translation: here is what is different, here is why it matters, and here is where to go.",
  },
  {
    slug: "saas-feedback-management-guide", title: "SaaS feedback management: a team workflow", date: "2026-09-22", keyword: "SaaS feedback management", category: "Academy",
    description: "Manage SaaS customer feedback with a lightweight team workflow for capture, triage, prioritisation, roadmap updates and clear customer follow-up.",
    supportingKeywords: ["customer feedback management", "SaaS customer feedback", "feedback management software", "feedback triage", "feature requests", "product discovery", "customer insights"],
    longTailKeywords: ["how to manage feedback in a SaaS company", "how do SaaS teams organise feature requests", "what is a feedback management workflow"],
    image: IMAGE.analysis, imageAlt: "SaaS feedback management workflow for a product team",
    hook: "SaaS feedback management can feel unglamorous. It is a lot of small notes, repeated requests and conversations that happen in different tools. Yet the teams that manage those hand-offs well make better use of the customer access they already have. They do not need a giant research department. They need a shared way to capture, review and return an answer.",
    context: "SaaS feedback management is the ongoing practice of turning comments from customers into an organised product input. Its scope is broader than a feature request board: it includes support contacts, sales notes, onboarding friction, interviews and usage signals. The aim is not to funnel every message into product. It is to recognise the subset that should influence product decisions, preserve its context and keep the customer relationship intact.",
    workflowTitle: "Make cross-team capture painless", workflow: "Give support, sales and success teams a quick way to add a product observation with the original wording and account context. Avoid asking them to translate it into a detailed specification. Product can do the synthesis later. In return, show those teams what happened to requests they logged. That feedback loop keeps the input flowing and prevents the familiar feeling that product feedback disappears into a mysterious void.",
    example: "A subscription SaaS team kept discovering churn reasons in renewal calls after the customer had already left. It added a simple product-feedback field to the success team’s account notes and reviewed patterns monthly. The team noticed that several customers struggled to show ROI to their managers. That insight led to research on reporting and a roadmap theme, not an immediate feature promise. The important change was seeing the pattern early enough to investigate.",
    pitfall: "Do not reward teams only for volume. A hundred context-free ‘customer wants X’ notes can be less valuable than three well-described observations tied to a job, segment and moment of friction. Also avoid centralising feedback in a way that locks out the people who hear it first. The system should reduce work for customer-facing teams, not make every conversation feel like admin.",
    next: "Choose one shared capture format, one weekly product triage and one monthly pattern review. Start with a narrow question, such as onboarding friction or reporting requests, so the team learns the habit without boiling the ocean. As patterns become clearer, make the public pieces of the loop visible through a board, roadmap and changelog.",
    quote: "Good SaaS feedback management is not a hand-off from customer teams to product. It is a shared memory that lets every team see what customers are trying to achieve and what the business chose to do about it.",
  },
  {
    slug: "product-idea-management-guide", title: "Product idea management: from suggestion to shipped", date: "2026-09-22", keyword: "product idea management", category: "Academy",
    description: "Manage product ideas without building an endless backlog: collect the right context, group similar requests, decide transparently and close the loop.",
    supportingKeywords: ["idea management", "product ideas", "feature requests", "product discovery", "feedback board", "feature prioritisation", "product roadmap"],
    longTailKeywords: ["how to manage product ideas", "how to avoid an endless feature backlog", "how do product teams evaluate customer ideas"],
    image: IMAGE.board, imageAlt: "Product idea management board for organising customer feature suggestions",
    hook: "Product ideas arrive in all shapes: a customer request, a founder’s hunch, a support workaround, a competitor comparison or a note from somebody who woke up with a ‘brilliant’ thought. The useful challenge is not collecting them all. It is keeping enough context to evaluate them later without allowing every idea to masquerade as a commitment.",
    context: "Product idea management is a lightweight system for capturing, shaping and deciding on possible product work. It includes customer ideas but should also leave room for technical, strategic and team-led opportunities. A healthy idea record says who raised it, what problem it may solve, any supporting evidence and its current state. It should not imply a delivery date simply because it exists.",
    workflowTitle: "Keep ideas separate from commitments", workflow: "Use clear stages such as new, researching, planned and shipped, but do not move an idea to planned until there is a real decision. Group similar ideas around the customer problem rather than forcing every contributor to use the same proposed solution. During a regular review, choose whether to archive, research, connect to an existing request or progress it. This protects the roadmap from becoming a museum of every thought anyone has had.",
    example: "A team saw requests for ‘Slack alerts’, ‘daily summaries’ and ‘email digests’. Instead of adding three separate ideas to a roadmap, it grouped them under a broader job: keeping account owners informed without checking the dashboard. A few conversations revealed different timing and permission needs. The eventual work was a notification centre with tailored delivery options, not the first literal request that arrived.",
    pitfall: "The unhelpful habit is keeping every idea forever because deleting it feels like rejecting the person who suggested it. An archive is kinder than false hope when an idea no longer fits. Another trap is encouraging solution-first pitches without asking what is difficult today. Ideas are valuable starting points; they are not always the right finished shape.",
    next: "Create one idea record format and use it for the next ten suggestions from any source. At review, write a one-line decision beside each: explore, connect, defer or archive. Then share the planned work through the roadmap rather than making the raw idea list public. Customers benefit from honest progress, not a glimpse at every unfinished internal debate.",
    quote: "Idea management gets easier when a team treats every suggestion as a clue, not an instruction. The clue may lead to a feature, a research call, a clearer help article or a decision to do nothing for now.",
  },
  {
    slug: "feedback-collection-methods-2026", title: "Feedback collection methods in 2026", date: "2026-09-23", keyword: "feedback collection methods", category: "News",
    description: "A practical look at feedback collection methods in 2026, from embedded prompts to interviews, and how product teams can combine them without noise.",
    supportingKeywords: ["customer feedback methods", "user research", "feedback widget", "customer interviews", "feedback surveys", "product feedback", "customer voice"],
    longTailKeywords: ["best ways to collect product feedback", "how to combine feedback collection methods", "what feedback collection method should SaaS use"],
    image: IMAGE.analysis, imageAlt: "Feedback collection methods combining user research, widgets and product analytics",
    hook: "The interesting shift in feedback collection is not a shiny new channel. It is the growing recognition that no single channel tells the whole story. A button inside the product can catch a moment of friction; an interview can reveal why it matters; a public board can show whether other people share it. Teams that combine those strengths make fewer confident guesses from thin evidence.",
    context: "Feedback collection methods range from interviews and usability sessions to in-app prompts, support conversations, public boards and surveys. Each has a different bias. Interviews create depth but involve a small number of people. Widgets are timely but short. Surveys are comparable but constrained by their questions. The practical question is not which method wins. It is how each method feeds a shared picture without making customers repeat themselves.",
    workflowTitle: "Use the right method for the uncertainty", workflow: "When you need to understand why a person behaves a certain way, speak with them or observe the task. When you need to learn whether a problem appears across a wider group, use a board, prompt or targeted survey. When you need to validate a proposed solution, put it in front of representative users. Label the source of each insight so a vote count is not accidentally treated as interview evidence, or a strong interview quote as a market-size estimate.",
    example: "A SaaS team noticed that many users abandoned a new setup step. A feedback widget collected comments saying the screen was confusing, but the wording varied. Short interviews showed that the real issue was not the interface alone: customers did not know which teammate owned the required permission. The team changed the setup guidance and added an invite prompt. The widget identified the place to investigate; research found the better fix.",
    pitfall: "A common mistake is opening every channel at once and assuming more input equals better insight. It often produces duplicate stories with no owner. Another is using a survey because it is easy to send, even when you need to watch someone complete a task. Match the method to the decision you need to make, then give the resulting evidence a clear route into planning.",
    next: "List the customer questions your team is trying to answer this quarter. For each one, choose one primary method and one supporting source of signal. Keep a shared evidence note beside the related feedback requests. This reduces the temptation to treat whichever channel is loudest this week as the full customer voice.",
    quote: "The most useful feedback programme is not the one with the most channels. It is the one where each channel answers a different question and the team knows how to connect the answers.",
  },
  {
    slug: "customer-suggestion-box-guide", title: "Customer suggestion box: make it useful", date: "2026-09-23", keyword: "customer suggestion box", category: "Academy",
    description: "Turn a customer suggestion box into a trusted product input with clear prompts, duplicate handling, visible status and thoughtful responses.",
    supportingKeywords: ["customer suggestions", "suggestion box", "feature requests", "customer feedback", "feedback board", "product ideas", "feature voting"],
    longTailKeywords: ["how to create a customer suggestion box", "how to respond to customer suggestions", "should customer suggestions be public"],
    image: IMAGE.board, imageAlt: "Customer suggestion box collecting product ideas and feature requests",
    hook: "The old-fashioned suggestion box has a reputation for being a polite place to put ideas that nobody intends to read. A digital customer suggestion box can be much better, but only if it offers a visible path after submission. People do not expect every suggestion to ship. They do expect to know whether it was seen, whether others agree and whether the team has made a decision.",
    context: "A customer suggestion box is a simple entry point for product ideas and improvements. In a product setting, it works best as a searchable board rather than a private form, because people can support an existing suggestion instead of writing the same thing again. A private option still has a place for sensitive accounts or account-specific needs. The key is to make the choice clear, not to funnel everything into one opaque channel.",
    workflowTitle: "Turn the box into a conversation, not a bin", workflow: "Use a clear invitation that explains what kinds of suggestions belong there. Show existing ideas before a new one is created and invite people to vote or add a useful use case. Keep a short status vocabulary, and when a suggestion is not a fit, respond with a reason where appropriate. The response does not need to be long. It needs to demonstrate that somebody considered the idea rather than letting it vanish.",
    example: "A customer success team repeatedly heard requests for a ‘simpler dashboard’. On a public suggestion box, those requests divided into two real themes: fewer setup metrics for new users and better filtering for power users. The team could acknowledge both, ask follow-up questions and avoid treating ‘simpler’ as a single feature. Customers could see their contribution alongside related experiences, which made the conversation more constructive than one-off email replies.",
    pitfall: "The mistake is announcing an open suggestion box without allocating someone to tend it. A list of unanswered requests makes people less likely to contribute next time. Avoid making it a complaint wall, too. Clear scope, helpful duplicate handling and a visible link to roadmap updates keep the tone oriented towards improving a shared product rather than venting.",
    next: "Start with a public board for broad product suggestions and a private contact route for account-specific issues. Add a link where customers already look for help, then answer or status new items on a predictable cadence. The habit of acknowledgement is what turns a suggestion box into a source of trust.",
    quote: "A suggestion box becomes credible when a customer can see that an idea did not simply enter a queue. It joined a conversation, gathered context and reached an honest outcome.",
  },
];

// Two exploratory drafts overlap existing topics (customer-feedback-widget and
// product-feedback-system), so only the 15 non-competing guides ship.
const PUBLISHED_GUIDE_SLUGS = new Set([
  "feedback-widget-guide",
  "user-feedback-widget-guide",
  "free-feedback-widget-guide",
  "no-login-feedback-guide",
  "product-feedback-board-guide",
  "customer-feedback-portal-guide",
  "feature-voting-software-guide",
  "feedback-inbox-guide",
  "feedback-prioritisation-guide",
  "changelog-communication-guide",
  "release-notes-for-customers-guide",
  "saas-feedback-management-guide",
  "product-idea-management-guide",
  "feedback-collection-methods-2026",
  "customer-suggestion-box-guide",
]);

export const BLOG_FEEDBACK_OPERATIONS: BlogPost[] = GUIDES.filter(({ slug }) => PUBLISHED_GUIDE_SLUGS.has(slug)).map(guide);
