import type { BlogPost } from "./blog-types";

export const BLOG_REVIEWS: BlogPost[] = [
  {
    slug: "productboard-alternatives",
    title: "The best Productboard alternatives in 2026",
    description:
      "Productboard costs more and does more than most teams need. Compare six alternatives with simpler setup, clearer pricing and a real public roadmap.",
    date: "2026-06-21",
    keyword: "productboard alternative",
    category: "Reviews",
    author: "Tom Whitfield, Feedlark co-founder",
    authorBio: "Tom co-founded Feedlark after years of watching product teams pay enterprise prices for features they rarely used.",
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Monitor displaying a digital product interface, representing software tools and product management",
    readMins: 6,
    blocks: [
      { p: "Productboard built its name as the platform for teams that want deep discovery tools, prioritisation frameworks and roadmap strategy in one place. That depth comes with a cost, both in monthly billing and in the weeks it takes new hires to feel comfortable inside it. If your team mainly needs a [public roadmap](/blog/how-to-build-public-roadmap), a feedback board people actually use and a changelog that keeps customers in the loop, Productboard is often more platform than you need. This guide compares six alternatives, what each one costs, and where each genuinely beats Productboard on the things most teams use every day. Most complaints about Productboard are not really about quality. They are about paying for [product discovery](https://www.nngroup.com/articles/discovery-study-guide/) tools that sit unused while a simple public roadmap takes longer to set up than it should." },
      { h2: "Why teams leave Productboard", ul: [
        "Onboarding takes weeks rather than minutes, and often needs a dedicated implementation call",
        "The learning curve is steep even for product managers who have used similar tools before",
        "Pricing scales with the number of 'makers', or editors, which adds up fast for small teams",
        "The tool is built around internal strategy work, not customer-facing transparency",
        "The public portal feels like an afterthought next to dedicated feedback board products",
        "Support and integrations are strong, but you pay enterprise rates for all of it",
      ] },
      { h2: "Feedlark", p: "Feedlark is the most direct swap for teams that want a feedback board, a public roadmap and a changelog without the overhead of a full strategy suite. The free tier includes all three with no cap on end-users, so a launch day spike in votes never triggers a bill. The Pro plan, at [$19 per admin seat](/pricing), adds custom branding, private boards and team roles. Setup takes under ten minutes because there is no implementation project to run. Ship a feature and the changelog entry publishes itself, with voters notified automatically, so the 'you asked, we shipped' loop closes without anyone chasing it by hand. Teams can [try it free](/signup) before deciding whether to add paid seats." },
      { h2: "Featurebase", p: "Featurebase covers more ground than Feedlark out of the box, including an in-app widget, a help centre module and audience segmentation. It is free for unlimited end-users, with paid seats starting from $29 a month. That extra depth is genuinely useful for teams that want a combined support and feedback hub, but it also means a longer setup and more menus to learn before the board goes live. Worth a look if the help centre integration matters to you specifically." },
      { h2: "Canny", p: "Canny is the most recognised name in this space, with wide integrations and a polished interface. The catch is pricing: Canny bills per tracked user, and our [breakdown of Canny's 2026 pricing](/blog/canny-pricing-explained) shows how quickly that adds up once a board takes off. The free plan caps at 25 tracked users, which suits early testing but not a product with real traffic. If your community is small and likely to stay that way, this matters less. If it is growing, check the maths before you commit." },
      { h2: "Nolt", p: "Nolt is simple and well designed, charging a flat rate per board rather than per user. Our [look at Nolt alternatives](/blog/nolt-alternatives) covers this in more detail, but the short version is that Nolt has no AI deduplication, limited integrations and no changelog tied to the roadmap. For a very small team that wants one clean board and nothing else, it still does the job well." },
      { h2: "Frill", p: "Frill sits in similar territory to Nolt: a clean interface, quick setup and a focus on the core feedback board use case. Pricing starts around $25 a month and scales to tiers with white labelling. It is a solid choice for getting something live fast, though teams that grow past the basics tend to find the same integration and automation gaps that limit Nolt." },
      { h2: "Aha!", p: "Aha! is arguably more complex than Productboard, not less. It bundles goals, initiatives, OKRs and capacity planning into one strategy platform, which large enterprise product organisations genuinely use. For a SaaS team of under twenty people that wants a public roadmap and a working feedback board, it adds more process than most teams want to run, and it does not solve the transparency gap that pushes people to look at alternatives in the first place. Teams researching [why product roadmaps fail](/blog/why-product-roadmaps-fail) usually find the cause is process, not a missing feature, so bolting on more process rarely fixes it." },
      { h2: "How to choose", p: "If cost or complexity is the main reason you are leaving Productboard, Feedlark or Featurebase replace what you actually use day to day. If the real complaint is a weak public portal, any tool on this list does that better than Productboard's default. If you need enterprise strategy features at a lower price, Aha! is worth comparing, though it will not simplify your workflow. Customers increasingly expect this kind of openness anyway: [Zendesk's 2026 CX Trends report](https://cxtrends.zendesk.com/) found that 63% of people say demand for transparency from companies has risen, and a public roadmap is one of the simplest ways to answer that." },
      { h2: "What migration actually looks like", p: "Moving off Productboard is usually simpler than teams expect, because the hard part was never technical. Export your existing feature requests and roadmap items, most tools accept a simple import, and recreate your board's categories and statuses in the new tool. The bigger task is communication: tell existing users where the new public roadmap lives, and keep a note or a banner pointing from the old portal for a few weeks so nobody lands on a dead page. Most teams complete the whole switch inside a single sprint, with the tool setup itself taking under a day and the rest of the time going into making sure old links and bookmarks still lead somewhere useful." },
      { h2: "Common mistakes teams make when switching", ul: [
        "Switching tools without telling existing voters where their requests went",
        "Copying every historic idea across, including ones rejected years ago that just add clutter",
        "Choosing a tool based on the sales demo rather than a real trial with your own data",
        "Underestimating how much a public roadmap changes internal habits, since someone still needs to keep it updated",
        "Picking the cheapest option without checking whether the changelog and roadmap are actually connected",
      ] },
      { h2: "A quick note on data ownership", p: "Whichever alternative you pick, check how easy it is to get your data back out again. A tool that lets you export votes, comments and statuses in an open format protects you from ever feeling stuck, in the same way Productboard's own export tools protect its existing customers today. This matters more than it sounds. Teams that treat their feedback data as portable tend to make calmer decisions about pricing changes down the line, because switching never feels like starting from zero. It is a small detail worth checking before you sign up anywhere, alternative or not." },
      { table: {
        caption: "Productboard alternatives at a glance",
        head: ["Tool", "Starting price", "Free tier", "Best for"],
        rows: [
          ["Feedlark", "$19/admin seat", "Unlimited users, roadmap and changelog", "Teams wanting simplicity and predictable cost"],
          ["Featurebase", "$29/seat", "Free for unlimited end-users", "Combined support and feedback hub"],
          ["Canny", "From $79/mo", "25 tracked users", "Established teams needing wide integrations"],
          ["Nolt", "~$29/mo per board", "Trial only", "Very small teams wanting one simple board"],
          ["Frill", "From $25/mo", "Trial only", "Fast setup with light white-labelling"],
          ["Aha!", "Enterprise pricing", "None", "Large PM teams needing strategy tooling"],
        ],
      } },
    ],
    takeaways: [
      "Productboard's per-maker pricing and long onboarding suit large PM teams, not small SaaS products.",
      "Feedlark and Featurebase both offer genuinely free tiers built around feedback boards and public roadmaps.",
      "Canny and Nolt trade off differently: tracked-user billing against flat per-board pricing.",
      "Pick based on what your team uses every day, not the length of the feature list.",
    ],
    faqs: [
      { q: "Is there a free alternative to Productboard?", a: "Yes. Feedlark's free plan covers a feedback board, public roadmap and changelog with no cap on end-users, and Featurebase also offers a free tier for unlimited end-users. Both charge only when you add paid admin seats or extra features." },
      { q: "What is the main difference between Productboard and Canny?", a: "Productboard is a full product strategy platform with discovery and prioritisation tools, while Canny is a focused feedback board with wide integrations. Canny is usually cheaper to start but bills per tracked user, so costs can rise with an engaged community." },
      { q: "Do small teams really need a full product management platform?", a: "Usually not. Most small SaaS teams only use three things day to day: a feedback board, a public roadmap and a changelog. A focused tool covers that without the setup time or per-maker pricing of a full strategy suite." },
      { q: "How long does it take to switch away from Productboard?", a: "Migrating votes and posts typically takes an afternoon for a small board. Tools like Feedlark are designed to be live within ten minutes, so most of the time investment is deciding which alternative fits, not the technical switch itself." },
    ],
  },
  {
    slug: "nolt-alternatives",
    title: "The best Nolt alternatives in 2026",
    description:
      "Nolt is clean and simple, but its flat per-board pricing and missing changelog push growing teams to look around. Compare five solid alternatives.",
    date: "2026-06-20",
    keyword: "nolt alternative",
    category: "Reviews",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and spends a surprising amount of her week reading other companies' pricing pages.",
    image: "https://images.unsplash.com/photo-1429743305873-d4065c15f93e?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max",
    imageAlt: "A forking path splitting into two directions through a forest, symbolising choice between alternatives",
    readMins: 5,
    blocks: [
      { p: "Nolt does one thing well: a clean, simple feedback board with almost no setup friction. As products grow, though, teams start needing AI deduplication, a roadmap tied to a changelog and integrations with tools like Jira or Linear, and Nolt's simplicity turns into a ceiling. This guide compares five alternatives that fill those gaps, what each costs, and where Nolt still wins for a very early product. If you are still deciding whether a [feedback board](/blog/feedback-widget-for-website) is the right first step at all, it usually is: it gives customers one clear place to ask for what they want instead of scattered emails and support tickets." },
      { h2: "What Nolt does well", p: "Nolt's design holds up well against competitors twice its price. Voting is straightforward, boards look professional without any configuration, and the flat per-board pricing, around $29 a month, is predictable regardless of how many people vote. For a very early product that just needs somewhere for users to post ideas, Nolt gets you live the same afternoon." },
      { h2: "Where Nolt falls short", ul: [
        "No AI duplicate detection, so popular boards fill up with several versions of the same request",
        "Limited native integrations with tools like Jira, Linear or Intercom",
        "No changelog, so you cannot publish what shipped from inside the same tool",
        "No roadmap view connected directly to feature requests and votes",
        "Per-board pricing adds up quickly once you run more than one product",
        "No automatic notification to voters when their request ships",
      ] },
      { h2: "Feedlark", p: "Feedlark is the most direct upgrade path for teams that have outgrown Nolt's simplicity. It adds AI deduplication, a roadmap connected to feature requests, and a changelog that notifies voters automatically when something ships, which matters more than it sounds: keeping that loop visible protects revenue, since subscription businesses see average monthly churn around 3.27% according to [Recurly's benchmark research](https://recurly.com/research/churn-rate-benchmarks/), and a visible feedback loop is one lever you can actually pull to bring that down. All of this sits on a free tier with no cap on users. The [Pro plan](/pricing) at $19 a month per seat works out cheaper than Nolt's per-board fee once you are running more than one product area, and setup still takes under ten minutes." },
      { h2: "Featurebase", p: "Featurebase goes further than Feedlark on feature depth, particularly around audience segmentation and a built-in help centre. It is free for unlimited end-users, with seats billed from $29 a month. The tradeoff is a steeper learning curve. If Nolt's simplicity is what drew you in originally, Featurebase can feel like a bigger jump than expected, though the depth pays off for teams with large, active communities." },
      { h2: "Frill", p: "Frill is the closest in feel to Nolt: clean design, fast setup and a tight focus on the core feedback board. It starts around $25 a month and scales to tiers with white labelling. It sits between Nolt's simplicity and the fuller platforms, though it shares Nolt's main limitation: no built-in roadmap automation or changelog." },
      { h2: "Canny", p: "Canny is the alternative most often compared with Nolt, and our [Canny pricing breakdown](/blog/canny-pricing-explained) is worth reading before you switch. It has more integrations and stronger AI features, but its tracked-user billing model makes it noticeably more expensive than Nolt once a community is engaged. The free plan caps at 25 tracked users, which a busy board can pass within a week." },
      { h2: "Upvoty", p: "Upvoty is one of the more affordable options, starting around $15 a month. It covers the basics of a feedback board plus a simple roadmap view, making it a reasonable step up from Nolt for budget-conscious teams that want a roadmap without the full suite of integrations. The interface is less polished than Nolt or Feedlark, but it works and is actively maintained." },
      { h2: "Migrating your board from Nolt", p: "Switching away from Nolt is a lighter job than most teams expect. Export your existing posts and votes, most alternatives accept a simple import or a quick manual copy for a small board, and rebuild your status categories in the new tool. The part that takes longer is telling existing voters where the board has moved to, since a feedback board is only useful if the people who already contributed can find it again. Plan for a short overlap period where both boards are visible, with a clear note on the old one pointing to the new address." },
      { h2: "What to check before you switch", ul: [
        "Can you export existing posts and votes, or will you start from a blank board?",
        "Does the new tool notify existing voters automatically once you migrate their requests?",
        "Is the public roadmap view free, or does it sit behind a paid tier?",
        "Will your current embed code or widget need replacing across your site?",
      ] },
      { h2: "Why automation matters more as you grow", p: "A small board can run entirely by hand: a founder reads every post, merges duplicates manually and emails people when something ships. That approach works for the first hundred votes and falls apart well before the thousandth. AI deduplication, automatic changelog publishing and voter notifications are not luxuries for a growing board, they are what stops your best engineer from spending Friday afternoons manually replying to people instead of shipping. This is the real gap Nolt leaves for teams that succeed at getting people to actually use their board." },
      { h2: "A realistic timeline for switching", p: "Most teams moving off Nolt complete the whole process inside a week. The first day covers exporting existing posts and setting up the new tool's categories and statuses. The next few days go into a soft launch, pointing a small group of existing voters to the new board and checking nothing important got lost in the move. By the end of the week, the old board can carry a simple note directing everyone to the new one, and normal posting resumes on the replacement." },
      { h2: "What a good replacement feels like on day one", p: "The best sign that a switch has gone well is that nobody notices much has changed, except that things they ask for now show up on a changelog a few weeks later. Existing voters should be able to find their old requests, add new ones without confusion, and see the same clear status labels they were used to. A migration that requires a training session for your own customers has gone wrong somewhere, and it usually means the new tool was chosen for its feature list rather than for how closely it matched the workflow people already understood." },
      { h2: "Which one to pick", p: "Want Nolt's simplicity plus a changelog and automatic voter notifications? Feedlark is the closest match, and it is cheaper at scale while free to start. Want Nolt's exact feel with a few more settings? Frill is nearest. Need enterprise integrations and are happy to pay for them? Canny is the most mature choice. On a tight budget? Upvoty covers the essentials for less. Whichever you pick, closing the loop with customers matters more than the tool: teams that reliably tell users [what shipped from their feedback](/blog/what-is-a-product-feedback-loop) tend to see stronger loyalty over time, and that lines up with the wider research on retention. Bain's oft-cited analysis found that [lifting customer retention by five points can raise profits by 25 to 95%](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers)." },
      { table: {
        caption: "Nolt alternatives compared",
        head: ["Tool", "Pricing model", "Changelog included", "Roadmap included"],
        rows: [
          ["Feedlark", "Free, then $19/seat", "Yes, with automatic voter notifications", "Yes, connected to requests"],
          ["Featurebase", "Free, then $29/seat", "Yes", "Yes"],
          ["Frill", "From $25/mo", "Limited", "Basic"],
          ["Canny", "From $79/mo, per tracked user", "Yes", "Yes"],
          ["Upvoty", "From $15/mo", "No", "Basic"],
          ["Nolt", "~$29/mo per board", "No", "No"],
        ],
      } },
    ],
    takeaways: [
      "Nolt's flat per-board pricing is predictable, but it has no changelog and no AI deduplication.",
      "Feedlark and Featurebase both add a connected roadmap and changelog on a free-to-start plan.",
      "Canny offers more integrations but bills per tracked user, which can outpace Nolt's flat fee.",
      "Match the alternative to what's actually missing for you: automation, changelog, or budget.",
    ],
    faqs: [
      { q: "What is the biggest limitation of Nolt?", a: "Nolt has no changelog and no roadmap view connected to feature requests, so teams cannot publish what shipped or notify voters automatically. It also lacks AI deduplication, which lets duplicate requests build up on busy boards." },
      { q: "Is Feedlark cheaper than Nolt?", a: "For a single small board, the costs are similar. Once you manage more than one product area or want a changelog and roadmap included, Feedlark's free tier and $19 per seat pricing usually works out cheaper than Nolt's flat per-board fee." },
      { q: "Does Canny have a free plan like Nolt?", a: "Canny's free plan caps at 25 tracked users, which many boards exceed quickly. Nolt has no permanent free plan either, just a trial, so most teams end up comparing paid tiers on both." },
      { q: "Which Nolt alternative is easiest to set up?", a: "Feedlark and Frill are both designed to go live within minutes with minimal configuration, similar to Nolt itself. Featurebase and Canny take longer to set up because they offer more configuration options." },
    ],
  },
  {
    slug: "best-free-roadmap-tools",
    title: "Best free roadmap tools in 2026",
    description:
      "Genuinely free roadmap tools do exist, though most 'free' plans are freemium trials in disguise. Here are the best truly free options for 2026.",
    date: "2026-06-20",
    keyword: "free roadmap tool",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1765917393220-78ed33e7e07b?fm=jpg&q=60&w=1080",
    imageAlt: "Notebook, ruler and keyboard arranged on a clean white surface, a modern planning workspace",
    readMins: 6,
    blocks: [
      { p: "Most 'free' roadmap tools are free for about a week before you hit a limit: five items, one user, or a private-only view, and then the paywall appears. This list covers the tools that stay useful without paying, and exactly what you get on each free tier. If you are still weighing whether you need a dedicated tool at all versus a spreadsheet, our guide to [product roadmap software](/blog/product-roadmap-software-guide) covers that decision in more depth." },
      { h2: "What free should actually mean", ul: [
        "No credit card required to get started",
        "Unlimited end-users can view and interact with the roadmap",
        "A public roadmap view accessible without a login",
        "No artificial item caps that appear after a trial period ends",
        "Core functionality intact, not just a fourteen-day trial of the paid plan",
      ] },
      { h2: "Feedlark", p: "Feedlark's free tier includes the feedback board, public roadmap and changelog with no user caps and no item limits. Unlimited people can post, vote and view the roadmap without creating an account. The free plan does not expire and does not ask for a credit card at [signup](/signup). The [Pro upgrade](/pricing), at $19 per seat, adds custom branding, private boards and team collaboration, but the core roadmap functionality stays free permanently, not just during a trial window." },
      { h2: "Fider (open source)", p: "Fider is an open-source feedback board and roadmap tool that you host yourself. It is free if you are happy to run your own server. The feature set covers the essentials: voting, statuses and a public roadmap. The tradeoff is infrastructure work: you need a server, a database and someone comfortable with basic DevOps. For teams already set up to self-host, it is the most cost-effective option at scale. For everyone else, it is more effort than it saves." },
      { h2: "Trello", p: "Trello was not built as a roadmap tool, but plenty of teams use it as one, especially early-stage products that already rely on it for project management. The free tier is generous: unlimited boards, unlimited users and no expiry. The catch is that Trello has no voting, no user-facing status updates and no changelog. You end up building a roadmap by hand, which works at a very small scale but breaks down as more people want a say." },
      { h2: "Notion", p: "Notion's free tier is broad enough to build a basic roadmap as a database view, and many teams run a Kanban board with status properties as a lightweight public roadmap. The catch is the same as Trello: no voting, no voter notifications, no changelog, and shared pages are read-only with no interaction. It is a documentation tool pressed into service as a roadmap, and that works right up until you want people to actually engage with it." },
      { h2: "Featurebase", p: "Featurebase's free tier is more limited than Feedlark's, holding some features back for paid tiers, but it still covers the basics: a feedback board and a simple roadmap. The upgrade path runs from $29 a seat. Worth a look if you want more depth later and are prepared to pay for it once you outgrow the free plan." },
      { h2: "What to check before committing", ul: [
        "Does the free plan cap tracked users or end-users?",
        "Is the public roadmap view free, or is it locked behind a paid tier?",
        "Can you embed the feedback widget without upgrading first?",
        "Does publishing a changelog require a paid plan?",
        "Can you export your data while still on the free tier?",
        "What happens to your existing data if you decide not to upgrade?",
      ] },
      { h2: "Why a public roadmap matters more than the tool", p: "The tool you pick matters less than whether customers can actually see it. Zendesk's 2026 CX Trends research found that 63% of customers say demand for transparency from the companies they buy from has risen, and a [public roadmap](/blog/how-to-build-public-roadmap) is one of the most direct ways to answer that: [Zendesk's CX Trends report](https://cxtrends.zendesk.com/) is worth reading if you want the full picture. A free tool that people can actually see beats an expensive one that sits behind a login only your team ever opens." },
      { h2: "How to test a free plan before you commit to it", p: "Do not just read the pricing page. Create a real account, add a handful of test items, invite a colleague to vote, and try viewing the public roadmap while logged out in a private browser window. This takes fifteen minutes and reveals more than any comparison article can, including whether the free plan is actually free or whether a paywall appears the moment you try to make the roadmap public. It also shows you how the tool feels day to day, which matters more once your team is relying on it every week." },
      { h2: "What happens when you outgrow the free tier", ul: [
        "Check whether upgrading is a smooth in-place change, or a full account migration",
        "Confirm existing votes, comments and statuses carry over automatically to the paid plan",
        "Ask whether the public roadmap URL stays the same after upgrading",
        "Look for a clear price per seat rather than a custom quote you have to request",
      ] },
      { h2: "A realistic scenario", p: "A five-person SaaS team starts on Feedlark's free plan to collect feedback during a private beta. Once they launch publicly, a mention on a community forum sends a few hundred people to the roadmap in a single week. Because the free plan has no user cap, nothing breaks and no invoice arrives. Six months later, the team adds a Pro seat each so they can apply their own branding to the public board. That upgrade is optional and driven by a feature they want, not a limit they hit, which is exactly how a genuinely free plan should behave." },
      { h2: "Why free tools still need a maintenance habit", p: "Even a tool with no bill still needs someone to keep it tidy. Old, completed items should move to a 'shipped' status rather than sitting forgotten in a backlog column, and duplicate posts benefit from an occasional manual merge even on tools with AI deduplication built in. Treat the free plan as a genuine product surface, not a set-and-forget widget, and it will keep earning its keep long after the initial setup." },
      { h2: "One more thing worth checking: response time", p: "A free roadmap tool is only as useful as the habit of actually replying to it. Set a simple internal rule, someone reviews new posts weekly and updates statuses, so the board never goes quiet for months at a time. Customers notice a stale roadmap far faster than they notice a missing feature, and a tool costs nothing if nobody keeps it current." },
      { h2: "Our recommendation", p: "For most teams, Feedlark is the strongest genuinely free option: it covers the feedback board, roadmap and changelog with no user caps, no time limit and no credit card required. If you are comfortable self-hosting, Fider gives you the same functionality with full control over your data. If you have simple needs and an existing Trello habit, its free tier gets you started, though expect to outgrow it once customers start asking why nobody replies to their votes. Keeping that reply loop tight also protects revenue: Recurly's benchmark research puts [average subscription churn at 3.27% a month](https://recurly.com/research/churn-rate-benchmarks/), and a visible roadmap is one of the cheapest ways to chip away at that number." },
      { table: {
        caption: "Free roadmap tool comparison",
        head: ["Tool", "User cap on free plan", "Changelog on free plan", "Self-hosted"],
        rows: [
          ["Feedlark", "None", "Yes", "No"],
          ["Fider", "None (self-hosted)", "Basic", "Yes"],
          ["Trello", "None", "No", "No"],
          ["Notion", "None", "No", "No"],
          ["Featurebase", "Limited", "No", "No"],
        ],
      } },
    ],
    takeaways: [
      "Genuinely free roadmap tools have no user cap and no time-limited trial disguised as a free plan.",
      "Feedlark and Fider both offer unlimited free use, one hosted and one self-hosted.",
      "General tools like Trello and Notion can work as a roadmap at very small scale, but lack voting and changelogs.",
      "Check whether the public view, widget and changelog are free before you build a workflow around a tool.",
    ],
    faqs: [
      { q: "Is Feedlark really free, or is it a trial?", a: "Feedlark's free plan does not expire and does not require a credit card. It includes the feedback board, public roadmap and changelog for unlimited end-users. Paid seats only add extras like custom branding and private boards." },
      { q: "Can I use Trello or Notion as a roadmap tool?", a: "Yes, at a small scale. Both have generous free tiers, but neither supports voting, voter notifications or a changelog, so you are building and maintaining the roadmap by hand rather than automating it." },
      { q: "What is the catch with most free roadmap tools?", a: "Most cap the number of tracked users or lock the public view behind a paid plan after a short trial. Always check whether the free tier is permanent or time-limited before building a workflow around it." },
      { q: "Is self-hosting a free roadmap tool worth it?", a: "It depends on whether you already have the DevOps capacity. Fider is genuinely free to run, but you take on the server, database and maintenance work yourself, which can cost more in time than a hosted plan costs in money." },
    ],
  },
  {
    slug: "canny-pricing-explained",
    title: "Canny pricing in 2026: what it really costs",
    description:
      "A clear breakdown of Canny's 2026 pricing: the 25-tracked-user free cap, per-user billing, hidden costs, and how to avoid the growth tax entirely.",
    date: "2026-06-18",
    keyword: "canny pricing",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=1080&q=80&fm=jpg&auto=format&fit=crop&ixlib=rb-4.1.0",
    imageAlt: "Three ascending stacks of coins on a white table, representing tiered pricing plans and cost budgeting",
    readMins: 5,
    blocks: [
      { p: "Canny is the best known customer feedback tool on the market, and its pricing is the single most common reason teams start looking elsewhere. This is a full breakdown of how Canny prices its plans in 2026, where the bill quietly grows, and what a [free alternative](/blog/best-canny-alternatives) actually looks like by comparison." },
      { h2: "How Canny's pricing works", p: "Canny sells access in tiers, and the deciding factor in which tier you need is not features, it is the number of tracked users on your account. A tracked user is anyone who posts, votes or comments on a board, which means an embedded widget on a busy signup page can add dozens of tracked users in a single afternoon. Canny also separates admin seats from tracked users, so a five-person team can still find itself paying more than expected once its customer base engages." },
      { h2: "The free plan caps at 25 tracked users", p: "Canny's free plan limits accounts to 25 tracked users in total. That ceiling is easy to hit: a single email blast asking for feedback, a mention in a newsletter, or a feature request thread shared internally can push a new account past 25 within days. Once you cross the limit, Canny requires an upgrade to keep the board running, which is a difficult surprise for a team that expected 'free' to mean free." },
      { h2: "Paid plans bill per tracked user", p: "In 2025, Canny moved to per-tracked-user billing and retired its older, more generous free plan. Paid plans start around $79 a month when billed yearly, and the bill rises from there as tracked users grow. For a product with a small, quiet user base, this can stay affordable for years. For a product that is actually gaining traction, and hopefully that is the goal, the bill can climb into the hundreds of dollars a month faster than most teams budget for." },
      { h2: "Why this is a 'growth tax'", p: "The core problem is not that Canny charges money. Every tool on this list charges money somewhere. The problem is what triggers the charge. The more your feedback board takes off, the more you pay, even though an extra voter costs Canny almost nothing to serve. Teams that succeed at building an engaged community get punished for it with a bigger bill, which is a strange incentive to build into a tool meant to encourage the kind of engagement that [Zendesk's 2026 CX Trends research](https://cxtrends.zendesk.com/) shows customers increasingly expect from the brands they buy from." },
      { h2: "Hidden costs beyond the sticker price", p: "The advertised monthly price is rarely the whole story. Extra admin seats, private boards, single sign-on and priority support are often gated behind higher tiers, so a team that needs even one of those features on top of its tracked-user count can find itself paying for two upgrades at once. It is worth listing exactly which features you need before comparing prices, rather than comparing the cheapest advertised tier on each vendor's website." },
      { h2: "A worked example", p: "Picture a small SaaS product with 400 monthly active users. Early on, only a handful vote on ideas, so the free plan covers it comfortably. Then a popular newsletter features the product, signups triple in a week, and a message on the homepage invites new users to vote on the roadmap. Tracked users jump past 25 within days, the account needs an upgrade, and the team ends up choosing a pricing tier under time pressure instead of on their own schedule. This is a common pattern precisely because the trigger for upgrading, tracked users, correlates directly with the thing every team is trying to achieve: more engaged customers." },
      { h2: "How to avoid it", p: "Feedlark takes the opposite approach. Unlimited end-users, posts and votes are free forever, and you only pay per admin seat, [from $19 a month](/pricing), if you want extras like custom branding and private boards. Your 26th voter costs nothing, and so does your 26,000th. That structure matters more the more successful your feedback board becomes, which is exactly backwards from how Canny's model behaves. If you are actively comparing options, our [roundup of Canny alternatives](/blog/best-canny-alternatives) covers six more tools beyond Feedlark, each with a different pricing model worth checking against your own growth plans." },
      { h2: "When Canny might still be worth it", p: "None of this makes Canny a bad product. Its integrations are genuinely wide, its interface is polished, and for a team with a small, stable user base that is unlikely to grow much, the entry tier can stay cheap indefinitely. The calculation changes once growth becomes the actual goal, which is the case for most SaaS teams reading a pricing comparison in the first place. It is also worth remembering that pricing surprises are one of the more avoidable contributors to churn: Recurly's benchmark data puts [average subscription churn at 3.27% a month](https://recurly.com/research/churn-rate-benchmarks/), and a predictable bill helps keep that number down." },
      { h2: "How to forecast your own bill before you sign up", p: "Before committing to any tracked-user pricing model, estimate your likely tracked-user count six months out, not today. Look at your current monthly active users, assume a modest percentage will engage with a feedback board once it exists, usually somewhere between two and ten percent for an embedded widget, and check where that number lands on the pricing page. If it lands near a tier boundary, budget for the tier above, because growth rarely stops exactly at a convenient line. This single exercise, done honestly, avoids most of the unpleasant billing surprises teams report after their first few months on a per-tracked-user plan." },
      { h2: "What to ask a vendor before switching pricing models", ul: [
        "What happens automatically if we exceed our tracked-user limit mid-month?",
        "Is there a grace period, or does the board stop working immediately at the cap?",
        "Can we downgrade later if engagement drops, and does that lose historical data?",
        "Are admin seats billed separately from tracked users, and how many are included by default?",
      ] },
      { h2: "The simplest fix if you are already stuck", p: "If you are already past a Canny tier boundary and the next upgrade feels steep, it is worth pausing before paying it and pricing out a switch instead. Exporting existing posts and votes typically takes an afternoon, and moving to a tool billed per admin seat removes the tracked-user problem permanently rather than deferring it to the next boundary. A one-off migration cost is usually smaller than a year of a bill that keeps climbing in step with your own success." },
      { h2: "The takeaway for anyone comparing pricing pages", p: "Read past the headline number on any feedback tool's pricing page and ask what specifically triggers a higher bill. A model billed on team size stays predictable as your customer base grows. A model billed on tracked users does not, and that single structural difference matters far more over a year than a few dollars of difference in the advertised starting price." },
      { quote: { text: "We loved Canny until our biggest feature request thread went viral inside our own customer base. The board worked exactly as designed, and that was the problem: the bill tripled the same month our churn dropped.", cite: "SaaS founder, describing a first year on tracked-user pricing" } },
      { table: {
        caption: "Canny pricing versus a per-seat alternative",
        head: ["Plan", "Billed on", "Free tier limit", "Cost as users grow"],
        rows: [
          ["Canny Starter/Growth", "Tracked users", "25 tracked users", "Rises with every new voter"],
          ["Canny Business/Enterprise", "Tracked users + seats", "None", "Rises further with admin needs"],
          ["Feedlark Free", "Admin seats only", "Unlimited end-users", "Flat, does not rise with voters"],
          ["Feedlark Pro", "Admin seats only", "Unlimited end-users", "$19 per seat, unaffected by growth"],
        ],
      } },
    ],
    takeaways: [
      "Canny bills by tracked user, so its cost rises with engagement rather than team size.",
      "The free plan caps at 25 tracked users, a limit busy boards can hit within days.",
      "Extra features like private boards and single sign-on often require a further tier upgrade on top.",
      "Feedlark charges per admin seat instead, so unlimited voters never add to the bill.",
    ],
    faqs: [
      { q: "How much does Canny cost per month?", a: "Canny's paid plans start around $79 a month when billed yearly, and the price rises as your number of tracked users grows. The free plan is capped at 25 tracked users in total." },
      { q: "What counts as a tracked user on Canny?", a: "Anyone who posts, votes or comments on a board counts as a tracked user, regardless of whether they are a paying customer. A busy feedback widget can add many tracked users in a single day." },
      { q: "Is there a free alternative to Canny?", a: "Yes. Feedlark offers unlimited end-users, posts and votes for free, and only charges for admin seats on the [Pro plan](/pricing)." },
      { q: "Why do teams call Canny's pricing a 'growth tax'?", a: "Because the trigger for a higher bill is the same thing every team wants: more engaged users voting and commenting. Costs rise exactly when the product is succeeding, which many teams find backwards for a feedback tool." },
    ],
  },
  {
    slug: "best-canny-alternatives",
    title: "7 best Canny alternatives in 2026 (free & paid)",
    description:
      "Compare seven of the best Canny alternatives for 2026, including Feedlark, Featurebase and Nolt, by price, free tier, changelog and roadmap features.",
    date: "2026-06-17",
    keyword: "canny alternatives",
    category: "Reviews",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and spends a surprising amount of her week reading other companies' pricing pages.",
    image: "https://images.unsplash.com/photo-1512758017271-d7b84c2113f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Colourful sticky notes pinned to a board representing a feedback and community planning wall",
    readMins: 7,
    blocks: [
      { p: "If Canny's per-user pricing or 25-user free cap pushed you to start looking around, you are not alone. This guide compares seven alternatives, what each one costs, and where each genuinely differs from Canny on the thing that matters most as you grow: what you pay once people actually start using your board. For the full detail on why Canny's own pricing matters so much to this decision, see our [breakdown of Canny's 2026 pricing](/blog/canny-pricing-explained)." },
      { h2: "Feedlark", p: "Feedlark is free for unlimited end-users, posts and votes, with paid seats from [$19 a month](/pricing) for teams that want custom branding or private boards. It adds a built-in changelog that notifies voters automatically when their request ships, which closes the loop without any manual follow-up. Setup takes under ten minutes, and there is no tracked-user limit to trip over as your board grows." },
      { h2: "Featurebase", p: "Featurebase is free for unlimited end-users, with seats billed from $29 a month. It includes a help centre module and audience segmentation on top of the standard feedback board, which suits teams that want a combined support and feedback hub rather than a lighter, more focused tool." },
      { h2: "Frill", p: "Frill keeps things clean and simple, starting from around $25 a month with white-label options on higher tiers. It is a good fit for teams that want to get a board live quickly without a lengthy setup process, though it lacks the AI deduplication and roadmap automation that busier boards eventually need." },
      { h2: "Nolt", p: "Nolt charges a flat rate of roughly $29 a month per board rather than per user, which makes costs predictable regardless of how many people vote. The tradeoff is a smaller feature set: no API, no AI deduplication and no changelog tied to the roadmap. Our [Nolt alternatives guide](/blog/nolt-alternatives) covers this comparison in more depth." },
      { h2: "Productboard", p: "Productboard is a full enterprise product management platform with discovery and prioritisation tools built in, priced per 'maker' or editor. It is powerful, but it is a heavier tool than most teams switching away from Canny actually want. Our [guide to Productboard alternatives](/blog/productboard-alternatives) looks at this comparison from the other direction, for teams starting from Productboard rather than Canny." },
      { h2: "Upvoty", p: "Upvoty is one of the more affordable options, starting from around $15 a month. It covers the core feedback board and a simple roadmap view, making it a reasonable choice for budget-conscious teams that do not need deep integrations or automation." },
      { h2: "Fider", p: "Fider is open source and free if you are willing to self-host it. It covers voting, statuses and a public roadmap, and gives you full control of your data, but it also puts the server, database and maintenance work on your own team rather than a vendor." },
      { h2: "How to choose", p: "If you want a focused feedback board, public roadmap and changelog without paying more as more people engage, look for a tool billed per admin seat, or free, rather than one billed per tracked user. That single distinction explains most of the price difference between these seven tools once a board actually starts working, and it matters for retention too: Recurly's benchmark data puts [average subscription churn at 3.27% a month](https://recurly.com/research/churn-rate-benchmarks/), a number that transparent, responsive teams tend to beat." },
      { h2: "How these seven tools handle integrations", p: "Integrations are often the deciding factor once price is settled. Canny and Featurebase both connect to tools like Jira, Slack and Intercom out of the box, which suits teams with an established workflow they do not want to rebuild. Feedlark keeps its integration list tighter but focuses on making the core loop, feedback to roadmap to changelog, work without any configuration at all. Nolt, Frill and Upvoty are lighter on integrations across the board, which is consistent with their simpler pricing and setup. Fider's integrations depend entirely on what you are willing to build yourself, since it is open source." },
      { h2: "What migrating between these tools actually involves", p: "Most of these platforms let you export existing posts and votes in a simple file format, and importing into a new tool usually takes an afternoon for a small board. The larger task is redirecting your embedded widget or public roadmap link and letting existing voters know where things moved. Budget a short overlap period where both the old and new boards stay visible, with a clear note pointing people to the new one, so nobody's bookmark leads to a dead page during the switch." },
      { h2: "A note on support quality across price points", ul: [
        "Canny and Productboard both offer dedicated support on their higher tiers, reflecting their enterprise pricing",
        "Feedlark and Featurebase provide direct support even on free plans, since both monetise through paid seats rather than gated support",
        "Nolt, Frill and Upvoty offer standard email support typical of their price point",
        "Fider relies on community support and documentation, which suits technical teams comfortable self-serving",
      ] },
      { h2: "Questions worth asking during a trial", p: "Before settling on any of these seven, run a short trial with your own data rather than relying on the marketing site alone. Add a handful of real feature requests, invite a colleague to vote, and check whether the public roadmap view actually works logged out in a private browser window. Confirm whether a changelog entry publishes automatically when you mark something as shipped, and whether existing voters would be notified. These small checks catch the gap between what a pricing page promises and what the product actually does far more reliably than reading reviews." },
      { h2: "How team size should shape the decision", p: "A solo founder evaluating these tools has different priorities from a ten-person product team. Smaller teams tend to value fast setup and low ongoing cost above deep integrations, which points toward Feedlark, Nolt or Upvoty. Larger teams with existing tooling investments often value integration depth more, which points toward Canny or Featurebase. Matching the tool to your actual team size, not the team size you hope to have in two years, avoids paying for capability that sits unused." },
      { h2: "Final word before you decide", p: "Seven tools, seven pricing models, and no single right answer. What matters is picking the model that fits how your product actually grows: per seat if your team grows slowly and your customer base grows fast, per tracked user only if you are confident your community will always stay small. Most teams reading a Canny alternatives roundup already know which of those two describes them." },
      { h2: "Our pick for value", p: "Feedlark is free for unlimited users and charges only per admin seat, which makes it the most predictable option for a product that expects to grow. Predictability matters here for a reason beyond convenience: engaged, well-served customers are valuable customers, and Bain's widely cited research found that [raising customer retention by five points can lift profits by 25 to 95%](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers). A pricing model that punishes exactly the engagement you are trying to build works against that goal." },
      { quote: { text: "Our board hit 30 tracked users in the first week after launch. We were not upset that people were voting, we were upset that voting triggered an invoice.", cite: "Early-stage founder, on a first month using tracked-user pricing" } },
      { table: {
        caption: "Canny alternatives at a glance",
        head: ["Tool", "Starting price", "Free tier", "Notable strength"],
        rows: [
          ["Feedlark", "$19/seat", "Unlimited end-users", "Automatic changelog and voter notifications"],
          ["Featurebase", "$29/seat", "Unlimited end-users", "Help centre and segmentation"],
          ["Frill", "From $25/mo", "Trial only", "Fast setup, white-label options"],
          ["Nolt", "~$29/mo per board", "Trial only", "Predictable flat pricing"],
          ["Productboard", "Per maker", "None", "Deep discovery and prioritisation"],
          ["Upvoty", "From $15/mo", "Trial only", "Budget-friendly basics"],
          ["Fider", "Free (self-hosted)", "Unlimited", "Full data control"],
        ],
      } },
    ],
    takeaways: [
      "Canny's tracked-user billing is the main reason teams look for alternatives once a board grows.",
      "Feedlark and Featurebase both offer genuinely free tiers with unlimited end-users.",
      "Nolt and Frill offer simpler, cheaper setups but fewer integrations and no changelog automation.",
      "Choose a tool billed per seat, or free, rather than per tracked user, if you expect real growth.",
    ],
    faqs: [
      { q: "Which Canny alternative is completely free?", a: "Feedlark and Featurebase both offer free tiers with unlimited end-users. Fider is also free, but only if you self-host it yourself, which takes on server and maintenance work in exchange for zero licensing cost." },
      { q: "Is Nolt cheaper than Canny?", a: "For a single small board, often yes, since Nolt charges a flat rate rather than per tracked user. Canny can become more expensive than Nolt once your community grows past a modest size." },
      { q: "What is the best Canny alternative for a support-heavy product?", a: "Featurebase is worth a close look, since it combines a feedback board with a help centre module, which suits teams that want feedback and support handled in one place." },
      { q: "Do any Canny alternatives include a changelog?", a: "Yes. Feedlark and Featurebase both include a changelog, and Feedlark specifically notifies voters automatically when a feature they asked for ships, closing the feedback loop without manual follow-up." },
    ],
  },
  {
    slug: "roadmap-software-free-buyers-guide",
    title: "Free roadmap software: what's actually free in 2026",
    description:
      "Free roadmap software claims are everywhere, but most hide a trial or a user cap. Here's how to tell genuinely free tools from freemium in disguise.",
    date: "2026-07-04",
    keyword: "roadmap software free",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Team reviewing roadmap software free options on a laptop during a planning meeting",
    readMins: 7,
    blocks: [
      { p: "Type 'roadmap software free' into a search bar and you will find a dozen tools claiming a free plan. Read the small print on half of them and the free plan turns out to be a fourteen-day trial, a five-item cap, or a single-user limit that makes it useless for an actual team. This guide separates roadmap software that is genuinely free from software that is free for just long enough to get you hooked, and explains exactly what to check before you build a workflow around any of them." },
      { h2: "The freemium trap: what 'free' usually means", p: "Most vendors use 'free' to describe three different things, and only one of them is actually free. Some plans are time-limited trials of the paid product, dressed up as a free tier. Some are usage-capped, working fine until you hit five roadmap items or one hundred votes, at which point the paywall appears. A smaller group are genuinely free forever, with the vendor making money from optional paid seats or add-ons rather than from access itself. The wording on a pricing page rarely tells you which of these three you are looking at, so you have to check the actual limits yourself." },
      { h2: "Five questions to ask before you trust a free plan", ul: [
        "Does the free plan expire, or does it renew forever without a credit card?",
        "Is the public roadmap view included, or is it a paid-only feature?",
        "Is there a cap on end-users, votes or items that a real launch would hit fast?",
        "Can you export your data if you decide to leave the free plan?",
        "Does the vendor's own pricing page use the word 'trial' anywhere near the word 'free'?",
      ] },
      { h2: "Feedlark: what's actually free", p: "Feedlark's free plan includes a feedback board, a public roadmap and a changelog, with no cap on end-users and no expiry date. You do not need a credit card to [sign up](/signup), and the plan does not convert into a trial after a set period. The paid [Pro plan](/pricing), at $19 per admin seat, adds custom branding, private boards and team roles. Nothing about the core roadmap experience, posting, voting, viewing the public roadmap, is held back for paying customers, which is the clearest test of whether a free plan is real." },
      { h2: "Featurebase: free tier with some depth locked away", p: "Featurebase is free for unlimited end-users, which is a genuinely strong starting point. Where it differs from Feedlark is in feature depth: several of its more advanced tools, including deeper segmentation and help centre features, sit behind paid seats starting from $29 a month. That is a fair model, not a trap, but it means the free plan is a smaller slice of the full product than Feedlark's is." },
      { h2: "Fider: free but not hosted for you", p: "Fider is open source, so the software itself costs nothing regardless of scale. The catch is that nobody hosts it for you: you need a server, a database and someone able to maintain both. For a team with in-house DevOps capacity, that trade is worth making. For most small SaaS teams, the hosting and maintenance overhead outweighs the money saved." },
      { h2: "Canny and Productboard: free trials wearing a free-plan costume", p: "Canny's free plan caps at 25 tracked users in total, a limit an engaged feedback board can reach within days of launch, at which point you are choosing a paid tier under time pressure rather than on your own schedule. Our [full breakdown of Canny's pricing](/blog/canny-pricing-explained) covers exactly how that plays out. Productboard, meanwhile, has no meaningful free plan at all: it is built around per-maker pricing aimed at larger product teams, and our [guide to Productboard alternatives](/blog/productboard-alternatives) is the better read if that is the tool you are comparing against." },
      { h2: "The upgrade path: what should trigger paying", p: "A well-designed free plan should make you pay for things that add convenience, not things that unlock basic use. Custom branding, private internal boards, single sign-on and advanced permissions are reasonable reasons to upgrade. Being forced to pay because your 26th customer voted on an idea is not. When you compare tools, check which category each upgrade trigger falls into before you commit, because that decision determines whether your bill grows in step with your team or in step with your customers." },
      { h2: "Why this matters for the decision you actually make", p: "A public roadmap only works if people trust it will still be there next month, and that trust matters more than most teams expect: Zendesk's 2026 CX Trends research found that 63% of customers say their [demand for transparency from companies has risen](https://cxtrends.zendesk.com/). Picking a tool whose free plan might vanish or convert to a paid trial halfway through the year undermines that trust before you have had a chance to build it. It is worth reading a little discovery theory here too: Nielsen Norman Group's [guide to running discovery research](https://www.nngroup.com/articles/discovery-study-guide/) makes the point that customers need a consistent place to be heard, not a moving target." },
      { h2: "How to spot a disguised trial in five minutes", ul: [
        "Search the vendor's help centre for the word 'trial' even if the pricing page only says 'free'",
        "Check whether the public roadmap URL still works after you stop paying, not just while you are on it",
        "Look for a countdown, a banner, or an email asking you to 'upgrade before your data is removed'",
        "Try creating an account without a credit card. If it asks for one, read the terms closely before assuming it is free",
      ] },
      { h2: "Budget-conscious teams still have real options", p: "None of this means a small budget forces a bad tool. Genuinely free plans exist precisely because vendors like Feedlark and Fider make money elsewhere, from paid seats or from support contracts rather than from basic access. A team on a tight budget can run a full public roadmap and feedback board indefinitely without ever paying, provided they pick a tool whose business model does not depend on that free plan expiring. The skill is not finding something cheap, it is telling the difference between cheap and temporarily cheap." },
      { h2: "A short checklist before you commit", p: "Before adding a roadmap tool to your stack, create a real account, add a few test items, and try viewing your public roadmap logged out in a private browser window. Confirm the free plan covers voting, a public view and basic status updates without a paywall appearing. Check whether existing data would export cleanly if you ever wanted to leave. This fifteen-minute exercise catches almost every disguised trial before it costs you a migration headache six months down the line." },
      { h2: "The pattern worth remembering", p: "Every genuinely free tool on this list makes money from something optional: extra seats, branding, or private boards. Every disguised trial makes money from removing the thing you already rely on the moment a countdown ends. That single distinction, what triggers payment, tells you more about a free plan's honesty than any amount of marketing copy, and it is worth checking on every tool you evaluate, not just the ones on this list. Keep that one question in your back pocket the next time a pricing page uses the word free, and you will rarely be caught out by a surprise bill again." },
      { table: {
        caption: "Advertised free vs. actually free",
        head: ["Tool", "Advertised as", "User cap", "Expires or converts to trial"],
        rows: [
          ["Feedlark", "Free plan", "None", "No"],
          ["Featurebase", "Free plan", "None (core features)", "No"],
          ["Fider", "Free (self-hosted)", "None", "No"],
          ["Canny", "Free plan", "25 tracked users", "Requires upgrade at cap"],
          ["Productboard", "Trial", "N/A", "Yes, converts to paid"],
        ],
      } },
    ],
    takeaways: [
      "Free roadmap software comes in three types: genuine, usage-capped, and a trial wearing free-plan branding.",
      "Check whether the public roadmap, widget and changelog are included, not just the voting board.",
      "A fair upgrade trigger adds convenience, like branding or private boards, not basic access.",
      "Feedlark and Fider are both genuinely free forever, one hosted, one self-managed.",
    ],
    faqs: [
      { q: "Is there roadmap software that's free forever, not just a trial?", a: "Yes. Feedlark's free plan has no expiry and no credit card requirement, covering the feedback board, public roadmap and changelog for unlimited end-users. Fider offers similar functionality for free if you self-host it." },
      { q: "Why do some 'free' roadmap tools ask for a credit card?", a: "That is usually a sign the free plan is actually a trial of a paid product. A genuinely free plan, like Feedlark's, does not need billing details because there is nothing to convert to later." },
      { q: "What should I check before trusting a free roadmap plan?", a: "Look for a cap on end-users or votes, check whether the public roadmap view is included, and see whether the vendor's own pricing page uses the word 'trial' anywhere near 'free'." },
      { q: "Is a self-hosted free tool like Fider better than a hosted free plan?", a: "It depends on your team. Self-hosting removes licensing cost but adds server and maintenance work. A hosted free plan like Feedlark's trades a small amount of control for zero setup and no ongoing upkeep." },
    ],
  },
  {
    slug: "productboard-free-alternative",
    title: "The best free Productboard alternative in 2026",
    description:
      "Productboard has no real free plan, just a trial. Here's the closest genuinely free alternative, what you keep, and what you give up switching.",
    date: "2026-07-05",
    keyword: "productboard free alternative",
    category: "Reviews",
    author: "Tom Whitfield, Feedlark co-founder",
    authorBio: "Tom co-founded Feedlark after years of watching product teams pay enterprise prices for features they rarely used.",
    image: "https://images.unsplash.com/photo-1553484771-371a605b060b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Person comparing productboard free alternative options on a tablet at a desk",
    readMins: 6,
    blocks: [
      { p: "Search for a Productboard free alternative and you will quickly notice something: Productboard itself doesn't really have a free plan. What it offers is a trial, useful for evaluating the product, not for running a real roadmap indefinitely without paying. This guide is for teams that specifically want a tool that stays free, not just a cheaper enterprise platform, and covers what you keep and what you lose by making that switch. If you want the broader comparison including paid options, our [guide to Productboard alternatives](/blog/productboard-alternatives) covers six tools across every price point." },
      { h2: "Why Productboard doesn't have a real free plan", p: "Productboard is built for product teams running structured discovery work: customer interview logs, insight tagging, prioritisation frameworks and roadmap views tied together. That is a genuinely useful set of tools for a team of product managers, but it is expensive to build and expensive to license, and Productboard prices it accordingly, per 'maker' or editor, with no free tier for ongoing use. If your team's actual need is simpler, a public roadmap, a feedback board and a changelog, you are paying for a lot of capability you will not touch." },
      { h2: "What a free alternative should actually include", ul: [
        "A public roadmap that customers can view without logging in",
        "A feedback board where people can post ideas and vote on existing ones",
        "No cap on the number of end-users who can vote or comment",
        "No credit card required, and no conversion to a paid trial after a set period",
        "Enough structure to organise requests by status, even without Productboard's deeper prioritisation tools",
      ] },
      { h2: "Feedlark: the closest free equivalent", p: "Feedlark covers the three things most teams actually use Productboard for: a feedback board, a public roadmap and a changelog, all included in a free plan with no user cap. It does not attempt to replace Productboard's discovery workflows, interview logs or scoring frameworks, and it is honest about that limitation. What it does include is enough to run a transparent, customer-facing roadmap without spending anything, with a [Pro plan](/pricing) at $19 per seat if you later want branding or private boards. Teams can [try the free plan](/signup) directly rather than starting a countdown-timer trial." },
      { h2: "Featurebase: free but different in shape", p: "Featurebase also offers a genuinely free plan for unlimited end-users, with paid seats from $29 a month for extra depth like a help centre module and audience segmentation. It sits a little closer to Productboard in ambition than Feedlark does, though it still does not attempt full discovery tooling. If you want more built-in structure than Feedlark offers and are prepared to pay for advanced features later, it is worth a direct trial." },
      { h2: "Fider: free if you can self-host", p: "Fider is open source, so it costs nothing in licensing fees regardless of how large your account grows. The tradeoff is that you run the infrastructure yourself: a server, a database and ongoing maintenance. For a team with existing DevOps capacity, that is a fair trade for permanent, unlimited free use. For most small SaaS teams, a hosted free plan is the more practical choice." },
      { h2: "What you give up moving from Productboard to a free tool", p: "None of the free alternatives replicate Productboard's discovery workflows: structured interview notes, insight tagging linked to specific customers, and weighted scoring frameworks for prioritisation. If your product team relies heavily on those, no free tool fully replaces them, and the honest answer is that you may need to keep a paid seat or two of Productboard for the strategy layer while running your public-facing roadmap somewhere lighter. Good discovery practice does not actually require expensive tooling though: Nielsen Norman Group's [guide to structuring discovery research](https://www.nngroup.com/articles/discovery-study-guide/) is a useful reference if you want to run that process manually alongside a simpler roadmap tool." },
      { h2: "Who should actually make this switch", p: "This move makes the most sense for small SaaS teams where one or two people wear the product manager hat alongside other jobs, and where the main need is a public roadmap and a way to close the loop with customers, not a full strategy suite. If your team includes several dedicated product managers running structured prioritisation exercises every sprint, Productboard's paid tiers may still earn their cost. For everyone else, a free tool that customers can actually see tends to build more goodwill than an internal strategy tool they never encounter: Bain's research on customer loyalty found that [lifting retention by five percentage points can raise profits by 25 to 95%](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers), and a visible roadmap is a low-cost way to work toward that." },
      { h2: "A hybrid setup some teams run instead", p: "A smaller number of teams keep one or two Productboard seats for internal discovery work, interview logs, insight tagging and prioritisation scoring, while running their public-facing roadmap and feedback board on a free tool like Feedlark. This gives product managers the structured internal process they are used to, without paying for extra seats just so more people can view a public roadmap that a free tool handles just as well. It is a reasonable middle ground if you are not ready to give up Productboard's discovery tools entirely but do not want its pricing dictating how many people can see your roadmap." },
      { h2: "What to check before you fully commit to a free tool", ul: [
        "Does the free plan let you export votes and posts if you later need to move again?",
        "Is there a limit on the number of admin accounts, even on the free tier?",
        "Can you customise statuses to match how your team already talks about progress?",
        "Does the changelog publish automatically, or does someone need to write it by hand each time?",
      ] },
      { h2: "Setting expectations with your team", p: "However you switch, tell your team plainly what changes and what does not. A free tool covers the public roadmap and feedback loop, not the internal strategy conversations Productboard supported. Some teams find they replace those conversations with a simple recurring planning meeting instead, using the public roadmap as the shared reference point. Others discover they relied on Productboard's structure more than they realised, and choose the hybrid setup above. Either outcome is fine. What matters is deciding deliberately rather than losing structured discovery by accident during a cost-cutting exercise." },
      { h2: "A final sanity check before you switch", p: "Create a real account on your shortlisted free tool, add a handful of genuine feature requests, and view the public roadmap logged out in a private browser window before committing anything else. This confirms the free plan behaves exactly as advertised rather than as described on a marketing page, and it takes less time than reading the rest of this guide." },
      { h2: "One year on", p: "Teams that make this switch tend to look back on it as an easy decision in hindsight, mostly because the public roadmap kept working exactly the same way a year later, with no surprise bill and no sudden feature lockout. That quiet reliability is the actual point of choosing a genuinely free tool over a trial dressed up as one, and it is worth more to most small teams than any single feature Productboard might have offered instead." },
      { table: {
        caption: "Productboard vs. free alternatives",
        head: ["Tool", "Free plan", "Discovery tooling", "Best for"],
        rows: [
          ["Productboard", "Trial only", "Extensive", "Dedicated PM teams running structured discovery"],
          ["Feedlark", "Yes, unlimited users", "None", "Small teams wanting a public roadmap and changelog"],
          ["Featurebase", "Yes, unlimited users", "Basic", "Teams wanting feedback plus a help centre"],
          ["Fider", "Yes, self-hosted", "Basic", "Teams with in-house DevOps capacity"],
        ],
      } },
    ],
    takeaways: [
      "Productboard offers a trial, not a genuine free plan, so 'free alternative' searches need a different tool entirely.",
      "Feedlark and Featurebase both give unlimited free end-users, covering what most small teams actually use daily.",
      "None of the free tools replicate Productboard's discovery and prioritisation frameworks.",
      "The switch suits small teams most; larger PM teams doing structured discovery may still need Productboard.",
    ],
    faqs: [
      { q: "Does Productboard have a free plan?", a: "Not a permanent one. Productboard offers a free trial to evaluate the product, but ongoing use requires a paid, per-maker subscription. There is no free tier for continuous use like there is with Feedlark or Featurebase." },
      { q: "What's the closest free alternative to Productboard?", a: "Feedlark and Featurebase both offer genuinely free plans with unlimited end-users, covering a feedback board and public roadmap. Neither replicates Productboard's deeper discovery and prioritisation tools, which are a different category of feature." },
      { q: "Will I lose features by switching from Productboard to a free tool?", a: "Yes, specifically around structured discovery: interview logs, insight tagging and weighted prioritisation frameworks. If your team relies heavily on those, you may want to keep them separate from your public-facing roadmap tool." },
      { q: "Is Feedlark suitable for a full product team, or just small teams?", a: "It works well for small to mid-sized teams whose main need is a transparent public roadmap, feedback board and changelog. Larger teams running formal discovery processes may still want a dedicated strategy tool alongside it." },
    ],
  },
  {
    slug: "roadmunk-free-alternative",
    title: "The best free alternative to Roadmunk in 2026",
    description:
      "Roadmunk is a solid mid-market roadmap tool with no free plan and per-editor pricing. Compare it fairly against genuinely free alternatives.",
    date: "2026-07-05",
    keyword: "roadmunk free alternative",
    category: "Reviews",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Product manager evaluating a roadmunk free alternative on a large monitor showing a timeline view",
    readMins: 6,
    blocks: [
      { p: "Roadmunk is a well-established roadmap tool built for mid-market product teams, known for its timeline-style roadmap views and swimlane layouts. It is a genuinely capable tool for internal planning, but it has no meaningful free plan and prices per editor, which puts it out of reach for smaller teams that just want a public roadmap and a feedback board. This guide compares Roadmunk fairly against tools that are actually free to run, without pretending Roadmunk is worse than it is at the job it was built for." },
      { h2: "What Roadmunk does well", p: "Roadmunk's strength is visual flexibility. It supports multiple roadmap formats, including timeline views, swimlanes and Kanban-style boards, which suits teams that need to present the same roadmap differently to different audiences: engineering, leadership and customers. For a mid-market product team with a dedicated planning process, that flexibility is a real advantage over lighter tools." },
      { h2: "Where Roadmunk's pricing sits", p: "Roadmunk prices per editor rather than per end-user, which is a more predictable model than tracked-user billing. It does not, however, offer a meaningful free tier for ongoing use, only a trial period to evaluate the product. For a team of five product managers, that per-editor cost adds up in the same way any per-seat enterprise tool does, and it is worth comparing directly against your expected team size before committing." },
      { h2: "What 'free alternative to Roadmunk' usually means", ul: [
        "A tool with no time-limited trial, that stays free indefinitely",
        "A public roadmap view, since Roadmunk's public sharing options sit on paid tiers",
        "A feedback board so customers can vote on what's next, which Roadmunk does not focus on",
        "No per-editor cost creeping up as more people need access",
      ] },
      { h2: "Feedlark: a free public roadmap and feedback board", p: "Feedlark is not a direct feature match for Roadmunk. It does not offer swimlane or timeline roadmap views. What it does offer is a free, permanent plan covering a public roadmap, a feedback board and a changelog, with no cap on end-users and no credit card required to [get started](/signup). For teams whose main need is customer-facing transparency rather than internal timeline planning, this is a lighter, cheaper way to get there. The [Pro plan](/pricing) at $19 a seat adds branding and private boards for teams that want more control later." },
      { h2: "Featurebase: another genuinely free option", p: "Featurebase also offers a free plan for unlimited end-users, with paid seats from $29 a month unlocking a help centre module and deeper segmentation. Like Feedlark, it is built around customer feedback and a public roadmap rather than internal timeline planning, so it is a similar category of tool to compare against Roadmunk rather than a like-for-like replacement." },
      { h2: "Trello or Notion: a manual free option", p: "Some smaller teams build a rough visual roadmap in Trello or Notion using boards and status labels. Both have generous free tiers, and Notion in particular can approximate a timeline view with its calendar and gallery layouts. Neither includes voting, a public-facing customer view, or a changelog, so you are trading Roadmunk's polish for a fully manual process, which only holds up at a small scale." },
      { h2: "What you trade away", p: "Moving from Roadmunk to a free tool means giving up multiple roadmap view formats and the swimlane-style planning that mid-market teams often build internal processes around. If your team relies on presenting the same roadmap in different visual formats to different stakeholders, no tool on this list matches that exactly, and it is worth being honest about that before switching. What you gain instead is a public-facing roadmap your customers can actually see, which research suggests matters more to them than most teams assume: Zendesk's 2026 CX Trends work found that 63% of customers report [rising demand for transparency](https://cxtrends.zendesk.com/) from the companies they use." },
      { h2: "Who should switch, and who shouldn't", p: "If your team's main need is internal planning across multiple visual formats for different stakeholders, Roadmunk remains a solid, purpose-built choice, and switching away from it purely to save money may cost you process quality you actually rely on. If your main need is a public roadmap and feedback board that customers can see and vote on, Feedlark or Featurebase get you there for nothing, and Roadmunk's swimlane views were likely never the point for your use case anyway. It is worth remembering the wider financial case for that kind of trust too: Bain's research shows [raising retention by five points can lift profits by 25 to 95%](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers). Reading up on [how to build a public roadmap](/blog/how-to-build-public-roadmap) is a good next step either way, since the presentation layer matters less than whether customers trust what they are looking at." },
      { h2: "Running both tools side by side", p: "A reasonable middle path is keeping Roadmunk for internal planning, where its swimlane and timeline views genuinely earn their cost with a mid-market planning process, while running a separate, free public roadmap for customers using Feedlark or Featurebase. The two serve different audiences: Roadmunk's internal view helps leadership and engineering plan capacity, while a public roadmap helps customers see what is coming and vote on what matters to them. Few teams need one tool to do both jobs well, and trying to force Roadmunk's internal planning views into a customer-facing role often produces a roadmap that is either too detailed for customers or too simplified for planning." },
      { h2: "Questions to ask before switching away from Roadmunk", ul: [
        "How many people on your team actually log into Roadmunk each week, versus just view exported screenshots?",
        "Would a simpler, list-style public roadmap satisfy most customer questions you currently get?",
        "Do you need swimlanes for internal planning specifically, or would a shared spreadsheet work just as well?",
        "Is per-editor pricing scaling faster than your team's actual headcount growth?",
      ] },
      { h2: "The honest tradeoff, summarised", p: "Roadmunk earns its price with visual flexibility that a free tool does not attempt to match. A free alternative earns its price, zero, by being honest about doing one job well: a public roadmap and feedback board that customers can actually use. Neither approach is wrong. The mistake is choosing based on brand recognition alone rather than checking which visual format and which price point your team genuinely needs this year, not the enterprise version you might grow into eventually." },
      { h2: "A practical next step", p: "If you are still unsure, list the last five questions customers actually asked about your product's direction. If a simple, votable list would have answered all five, a free tool likely covers your real need. If the answers depended on showing different views to engineering versus leadership versus customers, Roadmunk's flexibility is probably earning its keep already, and it is worth keeping rather than switching purely on price." },
      { h2: "A closing thought on fairness", p: "None of this is a criticism of Roadmunk as a product. It does a specific job for a specific kind of team well, and it has done so for years. The point of this guide is simply that 'free alternative' searches usually come from teams whose needs are lighter than Roadmunk was built for, and lighter needs deserve a lighter, cheaper answer, not a smaller version of an enterprise tool priced for a different kind of team entirely." },
      { table: {
        caption: "Roadmunk versus free alternatives",
        head: ["Tool", "Free plan", "Roadmap views", "Public customer view"],
        rows: [
          ["Roadmunk", "Trial only", "Timeline, swimlane, Kanban", "Paid tiers only"],
          ["Feedlark", "Yes, unlimited users", "Single list-style roadmap", "Yes, free"],
          ["Featurebase", "Yes, unlimited users", "Basic roadmap", "Yes, free"],
          ["Trello/Notion", "Yes, generous", "Manual Kanban or calendar", "Read-only, no voting"],
        ],
      } },
    ],
    takeaways: [
      "Roadmunk is a solid, established tool for mid-market teams, but it has no meaningful free tier.",
      "It prices per editor, which is predictable but adds up for teams with several product managers.",
      "Feedlark and Featurebase offer genuinely free plans, though neither matches Roadmunk's multiple visual formats.",
      "Keep Roadmunk if you rely on its swimlane and timeline views; switch if your real need is a public, votable roadmap.",
    ],
    faqs: [
      { q: "Does Roadmunk have a free plan?", a: "No, not for ongoing use. Roadmunk offers a trial period to evaluate the product, but continued use requires a paid, per-editor subscription. There is no permanent free tier." },
      { q: "What's the closest free alternative to Roadmunk?", a: "Feedlark and Featurebase both offer permanent free plans for unlimited end-users, covering a public roadmap and feedback board. Neither replicates Roadmunk's swimlane or timeline visual formats." },
      { q: "Is Roadmunk good value for a small team?", a: "It depends on team size. Roadmunk's per-editor pricing is predictable, but for a team of just one or two product people, that cost is hard to justify next to a free tool that covers the public roadmap and feedback side." },
      { q: "Can I replace Roadmunk with Trello or Notion for free?", a: "Only at a small scale. Both can approximate a visual roadmap, but neither supports customer voting or a public-facing changelog, so you take on the manual upkeep yourself." },
    ],
  },
  {
    slug: "intercom-changelog-alternative",
    title: "The best dedicated changelog alternative to Intercom",
    description:
      "Intercom's changelog feature is built for in-app messages, not a public release history. Here's a dedicated changelog alternative that fits better.",
    date: "2026-07-06",
    keyword: "intercom changelog",
    category: "Reviews",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and spends a surprising amount of her week reading other companies' pricing pages.",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Support and product team discussing an intercom changelog alternative around a laptop",
    readMins: 6,
    blocks: [
      { p: "People searching for an Intercom changelog alternative are usually not unhappy with Intercom as a support tool. They have noticed that Intercom's changelog and news features are built to push in-app messages to logged-in users, not to run a standalone, public-facing changelog that anyone can browse, subscribe to or find through search. This guide looks at what Intercom's feature is actually designed for, and where a dedicated [changelog tool](/blog/changelog-tool-guide) does a different job better." },
      { h2: "What Intercom's changelog feature actually is", p: "Intercom's News and product update features sit inside its wider messaging platform, designed to surface announcements to users while they are active inside your product. That works well for in-app engagement: a banner or a message that appears the next time someone logs in. It is not designed to be a public, indexable changelog page that exists independently of your app, one that a prospective customer or a non-logged-in visitor could find and browse." },
      { h2: "Why that's a mismatch for a public changelog", ul: [
        "In-app messages disappear once dismissed, with no permanent public archive",
        "There's no public URL that search engines or curious prospects can find on their own",
        "Entries aren't naturally tied to a feedback board or roadmap, so voters don't get notified when their request ships",
        "The format is built for short announcements, not a structured, dated release history",
      ] },
      { h2: "What a dedicated changelog tool should do", p: "A good changelog is a public, permanent record of what shipped and when, ideally tied to the feature requests that drove it. The open [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) standard puts this well: a changelog should be written for humans, kept in reverse chronological order, and grouped by the kind of change it describes. That is a useful yardstick even if you are not maintaining a code repository, because the underlying idea, a clear, dated, human-readable record, applies just as well to a product changelog aimed at customers." },
      { h2: "Feedlark: changelog tied to your roadmap and votes", p: "Feedlark's changelog is built to close the loop with the people who actually asked for something. When a roadmap item ships, the changelog entry publishes automatically and everyone who voted on that request gets notified, so the 'you asked, we shipped' message reaches the right people without anyone writing a manual email. It sits on the free plan alongside the [feedback board and public roadmap](/blog/how-to-build-public-roadmap), with no cap on end-users, and a [Pro plan](/pricing) at $19 a seat for teams that want custom branding on top." },
      { h2: "Featurebase: changelog plus a broader support suite", p: "Featurebase also includes a changelog, alongside its help centre and support-focused features, on a free plan for unlimited end-users with paid seats from $29 a month. If you are already comparing Intercom because you want a combined support and feedback tool rather than a lightweight changelog, Featurebase's broader scope may be the more direct comparison to make." },
      { h2: "Do you need Intercom at all, or just a changelog?", p: "It is worth separating two different questions here. If Intercom is working well as your support and messaging tool, you do not need to replace it, you just need somewhere else to publish a public changelog, and Feedlark or Featurebase can run alongside Intercom for that specific job. If you are reconsidering Intercom entirely, that is a bigger decision involving your whole support stack, and outside the scope of a changelog comparison. Most teams searching for an 'Intercom changelog alternative' are in the first group: happy with support, missing a public release history. Getting that release history right pays off in ways that are easy to underestimate: research on [customer discovery](https://www.nngroup.com/articles/discovery-study-guide/) consistently shows that customers who feel heard, and can see it reflected back to them, engage more deeply over time, which is exactly what a connected changelog and roadmap is built to demonstrate." },
      { h2: "Running Intercom and a dedicated changelog together", p: "Most teams that make this switch keep both tools running side by side rather than picking one. Intercom continues handling live chat, support tickets and in-app messages, while the dedicated changelog handles the public, permanent record of what shipped. A short in-app message through Intercom pointing to the new changelog entry works well as a one-two combination: the immediate nudge comes from Intercom, and the lasting, shareable, searchable record lives on the dedicated changelog page. Neither tool needs to do the other's job for this to work well." },
      { h2: "How to migrate existing update history", p: "If you have been publishing updates through Intercom's News feature for a while, most of that content is straightforward to recreate on a dedicated changelog. Copy the date, the headline and the description for each past update, group them by month or by release, and publish them as a backfilled history. This gives new visitors context on how actively the product has been developed, rather than a changelog that appears to start from nothing on the day you switched tools. It typically takes an afternoon for a year's worth of updates." },
      { h2: "What good changelog habits look like day to day", ul: [
        "Publish an entry the same day a feature ships, not in a monthly batch, so voters get notified promptly",
        "Group entries by type, new features, improvements and fixes, so readers can scan quickly",
        "Link each entry back to the original feature request where relevant, closing the loop visibly",
        "Keep entries short and written in plain language, aimed at customers rather than engineers",
      ] },
      { h2: "Why the format itself is worth taking seriously", p: "It is tempting to treat a changelog as an afterthought, a quick note bolted onto a release. Teams that take the format seriously tend to get more value from it: a changelog readers trust becomes a place people check before asking support the same question repeatedly, which quietly reduces ticket volume over time. That is a real, if often unmeasured, return on the small effort of publishing consistently, and it is one more reason a public, permanent, well-organised changelog page earns its place separately from an in-app messaging tool built for a different job entirely." },
      { h2: "A simple test to run this week", p: "Ask three customers, or three colleagues in support, whether they know where to find a full history of what your product has shipped this year. If the honest answer is 'not really' or 'somewhere in Intercom, I think', that gap is exactly what a dedicated, public changelog closes, and it usually takes less than a day to set the first version live with your last few months of updates backfilled." },
      { h2: "What success looks like six months in", p: "A working changelog setup shows up in small, quiet ways: fewer support tickets asking whether a feature exists yet, prospects mentioning they read the changelog before a sales call, and voters commenting that their request actually shipped. None of these are dramatic, but together they are exactly the outcome a public, permanent release history is meant to produce, and they are the reason it is worth the modest setup effort." },
      { h2: "Getting started this week", p: "Pick a dedicated changelog tool, backfill the last few months of updates from Intercom's News feed, and publish the first entry alongside your next release. Keep Intercom running exactly as it is for support and in-app messaging. Within a month, you will have a public, searchable release history that Intercom's messaging tools were never built to provide, running quietly alongside the support workflow your team already knows." },
      { table: {
        caption: "Intercom's changelog feature vs. a dedicated tool",
        head: ["Feature", "Intercom News/updates", "Feedlark changelog"],
        rows: [
          ["Public, indexable page", "No", "Yes"],
          ["Tied to feedback board votes", "No", "Yes"],
          ["Automatic voter notification on ship", "No", "Yes"],
          ["Free to use", "Requires Intercom subscription", "Yes, unlimited end-users"],
        ],
      } },
    ],
    takeaways: [
      "Intercom's changelog and news features are built for in-app messaging, not a standalone public changelog.",
      "A dedicated changelog gives you a permanent, indexable page that non-logged-in users can find and browse.",
      "Feedlark ties changelog entries directly to the feature requests and votes that drove them.",
      "You can usually keep Intercom for support and add a dedicated changelog tool alongside it, rather than replacing it.",
    ],
    faqs: [
      { q: "Can I use Intercom as a public changelog?", a: "Intercom's News feature can display updates to logged-in users inside your app, but it isn't designed as a standalone, public, indexable changelog page that anyone can find and browse independently of the product." },
      { q: "Do I need to replace Intercom to get a proper changelog?", a: "No. Most teams keep Intercom for support and messaging and add a dedicated changelog tool like Feedlark alongside it, specifically for the public release history that Intercom's feature set doesn't cover." },
      { q: "What makes a changelog entry useful to customers?", a: "A useful entry is dated, written in plain language, and ideally linked back to the feature request that prompted it. The open [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) standard is a good reference for structuring entries clearly." },
      { q: "Does Feedlark's changelog notify people automatically?", a: "Yes. When a roadmap item marked as shipped is published, everyone who voted for that request receives a notification automatically, closing the feedback loop without any manual follow-up work." },
    ],
  },
];
