import type { BlogPost } from "./blog-types";

export const BLOG_FEATURE_REQUESTS: BlogPost[] = [
  {
    slug: "feature-request-software-guide",
    title: "Feature request software: a practical guide",
    description:
      "Feature request software manages the full idea-to-shipped pipeline. Here is what it does, what to look for, and which tools do it without extra cost.",
    date: "2026-06-24",
    keyword: "feature request software",
    category: "Academy",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "A MacBook with lines of code on its screen on a busy desk",
    readMins: 8,
    blocks: [
      { p: "Feature request software manages one specific workflow. A user has an idea, they submit it, others vote on it, the team evaluates it, builds it, and the user finds out when it ships. Most teams try to run this across Slack, email, a spreadsheet and a project management tool. A dedicated tool does all of it in one place, and that alone removes most of the friction that stops good ideas reaching a roadmap." },
      { h2: "The full feature request pipeline", ul: [
        "Capture: users post ideas on a public board, no account required",
        "Deduplication: similar requests are flagged and merged automatically",
        "Voting: other users upvote the ideas they need too",
        "Triage: the team reviews the board weekly and assigns statuses",
        "Prioritisation: high vote items get promoted to the roadmap",
        "Build: the feature goes into development with a roadmap item attached",
        "Notify: voters receive an automatic message when it ships",
      ] },
      { h2: "Why spreadsheets don't work", p: "The problem with tracking feature requests in a spreadsheet is not data storage, it is signal. A spreadsheet can tell you that 47 people asked for dark mode, but it cannot tell you who those 47 people are, whether they are still active users, or whether three of those requests came from the same person under different email addresses. A proper tool captures all of that and surfaces the highest signal requests rather than just the newest ones. A small SaaS team we spoke to once kept a shared spreadsheet of feature ideas for two years. By the time they moved to a proper board, they found eleven duplicate rows for the same billing export request, submitted by different support agents on different dates, with no way to tell how many actual customers stood behind it. For a routine that avoids that mess entirely, see our guide on [how to track feature requests](/blog/how-to-track-feature-requests) day to day." },
      { h2: "What to look for in feature request software", ul: [
        "No login voting so participation isn't blocked by account creation",
        "Automatic duplicate detection to avoid triaging the same idea repeatedly",
        "Status workflow: Planned, In Progress, Shipped at minimum",
        "Roadmap view that updates automatically when you change a status",
        "Automatic notifications to voters on status changes",
        "Embeddable widget for collecting requests inside your product",
        "Data export so you can leave if you need to",
      ] },
      { p: "The embeddable widget matters more than it sounds. Pairing your board with a [feedback widget for your website](/blog/feedback-widget-for-website) means requests get captured in the exact moment a user notices something is missing, rather than after they have already forgotten about it and moved on." },
      { h2: "Feature request software vs PM software", p: "Project management software like Jira and Linear is optimised for engineering workflows: sprints, tickets, acceptance criteria, velocity tracking. It is designed to help teams deliver. Feature request software is optimised for discovery, capturing what users want most, surfacing the highest priority ideas, and communicating back to users. They are complementary tools rather than substitutes for each other. The best workflows connect them, so a feature request board feeds prioritised items into Jira as tickets once a decision has been made." },
      { h2: "Internal vs public feature boards", p: "A public feature board is open to all users, typically accessible at a URL like feedback.yourproduct.com. An internal board is accessible only to your team or specific user segments, useful for enterprise clients who want a private channel or for teams collecting internal tooling requests. Many products start with a single public board and add private boards for enterprise accounts later. The better tools support both from the same dashboard, so you are not paying for two separate systems." },
      { h2: "How pricing usually works", p: "Most vendors charge per seat, which punishes exactly the behaviour you want to encourage: more teammates reviewing and responding to feedback. Before choosing a tool, read a breakdown like our [Canny pricing explained](/blog/canny-pricing-explained) piece so you know what a seat based model actually costs once your team grows past a handful of people. Feedlark takes the opposite approach and charges a flat fee per workspace instead." },
      { h2: "AI assisted deduplication", p: "As a board grows, the same idea gets posted in many different ways. Add a dark mode, support dark theme, and make the background dark at night are all the same feature request written by three different people. Manual deduplication at scale is exhausting. Some tools now use AI to flag similar requests automatically, letting an admin merge them with a single click. This keeps the board clean without requiring someone to review every new post line by line." },
      { h2: "The notification most teams skip", p: "The most neglected feature in feature request management is the one that closes the loop, notifying users when their request ships. Teams that do this consistently report noticeably higher user satisfaction than those who don't, for the same set of shipped features. Users do not just want features, they want to feel heard. [Nielsen Norman Group's research on continuous discovery](https://www.nngroup.com/articles/discovery-study-guide/) makes a similar point: the value of listening comes from the follow up as much as the initial capture. An automated 'you asked, we built it' email at the moment of shipping costs almost nothing and delivers a disproportionate amount of loyalty." },
      { h2: "Why retention makes the case for investing here", p: "[Bain's research on customer retention](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers) found that a five percent improvement in retention can raise profits by twenty five to ninety five percent depending on the industry. Feature request software will not fix churn on its own, but it removes one common cause of it: users leaving because they felt unheard. A visible board, a working vote count, and a shipped notification are a cheap way to chip away at that risk." },
      { h2: "Choosing between building your own and buying a tool", p: "Some engineering teams consider building a simple internal tool instead of buying one. It is possible, but the real cost shows up later: deduplication logic, notification infrastructure, spam protection, and a public facing UI all need maintenance. Most teams that build their own abandon it within a year once the original engineer moves to another project. Buying a purpose built tool is usually cheaper across an eighteen month horizon." },
      { table: { caption: "Manual tracking compared with a board", head: ["Method", "Visibility", "Duplicate handling", "Prioritisation signal"], rows: [
        ["Spreadsheet and Slack", "Only visible to whoever maintains the file", "Manual, easy to miss", "Guesswork based on who shouted loudest"],
        ["Feature request board", "Public, updated in real time for the whole team", "Automatic flagging with one click merge", "Vote counts show real demand"],
      ] } },
      { h2: "Rolling this out across a team of any size", p: "Introducing a feature request board works best when it replaces old habits rather than sitting alongside them. Turn off the shared spreadsheet, redirect support macros to link the board instead of logging a row, and tell sales the board is now the place a prospect's request gets recorded. The switch takes about a week for most teams, and after that the old channels quietly stop being used because the board is simply less work." },
      { h2: "A short note on accessibility", p: "A public board is often the first thing a new or returning user reads about your product's direction, so it is worth writing status updates and roadmap notes in plain, accessible language. [W3C's guidance on writing for the web](https://www.w3.org/WAI/tips/writing/) is a useful reference here: short sentences, common words, and one idea per paragraph make a board easier to scan for everyone, including users relying on screen readers or translation tools. It costs nothing extra and it widens who can actually use the board you built." },
      { h2: "Getting started with Feedlark", p: "Feedlark covers the full feature request pipeline out of the box, for free. Set up a board in minutes, embed the widget, and link your roadmap. When you mark something as Shipped, the changelog entry is created automatically and every voter gets notified. The free tier has no user caps, so you can [try Feedlark free](/signup) and launch publicly straight away without worrying about hitting a limit in your first week, or compare it first against our list of the [best Canny alternatives](/blog/best-canny-alternatives)." },
    ],
    takeaways: [
      "Feature request software replaces spreadsheets and Slack threads with one visible pipeline from idea to shipped.",
      "Look for no login voting, automatic duplicate detection, and notifications that fire when a status changes to Shipped.",
      "Feature request tools and project management tools solve different problems and work best when paired together.",
      "A flat, seat free pricing model matters once more than a couple of teammates need to triage feedback.",
    ],
    faqs: [
      { q: "What is the difference between feature request software and a roadmap tool?", a: "Feature request software captures and prioritises raw ideas from users, while a roadmap tool displays what has already been decided. Most modern tools, including Feedlark, combine both, so a request can move from vote count to public roadmap without being re-entered anywhere." },
      { q: "Do users need an account to submit a feature request?", a: "No, the better tools allow posting and voting without forcing a signup, since that barrier stops a large share of genuine feedback. Requiring an account only makes sense for private, enterprise only boards." },
      { q: "How much does feature request software cost?", a: "Pricing varies widely, and many tools charge per seat, which gets expensive as more teammates need access. Feedlark charges one flat fee per workspace instead, so adding reviewers does not increase the bill." },
      { q: "Can I run feature request software alongside Jira or Linear?", a: "Yes, and most teams do exactly this. The feedback board handles capture, votes and communication, then confirmed priorities get created as tickets in whichever engineering tool your developers already use." },
    ],
  },
  {
    slug: "how-to-track-feature-requests",
    title: "How to track feature requests properly",
    description:
      "Tracking feature requests in spreadsheets and Slack threads means losing them. Here is a board based system that keeps every idea visible and actioned.",
    date: "2026-06-23",
    keyword: "how to track feature requests",
    category: "Academy",
    schemaType: "HowTo",
    author: "Tom Whitfield, Feedlark co-founder",
    authorBio: "Tom co-founded Feedlark and spends most of his week talking to product teams about how they actually triage feedback.",
    image: "https://images.unsplash.com/photo-1743385779347-1549dabf1320?fm=jpg&q=60&w=1080&auto=format&fit=crop&ixlib=rb-4.1.0",
    imageAlt: "Workflow diagram with product brief and user goals on a project management planning board",
    readMins: 7,
    blocks: [
      { p: "Every product team loses feature requests. They arrive in support tickets, Slack DMs, sales calls, onboarding conversations and user interviews, and then they scatter. A spreadsheet cannot prioritise them. An inbox cannot surface patterns. Here is the system that does, laid out as five steps you can start today." },
      { h2: "Why the spreadsheet fails", p: "A spreadsheet can store requests, but it cannot tell you which ones matter most. It cannot surface the fact that seventeen users all asked for the same thing using different wording. It cannot notify a user when their request ships. It cannot show your users that you are listening. It is a storage mechanism, not a feedback system, and the gap between those two things is where trust is built or lost. One team we heard from tracked requests in a shared document for a year, then discovered during a customer call that a churned account had asked for the same integration four times across four different support tickets, and nobody had ever connected the dots." },
      { h2: "The right system: a public feedback board", p: "A public feedback board is the single source of truth for feature requests. Every channel, support, sales, onboarding, routes requests there. Users vote on ideas they share. The team reviews the board on a regular cadence. The highest voted ideas get promoted to the roadmap. Nothing is lost, nothing is duplicated, and the priority order reflects actual user demand rather than recency or volume. Pairing this with proper [feature request software](/blog/feature-request-software-guide) means the whole pipeline, from first post to shipped notification, runs without manual copying between tools." },
      { h2: "Step 1: create the board and embed the widget", p: "Set up your board at a dedicated URL, feedback.yourproduct.com, and embed the feedback widget inside your product. The widget adds a Share feedback button to every screen, so users can post requests in context, while they are experiencing the thing they want to improve. Our guide to a [feedback widget for your website](/blog/feedback-widget-for-website) covers placement and setup in more detail. This typically generates significantly more feedback than a standalone board alone, because the friction of navigating away is removed." },
      { h2: "Step 2: build the routing habit", p: "When a feature request arrives via support, sales or any other channel, route it to the board. Post it yourself if the user won't, or reply to the channel with a link to the relevant board post so the user can vote. This takes about thirty seconds per request and means the board accumulates signal from every conversation, not just the users proactive enough to find the board themselves." },
      { h2: "Step 3: review and triage weekly", p: "Block an hour each week to review the board. Look at posts above a threshold, say five votes, that haven't been triaged yet. Assign statuses: Under Review for ideas you are considering, Planned for things you have committed to, In Progress for active work. Reply to posts with more detail where relevant. Regular triage keeps the board useful and signals to users that it is actively monitored." },
      { h2: "Step 4: detect and merge duplicates", p: "As the board grows, the same feature gets requested in many ways. Manually checking for duplicates is exhausting on a busy board. Tools with AI assisted deduplication flag similar posts automatically, you review the suggestions and merge with a click. The result is one clean post with all the votes from its duplicates combined, giving you accurate signal rather than fragmented data." },
      { h2: "Step 5: close the loop when you ship", p: "When a feature ships, move it to Shipped. Every user who voted receives an automatic notification: the feature they requested is now live. That moment, between the request and the notification, is where user trust is built. It is the proof that the board is real, not performative. Teams that close the loop consistently see significantly higher board engagement than those that don't, and it pairs naturally with a [changelog tool](/blog/changelog-tool-guide) so the same update also appears publicly for anyone who wasn't watching that specific request." },
      { h2: "Picking a triage cadence that fits your team", p: "Not every team should triage weekly. A small team with a quiet board might only need a monthly pass, while a fast growing product with hundreds of weekly posts needs something closer to daily." },
      { table: { caption: "How the two ends of that spectrum compare", head: ["Cadence", "Best for", "Risk if too slow"], rows: [
        ["Daily", "Large boards with high volume", "Team burns out reviewing every post"],
        ["Weekly", "Most small and mid sized teams", "Minor delay in responding to urgent requests"],
        ["Monthly", "Very small or early stage products", "Board feels abandoned, votes stop accumulating"],
      ] } },
      { h2: "Why users expect a fast response", p: "[HubSpot's research on customer service](https://blog.hubspot.com/service/customer-service-stats) found that over half of service leaders say customers now expect resolution within three hours or less. A feature request is not a support ticket, so the same clock does not apply directly, but the underlying expectation is the same: users notice when nobody is watching. A quick reply that says under review costs seconds and buys weeks of patience." },
      { h2: "Common mistakes teams make when tracking requests", p: "The first mistake is running two systems at once, a board for show and a spreadsheet for the real decisions. Users notice when a board is decorative, and engagement drops fast once they realise their vote does not actually influence anything. The second mistake is triaging only the newest posts instead of the highest voted ones, which means loud, recent requests crowd out older ideas with much stronger demand behind them. The third is skipping the shipped notification because it feels like a small detail. It is the single highest leverage step in the whole process, and skipping it quietly erodes the trust the rest of the system is built to earn." },
      { h2: "Why this connects to retention", p: "Feature request tracking rarely gets framed as a retention tool, but it behaves like one. [Bain's research on customer retention](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers) found that a five percent improvement in retention can raise profits by twenty five to ninety five percent depending on the industry, and unresolved, unacknowledged requests are a quiet but steady source of churn. [Recurly's benchmarking work](https://recurly.com/research/churn-rate-benchmarks/) puts average subscription churn at around 3.27 percent a month, which sounds small until you multiply it across a year of lost customers who each had a specific, fixable reason for leaving." },
      { h2: "Making the system stick after the first month", p: "The system above works, but it only stays working if someone owns it. Assign one person, even a rotating owner, to run the weekly triage and reply to posts. Add a recurring calendar event so the review does not quietly fall off the list when a busy sprint arrives. A board that gets triaged for three weeks and then ignored is worse than no board at all, because it trains users to stop trusting it." },
      { h2: "A quick note on scope", p: "This system works for products of any size, from a two person startup to a team shipping weekly across several products. The steps do not change, only the cadence and who is responsible for running them. Start with the smallest version, one board, one weekly hour, and let the process grow as the volume of requests grows with it." },
      { h2: "What this looks like in Feedlark", p: "Feedlark handles all five steps from one dashboard. The board is public and free for unlimited users. The widget embeds in a single line of code. Statuses update with one click. AI deduplication runs automatically. When you update a status to Shipped, the changelog entry is created and voters are notified without any additional work from your team, and you can see the full workflow for yourself on [Feedlark's signup page](/signup)." },
    ],
    takeaways: [
      "Route every feature request, from support, sales and onboarding, to one public board instead of a spreadsheet.",
      "Triage on a fixed cadence, weekly for most teams, and assign statuses so users see the board is actively monitored.",
      "Merge duplicates so vote counts reflect real demand rather than fragmented, repeated posts.",
      "Always notify voters when a request ships. It is the single highest leverage step in the whole system.",
    ],
    faqs: [
      { q: "How often should I triage a feature request board?", a: "Weekly works for most small and mid sized teams. Boards with very high volume may need daily attention, while a very quiet early stage board can get by with a monthly pass." },
      { q: "What is the biggest mistake teams make when tracking requests?", a: "Running a board for show while decisions are still made in a private spreadsheet. Users notice quickly when their vote does not influence anything, and engagement drops as a result." },
      { q: "Do I need engineering involvement to track feature requests?", a: "No, triage and status updates can be handled entirely by product or support staff. Engineering only gets involved once an item is prioritised and turned into a ticket." },
      { q: "Does tracking feature requests actually reduce churn?", a: "It reduces one specific cause of churn, users feeling unheard, though it will not fix pricing or product fit issues on its own. Combined with regular shipping and notifications, it is a low cost way to build trust." },
    ],
  },
  {
    slug: "feature-request-tracking",
    title: "How to track feature requests without chaos",
    description:
      "Feature requests scattered across Slack, email and support tickets? Here is a simple system to capture, prioritise and act on them with one shared board.",
    date: "2026-06-15",
    keyword: "feature request tracking",
    category: "Academy",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and previously ran feedback operations at two fast growing SaaS teams.",
    image: "https://images.unsplash.com/photo-1732437334226-e96e72272bc4?ixlib=rb-4.1.0&auto=format&fit=crop&w=1080&q=80",
    imageAlt: "A wall covered with colourful sticky notes representing feature tracking, ideas and product planning",
    readMins: 7,
    blocks: [
      { p: "Most teams lose feature requests in DMs, support tickets and meeting notes. A single board fixes that. Here is the workflow, along with why each step earns its place." },
      { h2: "Capture every request on one board", p: "Give users one public board to post ideas. Route requests from support and sales there too, so nothing is lost. The habit that makes this work is small: whenever a request appears anywhere else, the reply includes a link to the board post instead of a private note. Within a few weeks, the board becomes the default place a request lands, and the other channels quietly stop being where decisions get made." },
      { h2: "Why one board beats many channels", p: "Splitting feedback across Slack, a support inbox, sales call notes and a spreadsheet feels organised at first, but it means nobody ever sees the full picture. A request that shows up twice in support and once in a sales call looks like three separate, low priority items instead of one strong signal. A single board turns scattered mentions into one visible vote count, which is the only way prioritisation can be based on evidence rather than whoever spoke last in a meeting." },
      { h2: "Let votes do the prioritising", p: "Instead of guessing, let users upvote. The most requested items rise to the top, giving you a data backed priority list. This matters most when a small, vocal customer keeps asking for something that barely anyone else needs. A public vote count makes it obvious when a request is genuinely popular versus when it is one loud voice repeated in different meetings." },
      { h2: "Respond and set status", p: "Reply as the team, set a status, and the request becomes part of your public roadmap. Users see they were heard. A short reply, even just under review, changes how a request feels to the person who posted it. Silence reads as being ignored. A status, any status, reads as being taken seriously." },
      { h2: "A short anecdote from a growing team", p: "A ten person startup we spoke with used to track requests in a channel called sharp-ideas. It worked fine for the first twenty or so posts, then it became impossible to search, half the messages were reactions rather than requests, and three different teammates were quietly maintaining their own private lists of what they thought mattered most. Moving to a single board took an afternoon, and within a month the team had a ranked list nobody had to argue over, because the votes did the arguing for them." },
      { table: { caption: "Comparing scattered tracking with one board", head: ["Approach", "Where requests live", "How priority gets decided"], rows: [
        ["Slack channel plus support tickets", "Spread across several tools, hard to search", "Whoever remembers the loudest request"],
        ["Spreadsheet maintained by one person", "One file, but only as current as the last update", "Manual judgement, easy to miss patterns"],
        ["Single public board", "One place, votes visible to the whole team", "Vote count reflects actual demand"],
      ] } },
      { h2: "Signs your current tracking has already broken down", p: "There are a few reliable warning signs. Nobody on the team can say, without checking three different tools, how many people asked for a specific feature. The same idea gets raised again in a planning meeting because whoever raised it last time has forgotten it was already logged somewhere. Support agents start keeping their own private notes because they have stopped trusting that requests they log anywhere else will ever be looked at again. Any one of these on its own is a nuisance. All three together mean tracking has quietly stopped working, even if everyone still thinks a system is in place." },
      { h2: "How this differs from a full product feedback loop", p: "Feature request tracking is one part of a wider [product feedback loop](/blog/what-is-a-product-feedback-loop), which also includes interviews, surveys and usage data. A board is the easiest part to set up and the part users see directly, so it is worth getting right first. [Nielsen Norman Group's writing on continuous discovery](https://www.nngroup.com/articles/discovery-study-guide/) makes the case that this kind of lightweight, always on listening works better than periodic, one off research pushes, because it catches problems while they are still small and cheap to fix." },
      { h2: "A simple test for whether your system is working", p: "Ask anyone on the team, without looking anything up, to name the three most requested features right now. If they can answer instantly, the system is working. If they have to check a spreadsheet, scroll a Slack channel and ask a colleague, the tracking exists on paper but not in practice, and it is worth the afternoon it takes to consolidate everything onto one board." },
      { h2: "Handling requests that will never get built", p: "Not every idea belongs on the roadmap, and that is fine as long as the board says so honestly. A status like Not planned, with a short reason attached, is more respectful than silence, because it tells the user their idea was considered rather than lost. Users rarely mind hearing no when the reason is clear. What damages trust is a request that simply sits, unanswered, for months, leaving the person who posted it to guess whether anyone ever read it at all." },
      { h2: "Bringing sales and support into the habit", p: "The teams closest to customers usually generate the most requests, yet they are also the first to give up on a system that feels like extra admin. Keep their part of the workflow tiny: one link to paste into a reply, nothing to fill in, nothing to remember beyond that single habit. The moment logging a request takes more than a few seconds, people quietly stop doing it, and the board slides back into being just one more channel that gets missed." },
      { h2: "Keeping the board honest as it grows", p: "A board that never gets triaged is barely better than no board. Set a light weekly or fortnightly check, even fifteen minutes, to merge duplicates and update statuses on anything that has moved. For a fuller breakdown of how that habit fits into a weekly routine, see our guide on [how to track feature requests](/blog/how-to-track-feature-requests) properly." },
      { h2: "Why this is worth the effort", p: "[Bain's research on customer retention](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers) found that a five percent improvement in retention can raise profits by twenty five to ninety five percent depending on the industry. Feature request tracking will not single handedly move that number, but every unacknowledged request is a small, avoidable reason for a customer to look elsewhere. A board that visibly tracks and responds to requests removes that reason at almost no cost." },
      { h2: "What good tooling adds on top of a board", p: "A basic board solves visibility. Good tooling adds automatic duplicate detection so ten versions of the same idea become one accurate vote count, and automatic notifications so voters hear the moment their request ships, without anyone remembering to email them by hand. Feedlark bundles both into the free plan, alongside a [feedback widget](/blog/feedback-widget-for-website) you can embed directly in your product so requests get captured in the moment, not after the user has already given up and closed the tab." },
      { h2: "Getting started today", p: "You do not need a big rollout plan to start. Create one board, tell your team to route requests there instead of wherever they currently land, and give it two weeks. Compare that to running the same setup through [Feedlark's free plan](/pricing), which adds vote counts, statuses and shipped notifications without any extra manual work." },
    ],
    takeaways: [
      "One public board beats spreading requests across Slack, support tickets and a spreadsheet.",
      "Let votes decide priority so loud, repeated requests don't drown out genuinely popular ones.",
      "Reply and set an honest status on every request, even a simple Not planned, rather than leaving it in silence.",
      "A light, recurring triage habit keeps the board trustworthy as request volume grows.",
    ],
    faqs: [
      { q: "What is the fastest way to start tracking feature requests properly?", a: "Create one public board today and tell your team to link to it whenever a request comes up, instead of noting it privately. The habit matters more than the tool in the first few weeks." },
      { q: "Should every feature request get built eventually?", a: "No, and a board should say so honestly with a status like Not planned and a short reason. Users generally accept a clear no far better than being left without any answer at all." },
      { q: "How do I stop support and sales from ignoring the board?", a: "Keep their part of the process to one small action, usually pasting a link into a reply, with nothing else to remember. Any extra admin steps and people quietly stop using it." },
      { q: "Is a feature request board the same as a full feedback loop?", a: "No, tracking requests is one part of a wider feedback loop that also includes interviews, surveys and usage data. A board is simply the most visible and easiest part to get right first." },
    ],
  },
  {
    slug: "feedback-widget-for-website",
    title: "Add a feedback widget to your website",
    description:
      "A feedback widget lets users vote and suggest ideas from inside your product without signing up. Here is how to add one and what results to expect from it.",
    date: "2026-06-19",
    keyword: "feedback widget for website",
    category: "Academy",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1668854041298-4b8bbc9fbce0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "A clean, modern graphical user interface showing a website feedback widget",
    readMins: 8,
    blocks: [
      { p: "A feedback widget is a small embedded button, usually labelled Share feedback or Suggest a feature, that opens a feedback form directly inside your product. Instead of navigating away to an external board, users can post and vote without leaving the page they are on. That friction reduction matters more than most teams expect, and it is the difference between hearing from a handful of vocal users and hearing from a much wider slice of your actual customer base." },
      { h2: "Why in-product feedback gets more responses", p: "The moment a user experiences something they wish worked differently is exactly when they are most motivated to report it. If they have to stop what they are doing, navigate to a separate feedback site, create an account and find the right board, most of them won't. An embedded widget captures that moment in real time. You do not lose feedback to context switching, and you get significantly more submissions than a standalone URL alone." },
      { h2: "What a good feedback widget does", ul: [
        "Opens inline or in a slide over without navigating away from the current page",
        "Shows existing posts so users can upvote ideas already submitted",
        "Accepts new posts without requiring account creation",
        "Pre-populates the user's name and email if they're already logged in",
        "Submits to the same board as your public feedback page",
        "Loads fast and doesn't interfere with page performance",
      ] },
      { h2: "How to install a feedback widget", p: "Most modern feedback tools provide a JavaScript snippet you paste into your site's head or body. In Feedlark, you copy a single script tag from the dashboard and add it to your product's layout file. The widget appears immediately, styled to a neutral default that works with most designs. You can customise the button colour and position from the dashboard without touching code again. It also connects to the same underlying [feature request software](/blog/feature-request-software-guide) that powers your public board, so nothing needs to be set up twice." },
      { h2: "Where to place the widget", p: "The most common placement is the bottom right corner. It has become a convention users recognise, similar to live chat buttons. Avoid the top right, which competes with navigation elements, and avoid the left side, which users associate with menus and navigation drawers. For web apps, a persistent button on every page works well. For marketing sites, placing it only on the product or feature pages keeps submissions relevant." },
      { h2: "Voting inside the widget", p: "The widget shouldn't just accept new posts, it should show existing ones so users can upvote without duplicating. When a user opens the widget and sees ideas already submitted that they agree with, they vote on those instead of posting the same ideas again. That keeps the board clean and concentrates votes on the highest signal requests rather than scattering them across duplicates." },
      { h2: "No-login voting in the widget", p: "Requiring users to create an account before voting in the widget kills participation. Most users are logged into your product already, so the widget can pre-populate their identity automatically. For users who aren't logged in, letting them vote with just an email address, or even anonymously, keeps the barrier low. Anonymous votes still contribute to the vote count and surface signal even without follow-up notification capability." },
      { h2: "What to expect in the first week", p: "A feedback widget typically generates three to five times more submissions than a linked feedback URL alone. Expect a spike in the first few days after launch, users have been sitting on ideas and the widget gives them an easy outlet. After the initial wave, submissions settle into a steady rate that reflects your active user base. A product with 500 daily active users should expect five to fifteen new posts or votes per day from the widget." },
      { h2: "A short story about a widget launch", p: "A small team building a scheduling tool added a feedback widget the same week they redesigned their onboarding flow. Within three days they had forty new posts, more than the public board had collected in its first two months combined. Several of them pointed at the same confusing step in the new onboarding, something none of the team had noticed internally because they were too familiar with the product to see it the way a new user did. That single week of feedback reshaped their next sprint." },
      { h2: "Widget versus standalone board", p: "It helps to think of the widget and the public board as the same data with two entry points rather than two separate systems. The board works well for users who already know they have an idea and are willing to seek out a place to share it. The widget works for the much larger group who notice something in passing but would never go looking for a feedback page on their own. For a deeper look at other embedded patterns beyond this one widget, see our [in-app user feedback guide](/blog/in-app-user-feedback-guide)." },
      { table: { caption: "Comparing the two entry points", head: ["Entry point", "Best for", "Typical volume"], rows: [
        ["Standalone public board", "Motivated users actively looking to share ideas", "Lower, steady volume"],
        ["Embedded in-product widget", "Users noticing something in the moment", "Higher, especially just after launch"],
      ] } },
      { h2: "How this fits into a wider feedback strategy", p: "A widget is one input into a larger [feedback management](/blog/feedback-management-software-explained) setup, alongside support tickets, sales calls and direct interviews. On its own it captures spontaneous, in the moment reactions. Paired with a regular review habit, described in our guide on [how to track feature requests](/blog/how-to-track-feature-requests), it becomes one reliable channel among several rather than a novelty button nobody checks." },
      { h2: "Why accessible design matters for the widget", p: "A feedback widget should be usable by everyone, including people relying on a keyboard or a screen reader rather than a mouse. [W3C's guidance on writing for the web](https://www.w3.org/WAI/tips/writing/) also applies to the short labels and prompts inside a widget: plain words, short instructions, and a clear button label beat clever copy every time. A widget that only works for mouse users with perfect eyesight quietly excludes a meaningful share of your audience." },
      { h2: "Why the volume increase matters for retention", p: "More submissions is not just a vanity number. [Zendesk's CX Trends research](https://cxtrends.zendesk.com/) found that sixty three percent of customers say demand for transparency from companies has risen, and that eighty five percent of customer experience leaders say customers actively drop brands over unresolved issues. A widget that surfaces problems earlier, while they are still small, gives a team more chances to fix things before a frustrated user gives up and leaves for a competitor." },
      { h2: "Common widget mistakes to avoid", p: "The most common mistake is hiding the widget behind a settings menu or a help centre link, which defeats the purpose of reducing friction. The second is forcing an account or a lengthy form before a user can submit anything, which cuts submissions dramatically. The third is launching the widget and never checking what comes through it, which quickly becomes obvious to users and discourages further use." },
      { h2: "When a widget is not the right first step", p: "If your product has almost no active users yet, a widget alone will not generate much signal, and it is worth talking to early customers directly first. Once you have a steady stream of daily users, the widget starts paying for itself, catching the small frustrations nobody would ever email you about." },
      { h2: "Getting started with Feedlark's widget", p: "The Feedlark widget installs in under five minutes. Copy the script tag from your dashboard settings, paste it into your layout file, and the button appears on every page automatically. You can adjust the position, colour and button label from the dashboard, and you can [try it on the free plan](/signup) before deciding whether to invite your whole team. All submissions flow to the same board as your public feedback page, so votes are combined and the board stays unified." },
    ],
    takeaways: [
      "A feedback widget captures ideas at the exact moment a user notices something, rather than after they have moved on.",
      "Keep the widget frictionless: no forced account creation, and it should show existing posts so users vote instead of duplicating.",
      "Expect a first week spike in submissions, then a steady rate tied to your active user base.",
      "Treat the widget as one entry point into the same board and feedback strategy, not a separate system to manage.",
    ],
    faqs: [
      { q: "Where should I place a feedback widget on my site?", a: "The bottom right corner is the convention most users already recognise from live chat tools. Avoid the top right, since it competes with navigation, and the left side, which reads as a menu." },
      { q: "Will a feedback widget slow down my website?", a: "A well built widget loads asynchronously and adds negligible weight to a page. Feedlark's script is designed to load after the main content, so it does not affect page speed." },
      { q: "Should the widget require users to log in before voting?", a: "No, requiring an account before voting significantly reduces participation. Pre-filling identity for logged in users and allowing lightweight anonymous votes for everyone else works best." },
      { q: "How many submissions should I expect from a widget?", a: "Most teams see three to five times more submissions than a linked, standalone board alone. A product with 500 daily active users typically sees five to fifteen new posts or votes a day." },
    ],
  },
  {
    slug: "feature-request-board-guide",
    title: "Feature request board: what to include and launch",
    description:
      "A feature request board turns scattered ideas into one ranked list. Here is what belongs on it, how to launch one, and how to keep it useful for users.",
    date: "2026-07-02",
    keyword: "feature request board",
    category: "Academy",
    author: "Feedlark Team",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "A product team reviewing a feature request board on a laptop screen while discussing which ideas to prioritise",
    readMins: 7,
    blocks: [
      { p: "A feature request board is a public page where users post product ideas, vote on the ones they want most, and watch a status change as the team responds. It is not a suggestion box that disappears into an inbox. It is a live, visible list that anyone can check at any time to see what has been asked for, what is planned, and what has already shipped. If you are searching for this exact phrase, you almost certainly want to launch one, not just read about the idea, so this guide sticks to what actually belongs on a board and how to get it live." },
      { h2: "What belongs on a feature request board", p: "A board works when every post follows the same simple shape. At minimum, each entry needs a short title, a longer description of the problem or idea, a vote count, and a status. Anyone browsing the board should be able to scan titles in seconds and open the ones that matter to them for more detail. Categories or tags help once the board grows past a few dozen posts, letting users filter by area of the product instead of scrolling through everything." },
      { h2: "The core fields every post needs", ul: [
        "A clear, specific title, not a vague one",
        "A short description explaining the problem the user is trying to solve",
        "A vote button, visible without needing to open the post",
        "A status: something like Under Review, Planned, In Progress, or Shipped",
        "A comment thread so the team and other users can ask questions",
        "An author name or anonymous label, so duplicate voices are easy to spot",
      ] },
      { h2: "What doesn't belong on a board", p: "Bug reports usually do not belong on a feature request board, even though users often post them there anyway. A bug is a defect in something that already exists, while a feature request is a new capability that does not exist yet. Mixing the two makes voting meaningless, since nobody wants to vote against fixing a bug, and it clutters the board with items that will never compete fairly for prioritisation against genuine feature ideas. Most teams solve this by triaging bug reports off the board within a day of them appearing, replying with a quick note and moving the conversation to a support channel instead." },
      { h2: "Choosing a structure before you launch", p: "Decide early whether you want one board or several. A single, unified board works for most products, especially early on, because it keeps all votes in one place and avoids splitting attention. Larger products with genuinely distinct audiences, for example a mobile app and a web dashboard aimed at different users, sometimes benefit from separate boards. When in doubt, start with one board. Splitting later is easy. Merging two established boards with existing votes is not." },
      { h2: "How to launch a feature request board in a day", p: "Launching does not need a big project. Pick a tool, set up your board at a clear URL such as feedback.yourproduct.com, and define three or four starting statuses. Seed the board with five to ten ideas you already know users want, drawn from support tickets or sales notes, so it does not look empty on day one. Announce it in your product, your changelog, and a short email to existing users, then leave it open for a week before doing your first proper triage pass." },
      { h2: "Setting your first statuses and workflow", p: "Keep the initial status list short. Under Review, Planned, In Progress, and Shipped cover almost every situation a small team will face in the first few months. Resist the urge to add a dozen granular statuses before you have any real data on how requests actually flow through your process. You can always add more later once a genuine gap in the workflow appears." },
      { h2: "A short story about a slow start", p: "A three person tools startup launched a board with zero seeded posts and no announcement beyond a small link in their footer. Six weeks later it had four posts, all from the same user. They then seeded it with eight ideas pulled from old support tickets and sent one email to their user list. Within ten days the board had sixty votes across twenty two posts, and the same product had a genuinely useful priority list for the first time. The board itself had not changed. The launch had." },
      { table: { caption: "Comparing a bare idea list with a full board", head: ["Setup", "What it shows", "What it is missing"], rows: [
        ["Simple public idea list", "Titles and rough descriptions", "No votes, no statuses, no way to see demand"],
        ["Full feature request board", "Titles, votes, statuses, comments, categories", "Nothing, this is the complete pipeline"],
      ] } },
      { h2: "Keeping the board honest after launch", p: "A board only stays useful if statuses move. A post stuck on Under Review for six months looks abandoned even if the team is genuinely still considering it. Set a habit of reviewing untouched posts every few weeks and either advancing the status or replying with an honest update. For the fuller weekly routine this fits into, see our guide on [how to track feature requests](/blog/how-to-track-feature-requests) once the board itself is live." },
      { h2: "Why a board beats occasional research sprints", p: "[Nielsen Norman Group's writing on continuous discovery](https://www.nngroup.com/articles/discovery-study-guide/) argues that ongoing, lightweight listening beats periodic, big research pushes, because problems get caught while they are still small and cheap to fix. A feature request board is the simplest version of that idea in practice. It runs constantly in the background, asks nothing extra of your team between triage sessions, and still surfaces the same kind of signal a quarterly research sprint would take weeks to gather." },
      { h2: "Why demand signal matters more than opinions", p: "[Bain's research on customer retention](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers) found that a five percent improvement in retention can raise profits by twenty five to ninety five percent depending on the industry, and a board is one of the cheapest ways to find out which fixes would actually move that number. A vote count replaces internal debate about what customers probably want with an actual, visible ranking of what they have said they want. Teams that argue in meetings about priority usually find the argument disappears once a board has been running for a month." },
      { h2: "Common launch mistakes to avoid", p: "The most common mistake is launching a board with no starting content and no announcement, then concluding a few weeks later that users don't want to give feedback. The second is over-engineering the status workflow before a single post has moved through it. The third is treating the board as a one-time project rather than an ongoing habit, which quietly turns it back into the same dead inbox it was meant to replace." },
      { h2: "Pairing the board with an embedded widget", p: "A standalone board captures feedback from users motivated enough to seek it out. Pairing it with a [feedback widget for your website](/blog/feedback-widget-for-website) captures the much larger group who notice something in the moment but would never go looking for a separate page. Most teams that add a widget after launch see submissions rise noticeably within the first week, simply because the barrier to posting has almost disappeared." },
      { h2: "How a board fits next to your roadmap", p: "Once a board is running, the highest voted, triaged items typically graduate onto a public roadmap. Our guide on [visual roadmaps](/blog/visual-roadmap) covers how to present that next stage once ideas move past the board. Keeping the two connected, so a promoted board post automatically becomes a roadmap card, avoids re-entering the same idea twice." },
      { h2: "Getting started with Feedlark", p: "Feedlark gives you an unlimited free feature request board with no cap on votes, posts or users. Set up your board, seed it with a handful of known requests, and [try Feedlark free](/signup) to see votes, statuses and shipped notifications working together from day one. If you are weighing it against other tools first, our breakdown of the [best free roadmap tools](/blog/best-free-roadmap-tools) covers how boards and roadmaps compare across the market." },
    ],
    takeaways: [
      "A feature request board needs a title, description, vote count and status on every post, nothing more complicated to start.",
      "Seed a new board with five to ten known requests and announce it. An empty, silent board rarely attracts votes on its own.",
      "Keep bug reports off the board and start with a short status list: Under Review, Planned, In Progress, Shipped.",
      "A board only stays useful if statuses keep moving, so build a recurring habit of reviewing untouched posts.",
    ],
    faqs: [
      { q: "What is the difference between a feature request board and a roadmap?", a: "A board is where ideas are captured, voted on and triaged. A roadmap shows the subset of ideas the team has already committed to building, usually pulled directly from the board's highest voted, planned items." },
      { q: "Should bug reports go on a feature request board?", a: "No, bugs are defects in something that already exists, while feature requests are new ideas. Mixing them makes voting meaningless and clutters the board, so most teams redirect bug reports to a support channel instead." },
      { q: "How many posts should a feature request board have before launch?", a: "Seed it with five to ten ideas drawn from support tickets or sales notes before announcing it. A completely empty board rarely attracts its first votes on its own." },
      { q: "Is a free feature request board actually enough for a growing product?", a: "Yes for most teams. The core requirements, titles, votes, statuses and comments, do not change as a product grows, and tools like Feedlark support unlimited users and posts on the free plan." },
    ],
  },
];
