import type { BlogPost } from "./blog-types";

export const BLOG_WORKFLOW_GUIDES: BlogPost[] = [
  {
    slug: "feature-request-prioritization-framework",
    title: "Feature request prioritization: RICE vs ICE",
    description:
      "How to prioritize a growing feature request backlog with the RICE and ICE frameworks, using vote counts as a real reach signal instead of guesswork.",
    date: "2026-07-27",
    keyword: "feature prioritization framework",
    category: "Academy",
    author: "Feedlark Team",
    authorBio: "The Feedlark team builds and maintains the feedback, roadmap and changelog platform referenced in this guide.",
    image: "https://images.unsplash.com/photo-1532622785990-d2c36a76f5a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Two people mapping out priorities on a whiteboard",
    readMins: 7,
    takeaways: [
      "RICE (Reach, Impact, Confidence, Effort) and ICE (Impact, Confidence, Ease) are the two most common lightweight scoring frameworks for feature backlogs.",
      "The single biggest source of bad prioritization is a made-up Reach score. Vote counts on a public feedback board are a real, defensible number instead of a guess.",
      "ICE is faster to run but easier to game with optimism bias; RICE takes longer but forces a Reach estimate that's harder to fudge.",
      "Neither framework replaces judgment. Use the score to rank candidates, then sanity-check the top of the list against strategy before committing engineering time.",
    ],
    blocks: [
      { p: "Every product team eventually hits the same wall: more feature requests than engineering hours, and no shared language for deciding what goes first. Two scoring frameworks, RICE and ICE, exist to turn that argument into a spreadsheet instead of a shouting match. Neither is complicated, and neither works well without decent input data, which is exactly where most teams quietly go wrong." },
      { h2: "RICE: Reach, Impact, Confidence, Effort", p: "RICE scores each request on four factors and divides to get a single number: (Reach x Impact x Confidence) / Effort. Reach is how many users a change touches in a given period. Impact is a rough multiplier (0.25 for minimal, up to 3 for massive). Confidence is a percentage reflecting how sure you are about the other three numbers. Effort is person-months of work. The framework was popularized by Intercom specifically because Reach forces you to separate 'a loud customer wants this' from 'a lot of customers want this.'" },
      { h2: "ICE: Impact, Confidence, Ease", p: "ICE drops Reach and multiplies three 1-10 scores: Impact, Confidence, Ease. It's faster to fill in during a triage meeting because there's no separate reach estimate to research, but that speed is also its weakness. Without a Reach number, Impact scores tend to reflect whoever argued most persuasively in the room rather than actual demand." },
      { table: { caption: "RICE vs ICE at a glance", head: ["Factor", "RICE", "ICE"], rows: [
        ["Formula", "(Reach x Impact x Confidence) / Effort", "Impact x Confidence x Ease"],
        ["Time to score one item", "5-10 minutes with real data", "1-2 minutes"],
        ["Needs a reach estimate", "Yes, explicitly", "No, folded into Impact"],
        ["Easiest to game", "Confidence and Effort", "Impact"],
        ["Best fit", "Backlogs with usage/vote data available", "Fast early-stage triage"],
      ] } },
      { h2: "Where the Reach number should actually come from", p: "Most teams estimate Reach from memory or a quick guess: 'probably a lot of people want this.' That's the weak point in the entire exercise. If requests live on a public [feature request board](/blog/feature-request-board-what-to-include) with voting, Reach stops being a guess: it's the vote count, filtered to your actual customer base rather than anonymous internet traffic. A request with 40 votes from paying accounts is a materially different Reach number than one with 3 votes from trial users, and that distinction is invisible if requests arrive as scattered Slack messages and support tickets instead of a single board." },
      { quote: { text: "The teams who prioritize well aren't the ones with the fanciest scoring spreadsheet. They're the ones who made it cheap to collect real demand signal in one place, so the spreadsheet has something honest to work with.", cite: "Feedlark Team" } },
      { h2: "A simple decision rule for picking between them", ul: [
        "Backlog under 20 items and you triage weekly? Use ICE, it's fast enough to redo every sprint.",
        "Backlog is large, cross-functional, or reviewed quarterly? Use RICE, the extra rigor pays off at that scale.",
        "Either framework, without real Reach or vote data, is closer to a priority-flavored guess than a real score. Fix data collection before optimizing the formula.",
        "Re-score on a cadence, not once. A request that scored low six months ago can jump the queue once votes accumulate.",
      ] },
      { h2: "Common mistakes that quietly break both frameworks", p: "The most common failure is scoring Confidence generously to justify a decision you'd already made. Be stricter than feels comfortable: if you're relying on a single customer conversation, that's 50% confidence, not 90%. The second common mistake is treating the final score as a ranking to follow blindly rather than a starting point. A request that scores lower but ships a strategic bet (a new integration that unlocks a whole segment) can still be worth pulling forward. The framework should inform the conversation, not replace it." },
    ],
    faqs: [
      { q: "Is RICE or ICE better for feature prioritization?", a: "RICE is more rigorous because it forces an explicit Reach estimate, which is usually the number teams are most tempted to fudge. ICE is faster and works well for small, frequently-reviewed backlogs where speed matters more than precision." },
      { q: "Where should the Reach number in RICE come from?", a: "The strongest source is real vote or usage data, for example vote counts on a public feedback board, rather than a guess. This turns Reach from an opinion into a number you can defend to stakeholders." },
      { q: "How often should a feature backlog be re-scored?", a: "Whenever new demand signal arrives, such as a batch of new votes on a request, or at a minimum every planning cycle. A static score from months ago stops reflecting current reality." },
      { q: "Can prioritization frameworks replace product judgment?", a: "No. RICE and ICE rank candidates using the inputs you give them, but strategic bets, technical debt, and platform investments often don't score well on demand alone and still need a human call." },
    ],
  },
  {
    slug: "reduce-duplicate-feature-requests",
    title: "How to reduce duplicate feature requests",
    description:
      "Duplicate feature requests fragment your vote counts and hide real demand. Here's how AI-assisted duplicate detection and a few workflow habits fix it.",
    date: "2026-07-27",
    keyword: "duplicate feature request detection",
    category: "Academy",
    author: "Feedlark Team",
    authorBio: "The Feedlark team builds and maintains the feedback, roadmap and changelog platform referenced in this guide.",
    image: "https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Code and data on a computer monitor, representing automated duplicate matching",
    readMins: 6,
    takeaways: [
      "Duplicate requests are the single biggest reason vote counts understate real demand: the same idea gets split across three or four separate posts.",
      "Manual duplicate-checking doesn't scale past a few dozen open requests. Teams either stop checking or spend hours a week on it.",
      "AI-assisted duplicate detection matches requests on meaning, not exact wording, catching the paraphrased versions a keyword search misses.",
      "A clear merge policy (who merges, how voters are told, what happens to their votes) matters as much as the detection technology itself.",
    ],
    blocks: [
      { p: "Open any long-running feedback board and you'll find the same pattern: 'dark mode', 'add a night theme', 'option to switch to dark UI', and 'please darker colors' sitting as four separate posts with three votes each, when it's really one 12-vote request. Duplicates don't just clutter a board, they actively hide which features customers want most, because demand gets split instead of counted." },
      { h2: "Why duplicates happen even on a well-run board", p: "Customers don't search before posting, and they shouldn't have to guess the exact phrasing someone used six months earlier. 'Export to CSV', 'download my data', and 'let me get a spreadsheet of this' are the same request in three different vocabularies. A keyword search for 'export' misses the other two entirely, which is why manual dedup, scanning titles for similar words, catches maybe half of the actual duplicates on a busy board." },
      { h2: "What AI-assisted duplicate detection actually does", p: "Rather than matching on exact words, semantic duplicate detection compares the meaning of a new post against existing open requests, so 'download my data' and 'export to CSV' get flagged as likely duplicates even with zero shared vocabulary. [Feedlark](/) runs this check automatically when a request is submitted, surfacing the closest existing matches to the team (or the submitter) before a genuine duplicate goes live as a separate post." },
      { table: { caption: "Manual vs AI-assisted duplicate detection", head: ["", "Manual review", "AI-assisted detection"], rows: [
        ["Catches exact-wording duplicates", "Yes", "Yes"],
        ["Catches paraphrased duplicates", "Inconsistent, depends on reviewer memory", "Yes, matches on meaning"],
        ["Scales past 50 open requests", "No, becomes a part-time job", "Yes, runs on every submission"],
        ["Speed", "Minutes to hours per batch", "Instant, at submission time"],
      ] } },
      { h2: "A merge policy that keeps votes honest", ul: [
        "Decide who can merge: usually a PM or admin, not open to any voter, to avoid accidental or bad-faith merges.",
        "When two requests merge, combine the vote counts and notify voters on both threads so nobody's vote silently disappears.",
        "Keep the original wording of the more popular post as the canonical title; it's usually the clearer phrasing, which is part of why it attracted more votes.",
        "Merge early. A duplicate caught at 2 votes is a quick fix; the same duplicate caught at 40 votes on each side means an awkward retroactive merge and voter confusion.",
      ] },
      { quote: { text: "The cost of an unmerged duplicate isn't clutter, it's a wrong prioritization call. If your actual top request is split across three posts averaging 8 votes each, it looks like a mid-priority nice-to-have instead of the 24-vote request it really is.", cite: "Feedlark Team" } },
      { h2: "Getting started without a big cleanup project", p: "You don't need to audit your entire historical backlog in one sitting. Start by turning on duplicate detection for new submissions so the problem stops growing, then merge the handful of obvious existing duplicates you already know about. A full historical sweep can happen gradually, prioritizing your highest-traffic board first." },
    ],
    faqs: [
      { q: "How do duplicate feature requests affect prioritization?", a: "They split demand for the same underlying idea across multiple posts, so each individual post looks lower-priority than the combined demand actually is. This is one of the most common causes of a team missing its own most-requested feature." },
      { q: "Can AI reliably detect duplicate feature requests?", a: "Semantic matching, comparing meaning rather than exact wording, catches paraphrased duplicates that keyword search misses, and is a strong first pass. A human should still confirm before merging, since some requests are similar but not actually the same ask." },
      { q: "What happens to votes when two requests are merged?", a: "The vote counts should combine, and voters on both original posts should be notified of the merge so they know their vote still counts and can track the combined request going forward." },
      { q: "How often should a feedback board be checked for duplicates?", a: "Ideally at submission time, via automated detection, rather than in a periodic cleanup pass. Catching a duplicate early avoids the harder problem of merging two established posts with their own vote histories." },
    ],
  },
  {
    slug: "beta-tester-feedback-guide",
    title: "Beta tester feedback: how to collect it well",
    description:
      "A practical setup for collecting, organizing and acting on beta tester feedback, so early signal doesn't get lost in scattered Slack messages and emails.",
    date: "2026-07-27",
    keyword: "beta feedback tool",
    category: "Academy",
    author: "Feedlark Team",
    authorBio: "The Feedlark team builds and maintains the feedback, roadmap and changelog platform referenced in this guide.",
    image: "https://images.unsplash.com/photo-1551651653-c5186a1fbba2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Mobile app interface being reviewed on a smartphone",
    readMins: 6,
    takeaways: [
      "Beta feedback usually arrives scattered across Slack, email and support tickets, which makes it nearly impossible to see which issues multiple testers actually hit.",
      "A private, invite-only feedback board keeps beta signal organized and voteable without exposing an unreleased feature to your whole customer base.",
      "Tagging feedback by build or version number is what turns beta feedback into a usable regression trail instead of a pile of one-off comments.",
      "Closing the loop with beta testers when their bug or note is fixed measurably improves how much feedback you get from that cohort in future betas.",
    ],
    blocks: [
      { p: "Beta programs generate some of the highest-quality feedback a product team gets, testers are engaged, motivated, and looking closely, but that value gets lost fast if the feedback lands in six different Slack threads and nobody's job is to consolidate it. The fix isn't a bigger beta program, it's a better collection setup." },
      { h2: "Why scattered channels quietly waste beta signal", p: "When three testers independently hit the same bug through email, a Discord channel, and a support ticket, that's a strong signal, three independent confirmations. But if nobody connects those three reports, each looks like a one-off. A private feedback board solves this by giving every tester the same place to post, so duplicate reports become visible vote counts on one item instead of three disconnected complaints." },
      { h2: "Setting up a private beta feedback board", ul: [
        "Make the board private and invite-only so unreleased features stay off your public roadmap and search index.",
        "Ask testers to tag feedback with the build or version number they were on; this turns a pile of comments into a searchable regression trail.",
        "Keep the submission bar low: a title and one sentence is enough. Testers who have to fill out a long form submit less.",
        "Let testers vote on existing reports instead of only filing new ones. A 'me too' vote on an existing bug is more useful than a fourth near-duplicate report.",
      ] },
      { table: { caption: "Channels for beta feedback compared", head: ["Channel", "Searchable", "Voteable", "Shows duplicate reports"], rows: [
        ["Slack/Discord", "Poorly, scrolls out of view", "No", "No, buried in separate messages"],
        ["Email", "No", "No", "No"],
        ["Support tickets", "Yes, but siloed from product view", "No", "Only if manually cross-referenced"],
        ["Private feedback board", "Yes", "Yes", "Yes, visible as vote counts"],
      ] } },
      { quote: { text: "The single biggest change we made to our beta process wasn't recruiting more testers, it was giving the ones we had one place to put feedback instead of five. Reports we'd have missed as isolated Slack messages became obvious once they showed up as the same item with four votes.", cite: "Feedlark Team" } },
      { h2: "Closing the loop matters more in beta than anywhere else", p: "Beta testers are volunteering scrutiny they don't have to give. When a reported bug gets fixed or a suggestion ships, notify the specific people who flagged it, not just a general release note. That direct acknowledgment is what keeps a beta cohort engaged across multiple rounds instead of tapering off after the first one. A board that auto-notifies voters when a linked item ships, the same mechanic used for a public roadmap, works just as well in a private beta context." },
      { h2: "Graduating beta feedback into the main backlog", p: "When a beta wraps, don't let its board become an orphaned archive. Move confirmed bugs into your regular tracker, and for feature suggestions with real traction, merge or link them into your public feedback board so the momentum they built during beta carries forward instead of resetting to zero." },
    ],
    faqs: [
      { q: "Should beta feedback be public or private?", a: "Private and invite-only is usually right, since beta features often aren't ready for a general audience and shouldn't appear on a public roadmap or be indexed by search engines. Confirmed items can graduate to a public board once the feature ships." },
      { q: "How do you avoid losing beta feedback across Slack, email and tickets?", a: "Consolidate to one board that every tester uses, and treat other channels as intake points that get manually logged there rather than as the system of record. Tagging by build/version number also makes the collected feedback far more useful for regression tracking." },
      { q: "Does closing the loop with beta testers actually matter?", a: "Yes. Beta testers who see their specific report acknowledged or fixed are meaningfully more likely to participate in the next round. Testers who never hear back tend to stop reporting." },
      { q: "What's the minimum setup needed to collect beta feedback well?", a: "A private board where testers can post, vote on existing reports, and tag by build number, plus a habit of notifying reporters when their item is addressed. It doesn't need to be more complex than that to work." },
    ],
  },
  {
    slug: "product-roadmap-examples",
    title: "Product roadmap examples worth learning from",
    description:
      "What separates a roadmap customers actually check from one they ignore, illustrated with concrete public roadmap examples and the patterns behind them.",
    date: "2026-07-27",
    keyword: "product roadmap examples",
    category: "Academy",
    author: "Feedlark Team",
    authorBio: "The Feedlark team builds and maintains the feedback, roadmap and changelog platform referenced in this guide.",
    image: "https://images.unsplash.com/photo-1503551723145-6c040742065b-v2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Sticky notes organized on a board representing roadmap planning",
    readMins: 7,
    takeaways: [
      "The best public roadmaps share a small set of traits: a handful of clear statuses, plain-language items, and a visible link back to customer votes.",
      "A roadmap with 40 vague items and no status column reads as noise; customers stop checking it within a week.",
      "Linking roadmap items to the votes and requests behind them is what makes a roadmap feel earned rather than arbitrary.",
      "A roadmap that never updates is worse than no roadmap at all, since it signals the team stopped listening.",
    ],
    blocks: [
      { p: "'Show me a good product roadmap' is a harder ask than it sounds, because most public examples out there are either a vague marketing timeline or an overwhelming wall of Jira tickets. Neither is what customers actually want to see. The roadmaps that work share a specific, repeatable structure, and it's worth breaking down what that structure is before building your own." },
      { h2: "The three-column pattern almost every good roadmap uses", p: "Planned, In Progress, and Shipped (sometimes with a fourth 'Under Review' column for triage) is the structure you'll find on the roadmaps people actually bookmark. It's simple enough to scan in ten seconds and specific enough to answer the two questions every visitor has: is my request being worked on, and did anything I asked for already ship. Anything more granular than this, custom statuses for every internal stage of your process, tends to confuse external visitors who don't know your workflow." },
      { table: { caption: "What separates a roadmap people check from one they ignore", head: ["Trait", "Roadmap people check", "Roadmap people ignore"], rows: [
        ["Item wording", "Plain language: 'Dark mode'", "Internal jargon: 'THEME-implement dark palette tokens'"],
        ["Status clarity", "3-4 statuses, clearly defined", "Custom internal statuses, unclear meaning"],
        ["Link to demand", "Shows vote count or request behind each item", "No visible connection to customer input"],
        ["Update cadence", "Moves items regularly as work progresses", "Static for months at a time"],
        ["Item count", "Focused list of active priorities", "40+ items, no sense of what's actually next"],
      ] } },
      { h2: "Why linking votes to roadmap items changes how it reads", p: "A roadmap item that just says 'Bulk export' reads as a decision made in a vacuum. The same item showing '34 votes' next to it reads as a decision earned from listening. This single detail, whether roadmap items visibly connect back to the [feature requests](/blog/how-to-track-feature-requests) and votes that drove them, is the biggest difference between a roadmap that builds trust and one that feels arbitrary, even when the underlying prioritization process is identical." },
      { quote: { text: "Customers don't expect every request to ship. What they're actually checking for is whether the team is listening at all. A roadmap that shows vote counts and moves items over time answers that question without you having to say a word about it.", cite: "Feedlark Team" } },
      { h2: "The failure mode: a roadmap that never changes", p: "A stale roadmap is worse than none, because it actively signals neglect. If 'In Progress' still shows the same three items it showed four months ago, visitors reasonably conclude the team stopped shipping, or stopped updating the page, either of which erodes trust. Treat roadmap maintenance as a five-minute weekly habit: move what shipped to Shipped, start what's actually started, and it stays credible with almost no ongoing effort." },
      { h2: "Building one without overengineering it", ul: [
        "Start with three statuses (Planned, In Progress, Shipped). Add a fourth only if you have a genuine triage stage worth showing publicly.",
        "Pull items directly from your feedback board's top-voted requests rather than writing a separate internal roadmap and hoping they line up.",
        "Show vote counts next to each item if your tool supports it; it's a small addition with an outsized trust effect.",
        "Update it weekly, even if the update is just moving one item. Consistency matters more than frequency.",
      ] },
    ],
    faqs: [
      { q: "What makes a product roadmap example good?", a: "A small number of clear statuses, plain-language item names, a visible link to the customer votes or requests behind each item, and regular updates. Complexity and item count both work against readability." },
      { q: "How many statuses should a public roadmap have?", a: "Three (Planned, In Progress, Shipped) covers most cases. A fourth status for early triage can work if it genuinely reflects a stage customers care about, but internal-only statuses tend to confuse external visitors." },
      { q: "Should a roadmap show vote counts?", a: "Yes, when possible. Showing the demand behind an item makes prioritization feel earned rather than arbitrary, and it's one of the highest-impact, lowest-effort additions a public roadmap can make." },
      { q: "How often should a public roadmap be updated?", a: "Weekly is a reasonable minimum. A roadmap that hasn't moved in months signals the team stopped shipping or stopped maintaining the page, both of which damage trust more than having no public roadmap at all." },
    ],
  },
  {
    slug: "feedback-triage-workflow",
    title: "Feedback triage: a workflow that scales",
    description:
      "A repeatable feedback triage process for turning a growing inbox of requests, bugs and comments into a prioritized, actioned backlog without a full-time triager.",
    date: "2026-07-27",
    keyword: "feedback triage process",
    category: "Academy",
    author: "Feedlark Team",
    authorBio: "The Feedlark team builds and maintains the feedback, roadmap and changelog platform referenced in this guide.",
    image: "https://images.unsplash.com/photo-1766066014237-00645c74e9c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Team member reviewing incoming feedback at a desk",
    readMins: 7,
    takeaways: [
      "Triage fails when it's treated as an occasional cleanup task instead of a scheduled, owned process with a fixed cadence.",
      "A good triage workflow has four steps: capture, dedupe, categorize, route, done consistently rather than exhaustively.",
      "Routing feedback to the right owner (support, PM, engineering) at triage time prevents items from sitting unaddressed in a general inbox.",
      "Triage should take 15-30 minutes on a healthy cadence. If it regularly takes longer, the intake volume or process needs fixing, not more triage time.",
    ],
    blocks: [
      { p: "Most product teams don't have a feedback problem, they have a triage problem. Requests, bug reports and comments come in fine; what breaks down is the step between 'received' and 'someone owns this and knows what to do with it.' A repeatable triage workflow is what closes that gap, and it doesn't require a dedicated headcount to run." },
      { h2: "The four-step triage loop", ul: [
        "Capture: pull new items from every intake channel (feedback board, support tickets, sales notes) into one queue. If an item only exists in a support agent's head, it doesn't count as captured.",
        "Dedupe: check new items against existing open requests before treating them as new. This is the step teams skip under time pressure, and it's the one that most damages prioritization accuracy over time.",
        "Categorize: tag by type (bug, feature request, question) and rough theme (billing, onboarding, a specific feature area) so patterns become visible across a quarter, not just a single sitting.",
        "Route: assign an owner. A bug goes to engineering triage, a feature request gets logged against a roadmap theme, a question gets handed to support. Nothing should leave triage without an owner.",
      ] },
      { table: { caption: "A weekly triage cadence for a small team", head: ["Day", "Task", "Time"], rows: [
        ["Monday", "Capture new items from the past week into one queue", "10 min"],
        ["Monday", "Dedupe against existing open requests", "10 min"],
        ["Monday", "Categorize and route each item to an owner", "10-15 min"],
        ["Ongoing", "Owners work items within their normal workflow", "N/A"],
      ] } },
      { h2: "Why routing at triage time matters more than routing later", p: "A feature request that sits in a general inbox for two weeks before anyone decides whose job it is to evaluate it has already lost momentum, and often the customer who filed it has stopped expecting a response. Assigning an owner at triage time, even if that owner's first action is just 'add to backlog for next planning', keeps items moving instead of stalling in an ownership gap." },
      { quote: { text: "The teams who triage well aren't doing anything exotic. They just do it on a fixed schedule instead of 'whenever things pile up', and they don't let an item leave the triage step without someone's name next to it.", cite: "Feedlark Team" } },
      { h2: "Signs your triage process needs fixing", ul: [
        "Triage regularly runs over 30 minutes: either intake volume has outgrown a single weekly pass, or dedup isn't catching enough duplicates to keep the queue manageable.",
        "The same theme keeps resurfacing as 'new': a sign categorization tags aren't being reused consistently, so patterns stay invisible.",
        "Items sit for weeks without an owner: routing is being skipped, usually because the process relies on someone remembering to do it rather than a fixed step.",
      ] },
      { h2: "Tooling that makes triage lighter, not heavier", p: "The workflow above works with a spreadsheet, but it works a lot faster when capture and dedupe happen in the same place customers submit feedback. A [feedback board](/blog/feedback-widget-for-website) with built-in duplicate detection and status tagging turns steps one and two into something closer to automatic, leaving the actual judgment calls, categorization and routing, as the only manual work each week." },
    ],
    faqs: [
      { q: "How often should feedback triage happen?", a: "Weekly works well for most small-to-mid-size teams. High-volume products may need it twice a week; low-volume products can stretch to biweekly, but longer than that lets items go stale and lose momentum." },
      { q: "What's the biggest mistake teams make in feedback triage?", a: "Skipping deduplication under time pressure. It feels like the step you can cut when busy, but skipping it is what causes real demand to look artificially low, since the same request stays split across multiple entries." },
      { q: "Does feedback triage need a dedicated person?", a: "No, not for most teams. A fixed 15-30 minute weekly slot owned by a PM or team lead is enough, as long as the four steps (capture, dedupe, categorize, route) actually happen each time rather than being skipped when busy." },
      { q: "What does 'routing' mean in a triage workflow?", a: "Assigning a clear owner to each item as it leaves triage, whether that's engineering for a bug, a PM for a feature request, or support for a question, so nothing sits unaddressed in a general inbox with no one responsible for the next step." },
    ],
  },
];
