import type { BlogPost } from "./blog-types";

export const BLOG_ROADMAP: BlogPost[] = [
  {
    slug: "product-roadmap-software-guide",
    title: "Product roadmap software: how to choose",
    description:
      "Product roadmap software helps teams plan, share and update what they're building. Here's how to find the right one, and avoid the traps of heavy PM tools.",
    date: "2026-06-25",
    keyword: "product roadmap software",
    category: "Academy",
    author: "Feedlark Team",
    readMins: 8,
    image: "https://images.unsplash.com/photo-1573166801077-d98391a43199?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Professional presenting a product roadmap on a whiteboard in a modern office setting",
    takeaways: [
      "Public roadmaps and internal roadmaps serve different audiences and need different levels of detail.",
      "Three simple statuses, Planned, In Progress and Shipped, are enough for almost any team.",
      "Match the tool to your team size; heavyweight PM platforms often cost more time than they save.",
      "Favour pricing based on admin seats, not viewers, so the roadmap can stay public and free to browse.",
    ],
    blocks: [
      { p: "Product roadmap software sits between your feedback board and your delivery tracker. It answers one question for anyone who asks it: what are you building and when? Get the answer right and you save your team dozens of meetings, reduce support requests and build real trust with users." },
      { h2: "Public roadmap vs internal roadmap", p: "An internal roadmap is for your team: granular, date specific, linked to sprints and engineering tickets. A public roadmap is for everyone else, customers, investors, partners and prospects. Public roadmaps are deliberately higher level, showing status (Planned, In Progress, Shipped) without committing to specific release dates. Most teams need both, but they serve completely different audiences. The internal version can reference ticket numbers and named engineers. The public version should read like plain English, written for someone who has never used your product before. Keeping the two separate, rather than trying to sanitise one document for both audiences, saves a surprising amount of editing time later. For ideas on formatting the public-facing version well, see our guide to building a [visual roadmap](/blog/visual-roadmap) that customers actually trust." },
      { h2: "How roadmap software differs from Jira or Linear", p: "Jira and Linear are delivery tools. They're optimised for engineering teams: tickets, sprints, acceptance criteria, velocity tracking. They're not designed for a customer to visit and understand what's coming next. A customer landing on a Jira board sees ticket numbers, story points and swimlanes that mean nothing to them, which is a clear sign the tool is being asked to do a job it wasn't built for. Product roadmap software is customer facing by default: clean, public, and requiring no account to view. Connecting your delivery tool to your public roadmap is a good idea; using your delivery tool as your public roadmap is not." },
      { h2: "The core features to look for", ul: [
        "Public-facing roadmap view that requires no login to access",
        "Simple statuses, Planned, In Progress and Shipped are usually enough",
        "Linked feedback board so votes inform what gets promoted to Planned",
        "Changelog integration so Shipped items automatically publish a release note",
        "Automatic voter notification when an item moves to Shipped",
        "Embeddable widget for in-app roadmap views",
      ] },
      { p: "None of this is exotic. It's the baseline a small team can set up in an afternoon rather than a quarter, which is exactly the point." },
      { h2: "The trap of heavyweight PM platforms", p: "Productboard, Aha! and similar enterprise PM platforms are comprehensive. They handle strategy alignment, OKRs, customer segment tagging and stakeholder reporting. For a team of two PMs, that's mostly overhead. The setup takes weeks, the learning curve is steep and the price reflects the feature depth. We've compared several lighter options in our [productboard alternatives](/blog/productboard-alternatives) roundup, most cost a fraction of the enterprise platforms and take an afternoon to configure rather than a quarter. If what you actually need is a public roadmap and a place for users to vote on features, you're paying for a plane when you need a bicycle." },
      { h2: "Timeline roadmaps vs status roadmaps", p: "Timeline roadmaps show items on a Gantt-style grid. They communicate sequence and rough timing but require constant maintenance as dates shift. Picture a roadmap that promises a feature 'by March'. If it slips to April, someone has to edit every reference to that promise: the shared deck, the sales one-pager, the customer email thread. Status roadmaps avoid this problem because they never promised March in the first place. They show items in swim lanes, Planned, In Progress, Shipped, with no dates attached. That label was true in February and it's still true in April. Status roadmaps are far easier to maintain, more honest about uncertainty, and more useful for users who just want to know what's coming rather than exactly when." },
      { h2: "How to connect feedback to your roadmap", p: "The most effective roadmaps start from feedback. You collect requests on a public board, let users vote, and promote the highest-signal items to Planned when the team decides to pick them up. In practice this might look like a request for dark mode collecting forty votes in a month, a volume that's hard to ignore, and moving it to Planned takes seconds once the data sits in one place rather than scattered across email and spreadsheets. That link from vote to roadmap item creates an auditable trail. Research from the [Nielsen Norman Group](https://www.nngroup.com/articles/discovery-study-guide/) on discovery methods backs this up: users trust a product more when they can see how their input shapes decisions. It also keeps the roadmap honest; you're building what users want most, not just what the last executive requested. If you need a refresher on gathering that input well in the first place, our guide on [how to collect customer feedback](/blog/how-to-collect-customer-feedback) covers the basics." },
      { h2: "A common evaluation mistake", p: "One founder we spoke with spent three weeks trialling three different enterprise roadmap platforms before realising her five-person team needed none of them. She had a spreadsheet of comparison criteria, two demo calls booked a week, and a growing sense that she was solving a problem she didn't actually have. Her team needed three status columns and a link she could drop into a support reply, nothing more. She picked the simplest tool on her shortlist, set it up in an afternoon, and never looked back. The lesson generalises well beyond her situation: match the tool to your team's size, not to the size of problem the sales page describes." },
      { h2: "Pricing to watch out for", p: "Some roadmap tools charge per editor, some per viewer, some per item. Viewer caps are the sneaky ones, they let you publish a public roadmap but charge once enough people view it. Check the pricing page carefully before committing; our breakdown of [Canny's pricing](/blog/canny-pricing-explained) is a good example of how these models play out once a roadmap gets popular. The most predictable model for a public roadmap is one that charges per admin, the people building and updating the roadmap, with unlimited free viewers." },
      { table: { caption: "Status label conventions used across public roadmaps", head: ["Stage", "Common label", "Alternative label", "What it means"], rows: [
        ["Not started", "Planned", "Under review", "Accepted but not yet in active development"],
        ["In development", "In Progress", "Building", "Actively being worked on by the team"],
        ["Released", "Shipped", "Live", "Available to all users now"],
        ["Rejected", "Not planned", "Closed", "Considered and declined, with a reason given"],
      ] } },
      { p: "Whichever labels you choose, keep them consistent everywhere: the roadmap, the changelog and any release emails. Consistency is what makes a status system easy to scan at a glance." },
      { h2: "Signs your current setup is holding you back", p: "Demand for transparency keeps rising. [Zendesk's CX Trends research](https://cxtrends.zendesk.com/) found that 63% of customers say the demand for transparency from companies has grown, and a stale internal roadmap can't meet that expectation on its own. Watch for these signs that your current setup is due an upgrade:", ul: [
        "Your roadmap lives in a slide deck that only gets updated before board meetings",
        "Support keeps answering the same 'is X coming?' question by email every week",
        "Nobody outside the product team has seen the roadmap in months",
        "Promoting a request to the roadmap means updating three separate documents",
        "You can't tell a user why a feature made it onto the roadmap",
      ] },
      { h2: "How to run a lightweight evaluation in a week", ul: [
        "Day 1 to 2: list your must-have features, keep the list to under ten items",
        "Day 3: sign up for two or three tools that match your team size, not your ambitions",
        "Day 4: import or recreate ten real feature requests to see how each tool actually feels",
        "Day 5: share a draft public roadmap link with a colleague outside the product team",
        "Day 6 to 7: pick the tool that took the least explaining and commit to it",
      ] },
      { h2: "Feedlark as roadmap software", p: "Feedlark's roadmap is built into the same platform as the feedback board and changelog. When you promote a request to In Progress, it appears on your public roadmap. When you ship it, a changelog entry is created and every voter is notified. The whole flow, collect, plan, ship, notify, works from one tool. [Bain's research, cited by Harvard Business Review](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers), found that a 5% improvement in customer retention can raise profits by 25 to 95%, and a public roadmap people trust is a small but real part of keeping that number healthy. The roadmap is free; the [Pro plan](/pricing) adds custom domain, private boards and white-label branding." },
    ],
    faqs: [
      { q: "Do I need separate roadmap software if I already use Jira or Linear?", a: "Usually yes. Jira and Linear are built for engineering delivery, not for customers to browse. A dedicated public roadmap presents the same information in a format non-technical users and prospects can understand without an account." },
      { q: "How many statuses should a public roadmap have?", a: "Three is usually enough: Planned, In Progress and Shipped. Extra statuses tend to confuse viewers rather than add useful information, and they make the roadmap harder to keep updated." },
      { q: "Is a public roadmap always the right choice?", a: "For most SaaS products, yes, since it reduces support questions and builds trust. Some teams keep certain strategic items internal and only publish the parts that are safe to share, which is fine as long as the public sections stay current." },
      { q: "What should I look for in roadmap software pricing?", a: "Favour tools that charge per admin seat rather than per viewer. Viewer-based pricing punishes you for having a popular, well-used roadmap, which defeats the purpose of publishing one at all." },
    ],
  },
  {
    slug: "why-product-roadmaps-fail",
    title: "Why product roadmaps fail (and how to fix yours)",
    description:
      "Most product roadmaps fail for the same reasons: no user input, no updates, no transparency. Here are six common pitfalls and how to build one that sticks.",
    date: "2026-06-25",
    keyword: "why product roadmaps fail",
    category: "Academy",
    author: "Tom Whitfield, Feedlark co-founder",
    authorBio: "Tom co-founded Feedlark and writes about product feedback, roadmaps and changelogs.",
    readMins: 8,
    image: "https://images.unsplash.com/photo-1529119368496-2dfda6ec2804?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Team strategy planning session with sticky notes on a wall board",
    takeaways: [
      "Roadmaps fail most often from silence: no customer input, no updates, and no word back to voters.",
      "Three status columns, Planned, In Progress and Shipped, are easier to maintain than dated timelines.",
      "A public roadmap is a trust-building asset, not just an internal planning document.",
      "Connecting the roadmap to your changelog and voter notifications turns feedback into a visible loop.",
    ],
    blocks: [
      { p: "The average product roadmap is a slide deck that's six months out of date and known only to the people who built it. That's not a roadmap, it's a wish list that nobody checks. Here's why most go wrong, and what the ones that work do differently." },
      { h2: "Reason 1: it's built without customer input", p: "A roadmap built purely from internal opinion reflects what the loudest voice in the room wants. That might be the CEO's pet feature or the feature the VP of Sales promised a prospect. Neither necessarily reflects what the majority of your users need. The fix requires discipline: start from votes. Run a public feedback board for a month before touching your roadmap. The data tells you what to prioritise; the roadmap records the decisions. Our guide to [customer feedback tools](/blog/customer-feedback-tools-guide) covers how to set one up without over-engineering it. It's worth saying plainly: internal opinion isn't worthless, it's just incomplete on its own. The healthiest roadmaps blend a small amount of strategic judgement with a much larger amount of voted, evidenced demand, rather than treating the two as opposites." },
      { h2: "Reason 2: it's too detailed to maintain", p: "Quarter-level roadmaps with specific release dates and feature descriptions look impressive in a board presentation. They're nightmares to maintain when priorities shift, which they always do. By month three, the roadmap is a lie. We've seen this play out with a ten-person team that published a roadmap promising six dated features for the quarter. Two shipped on time, one shipped a month late, and three were quietly dropped when a bigger client asked for something else. Customers noticed the gap between promise and reality long before anyone updated the document. Teams that keep their roadmaps useful keep them high level: three columns, Planned, In Progress, Shipped, no dates, reviewed monthly. Simple systems get maintained. Complex ones get abandoned." },
      { h2: "Reason 3: it's internal-only", p: "A roadmap that only your team can see can't build trust with users, reduce support volume, or align partners and investors. A public roadmap does all three. When a user can see that their feature request is In Progress, they stop emailing support. When a prospect sees a healthy stream of Shipped items, it signals momentum. This matters more than it used to. [Zendesk's CX Trends research](https://cxtrends.zendesk.com/) found that 63% of customers say the demand for transparency from companies has risen, and 85% of CX leaders say customers will drop a brand over unresolved issues. A [public roadmap](/blog/how-to-build-public-roadmap) is one of the simplest ways to show your working. Public roadmaps are a marketing asset, not just a planning tool." },
      { h2: "Reason 4: nothing ever moves to Shipped", p: "The most common reason users stop engaging with a feedback board or roadmap is that nothing appears to happen. Items stay in Planned for months. Shipped is empty. The roadmap starts to feel like theatre, a gesture toward transparency rather than actual accountability. Average subscription churn sits around 3.27% according to [Recurly's benchmark data](https://recurly.com/research/churn-rate-benchmarks/), and a roadmap that never ships anything visible is one of the quieter contributors to that number. The fix is to move things to Shipped consistently, even small things. A short changelog entry every two weeks is worth more than a big launch every quarter for maintaining trust. Our guide on [how to write a changelog](/blog/how-to-write-a-changelog) covers the format that takes the least effort to keep up." },
      { h2: "Reason 5: voters never hear back", p: "You asked users what they want. They told you. You built it. And then silence. The people who took the time to post and vote have no idea the thing they asked for is now live. They're still using workarounds or looking at competitors. Automatic voter notification, triggered when an item moves to Shipped, closes this gap. It costs nothing to set up and creates a genuine 'you asked, we delivered' moment that turns functional users into loyal ones. [HubSpot's service research](https://blog.hubspot.com/service/customer-service-stats) reflects the same pattern industry-wide: customers who feel heard are considerably more likely to stick around. This is really just the last step of a [product feedback loop](/blog/what-is-a-product-feedback-loop): collect, act, and tell people you acted." },
      { quote: { text: "We had a roadmap page for a year before anyone told us it existed. Once we started notifying voters when something shipped, replies started coming back within the hour.", cite: "Head of Product, workflow automation SaaS" } },
      { h2: "Reason 6: it's disconnected from the changelog", p: "Your roadmap shows what you're planning to build. Your changelog shows what you've already built. They should be the same list, with items moving from one to the other as you ship. When they're separate, one in Notion, one in a custom Webflow page, the overhead of keeping them in sync is what kills both. A [changelog tool](/blog/changelog-tool-guide) that's wired directly to the roadmap removes that friction entirely; one update produces both records. The roadmap decays because updating two places is too much friction. Teams often notice this failure only after the fact, when a customer asks about a feature that shipped months ago and nobody can explain why it was never announced." },
      { h2: "A quick diagnostic before you start fixing anything", ul: [
        "Can a new customer find your roadmap without asking support for a link?",
        "Has anything moved to Shipped in the last two weeks?",
        "Would a voter from six months ago recognise their request has been actioned?",
        "Does the roadmap match what your engineering team is actually building this week?",
        "Is there a single source of truth, or do the roadmap and changelog disagree?",
      ] },
      { h2: "What a working roadmap looks like", ul: [
        "It starts from voted feature requests, not internal opinion",
        "It uses three statuses: Planned, In Progress, Shipped",
        "It's publicly accessible without login",
        "It updates at least twice a month as items ship",
        "It automatically notifies voters when an item moves to Shipped",
        "It links directly to changelog entries for each shipped item",
      ] },
      { h2: "How to recover a roadmap that's already broken", p: "If your roadmap already fits several of the descriptions above, the fix isn't to start again from scratch. It's to prune hard and rebuild trust in small steps.", ul: [
        "Archive anything that's been sitting in Planned for more than two quarters without progress",
        "Post a short, honest update explaining what changed and why",
        "Move at least one small item to Shipped in the first week, even if it's minor",
        "Turn on notifications for anyone who's ever voted, starting today rather than retroactively",
        "Set a recurring calendar reminder to review the roadmap every two weeks",
      ] },
      { h2: "A quick before-and-after example", p: "A twelve-person SaaS team we spoke with had a roadmap with eighteen items, none of which had moved in four months. They cut the list to six realistic items, added a one-line explanation for each of the twelve they removed, and committed to shipping something small every fortnight. Within two months, support tickets asking 'what happened to X?' dropped noticeably, and several of the users who'd been quietest on the feedback board started voting again. Nothing about the underlying product changed in that window, only the visibility of what was already happening." },
      { h2: "Tools that make this easier", p: "The reason roadmaps fail isn't usually lack of intent, it's friction. When updating the roadmap is a manual, multi-step process across several tools, it doesn't get done consistently. Tools like Feedlark connect the feedback board, roadmap and changelog into one system. Promote a request and it hits the roadmap. Ship it, a changelog entry is created and voters are notified. One action, three outcomes. The roadmap and feedback board are free to use; the [Pro plan](/pricing) is only needed for a custom domain or private boards. That's the kind of system that actually gets maintained." },
    ],
    faqs: [
      { q: "How often should a product roadmap be updated?", a: "At least twice a month if you're shipping regularly. A roadmap that only changes before board meetings quickly falls out of step with what your team is actually building." },
      { q: "Should a roadmap include exact release dates?", a: "Generally no. Dates create expectations that are hard to keep once priorities shift. A status-based roadmap, using labels like Planned, In Progress and Shipped, is more honest and far easier to maintain." },
      { q: "What's the biggest reason customers stop trusting a roadmap?", a: "Silence. When an item sits in Planned for months with no explanation, or disappears without a word, customers assume feedback goes nowhere. Regular small updates matter more than occasional big ones." },
      { q: "Do voters need to be notified individually when a feature ships?", a: "Yes, ideally automatically. A short notification tied to the original request turns a passive vote into a completed loop, and it's one of the cheapest ways to build loyalty." },
    ],
  },
  {
    slug: "how-to-build-public-roadmap",
    title: "How to build a public product roadmap",
    description:
      "A practical guide to building a public product roadmap that builds trust: what to include, how to set statuses, and how to keep it updated automatically.",
    date: "2026-06-16",
    keyword: "public product roadmap",
    category: "Academy",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and has built roadmaps for teams of every size.",
    schemaType: "HowTo",
    readMins: 7,
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?fm=jpg&q=60&w=1080&auto=format&fit=crop&ixlib=rb-4.1.0",
    imageAlt: "Person working on a planning board with blue and white paper, building a public roadmap",
    takeaways: [
      "A public roadmap works best when it's built from votes, not internal guesswork.",
      "Three statuses, Planned, In Progress and Shipped, are enough; extra columns usually add confusion.",
      "Be selective about what goes on the roadmap so it stays credible over time.",
      "Closing the loop when you ship, with a changelog entry and voter notification, is what keeps people coming back.",
    ],
    blocks: [
      { p: "A public roadmap turns 'when are you building X?' into a link you can share. Done well, it builds trust, cuts support load and gives voters proof that their feedback led somewhere. Done badly, it's a slide deck nobody outside the product team has seen in months. Here's a step-by-step way to build one from a genuinely blank page." },
      { h2: "Step 1: start from real feedback, not internal opinion", p: "Don't invent a roadmap in a vacuum. Collect feature requests on a public board, let users vote, and promote the highest-signal items when the team decides to pick them up. Votes are your prioritisation data, not a suggestion box you glance at once a quarter. One team we spoke with started their first roadmap by exporting a year of scattered feedback from email threads and support tickets into a single board. Within a week, three items had more votes than anything on their existing internal wish list, and two of those hadn't been discussed by the product team at all. Research from the [Nielsen Norman Group](https://www.nngroup.com/articles/discovery-study-guide/) on discovery methods makes the same point: structured, ongoing feedback collection surfaces things ad hoc conversations miss. If you haven't set up a collection process yet, our guide on [how to collect customer feedback](/blog/how-to-collect-customer-feedback) is a good place to start. Give the board at least a few weeks of quiet running before you build the roadmap from it, otherwise you're prioritising off a handful of early, possibly unrepresentative, votes." },
      { h2: "How to phrase roadmap items so nobody misreads them", p: "The wording of a roadmap item matters as much as its status. Vague titles create vague expectations, and specific titles create trust because they're easy to check against reality once the item ships.", ul: [
        "Write the outcome, not the mechanism: 'Export data to CSV' rather than 'Rebuild the export service'",
        "Keep each title to one line; move any extra detail to a linked feedback thread",
        "Avoid words like 'soon' or 'improved' that don't mean anything specific",
        "Use the same terminology your customers use in their own feedback, not your internal name for the feature",
      ] },
      { h2: "Step 2: decide what goes on the roadmap and what doesn't", p: "Not every request belongs on a public roadmap. Being selective is what keeps it credible.", ul: [
        "Include: features with real demand, shown by votes or repeated requests",
        "Include: work that's genuinely been accepted, not just discussed once in a meeting",
        "Include: a short, plain-language description anyone can understand without context",
        "Leave off: speculative ideas nobody has committed to building",
        "Leave off: internal technical work like refactors or infrastructure migrations",
        "Leave off: anything you're not confident enough in to be asked about in three months",
      ] },
      { h2: "Step 3: use simple, honest statuses", p: "Three columns are enough for most teams: Planned, In Progress and Shipped. Map each request to a status and your roadmap builds itself, rather than needing a separate document written from scratch.", table: { caption: "What belongs in each roadmap status", head: ["Status", "Entry criteria", "Example"], rows: [
        ["Planned", "Accepted by the team, not yet started", "Dark mode, accepted after 40 votes"],
        ["In Progress", "Someone is actively building it", "Bulk export, in development this sprint"],
        ["Shipped", "Live for all users, changelog entry published", "CSV import, released last Tuesday"],
      ] } },
      { h2: "Step 4: choose where to host it", p: "A public roadmap needs a URL you're happy to share anywhere: in your app, in support replies, in your welcome email. Some teams embed it directly on their marketing site; others link out to a hosted page. Either works, as long as it needs no login and loads fast. If you're weighing up a full feedback and roadmap system against a simple embedded widget, our comparison of [feedback widgets for websites](/blog/feedback-widget-for-website) covers the trade-offs. Feedlark hosts the roadmap on its own public page by default, with an embeddable widget available for teams that want it inside their product; the [Pro plan](/pricing) adds a custom domain for either option." },
      { h2: "Step 5: close the loop when you ship", p: "When something ships, move it to Shipped and tell the people who asked. Tools like Feedlark do this automatically: a changelog entry goes out and every voter gets notified. That last step matters more than it seems. [Zendesk's CX Trends research](https://cxtrends.zendesk.com/) found that 85% of CX leaders say customers will drop a brand over unresolved issues, and silence after a request is a quieter version of the same problem. A short note beats a long wait every time. Picture the difference between a voter discovering a feature by accident three months after launch, and the same voter getting a two-line email the day it ships. The feature is identical either way; only the relationship changes." },
      { h2: "When to retire an item quietly and when to explain it publicly", p: "Not every roadmap item survives. Priorities change, and some requests turn out to be smaller in demand than they first appeared. Removing a low-vote item that never had much support rarely needs a public explanation. But an item that's been visible on the roadmap for months, with real votes attached, deserves a short note when it's dropped or deprioritised. A single sentence, explaining what changed and why, costs little and prevents the item from looking like it vanished for no reason. Silence is what actually damages trust here, not the decision itself. Most voters accept a clear 'not right now, and here's why' far more easily than they accept an item quietly disappearing with no comment at all." },
      { h2: "Step 6: write it in plain, accessible language", p: "Roadmap items get read by people who've never used your product and by people who use it every day. Write for the first group. Avoid jargon, ticket codes and internal shorthand. The [W3C's guidance on accessible writing](https://www.w3.org/WAI/tips/writing/) is aimed at web content generally, but the advice, short sentences, plain words, clear structure, applies just as well to a roadmap item as to any other page on your site." },
      { h2: "Step 7: set a review cadence and keep it public", p: "Host the roadmap on a public, server-rendered page so search engines and AI assistants can surface what you're building when people ask. Then put a review on the calendar, weekly for a fast-moving team, fortnightly otherwise, so items keep moving rather than sitting still. A roadmap that hasn't changed in two months reads as abandoned even if the team behind it is busier than ever. Attach the review to a meeting that already exists, such as sprint planning, rather than inventing a new one that's easy to skip once the week gets busy." },
      { h2: "How much detail is too much detail", p: "A common early mistake is trying to make the public roadmap comprehensive. Every field you add, owners, dependencies, technical notes, is a field you have to keep accurate forever. Ask what a customer actually needs to know: what it is, roughly when it might land, and whether their vote helped move it forward. Everything else belongs in the internal version, where the audience already has the context to interpret it correctly." },
      { h2: "Common mistakes when building your first roadmap", ul: [
        "Publishing every idea the team has ever discussed, rather than only accepted work",
        "Promising exact dates before the team has actually scoped the work",
        "Forgetting to link items back to the [feature requests](/blog/how-to-track-feature-requests) that inspired them",
        "Letting the roadmap and the changelog drift out of sync with each other",
        "Treating launch day as the finish line instead of the start of a review habit",
      ] },
      { quote: { text: "The first version of our roadmap took less than an afternoon. What took longer was trusting that three columns really were enough.", cite: "Founder, ten-person SaaS team" } },
    ],
    faqs: [
      { q: "How long does it take to launch a first public roadmap?", a: "Most teams can set up a basic three-column roadmap in an afternoon once they have a handful of real feature requests to populate it with. The ongoing work is the review cadence, not the initial build." },
      { q: "Should every feature request appear on the roadmap?", a: "No. Only requests the team has genuinely accepted belong there. Publishing every idea that's ever been discussed makes the roadmap harder to trust, since users can't tell which items are real commitments." },
      { q: "Do I need exact dates on a public roadmap?", a: "Generally no. A rough time horizon, like 'this quarter', is usually enough, and it avoids the awkward job of explaining a missed date later. Status labels do most of the communicating for you." },
      { q: "How do I keep a roadmap from going stale after launch?", a: "Set a fixed review slot, weekly or fortnightly, and treat moving at least one item forward as non-negotiable. Connecting the roadmap to your changelog so shipped items update automatically removes most of the manual effort." },
    ],
  },
  {
    slug: "visual-roadmap",
    title: "How to build a visual roadmap your team trusts",
    description:
      "A visual roadmap communicates where the product is going without a wall of text. Here's how to build one that works for customers and stakeholders.",
    date: "2026-06-26",
    keyword: "visual roadmap",
    category: "Academy",
    author: "Feedlark Team",
    readMins: 8,
    image: "https://images.unsplash.com/photo-1598520106830-8c45c2035460?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Person writing diagrams on a glass whiteboard during a planning session",
    takeaways: [
      "A visual roadmap communicates direction at a glance, but only if it stays current.",
      "Three status columns and one colour per status are easier to scan than an elaborate colour or icon system.",
      "Connecting the roadmap to your feedback board shows customers their votes had an effect.",
      "Explain changes to the roadmap proactively; silence is what breaks customer trust, not the change itself.",
    ],
    blocks: [
      { p: "A visual roadmap does something a spreadsheet or a list can't: it communicates direction at a glance. Customers, stakeholders and team members can look at it and immediately understand what's being worked on, what's coming next and what's already done. The challenge is keeping it honest." },
      { h2: "Why visual roadmaps fail", p: "Most visual roadmap failures share one cause: the roadmap stops being updated. It's created with care, shared with customers, and then reality changes. Features slip. Priorities shift. The roadmap stays where it is, increasingly disconnected from what's actually happening. Customers who check back see a plan that doesn't match their experience. Trust erodes quickly once that happens. The erosion isn't dramatic, it's death by a thousand small disappointments, each one a customer quietly deciding the roadmap isn't worth checking again. A roadmap built as a one-off design project, a nice image exported from a design tool and pasted into a help centre article, is especially prone to this. It looks finished, so nobody treats it as something that needs ongoing maintenance." },
      { h2: "The three-column format that actually works", p: "The most durable visual roadmap format is the simplest: three columns labelled Planned, In Progress and Shipped. Items move left to right as they progress. Customers can see exactly where their requested feature is. The team has a shared view of what's in flight. There's no ambiguity about what 'coming soon' means because everything has a clear status label. Teams that add a fourth or fifth column, like 'Under review' or 'On hold', usually find it adds confusion rather than clarity; three is a genuine sweet spot, not just a simplification for its own sake." },
      { h2: "What to put on a visual roadmap", ul: [
        "Feature names and brief descriptions in plain English, not internal ticket codes",
        "Status: Planned, In Progress or Shipped",
        "Vote counts from the feedback board if you have them",
        "A rough time horizon such as 'This quarter' rather than exact dates",
        "A link from each item back to the original feedback request where relevant",
      ] },
      { p: "Keep descriptions to a single sentence wherever possible. If an item needs a paragraph to explain, it probably needs a supporting page linked from the roadmap rather than a longer roadmap entry." },
      { h2: "What to leave off", ul: [
        "Exact delivery dates unless you're very confident in them",
        "Internal technical details that don't mean anything to customers",
        "Items that are speculative or not yet committed",
        "Anything that's been on the roadmap for more than two quarters without moving",
      ] },
      { h2: "How stakeholders read a visual roadmap differently to customers", p: "Customers scan a visual roadmap looking for one thing: their request. Investors and internal stakeholders read it looking for a different thing: momentum, and whether the team is delivering at a steady pace. Both audiences are served by the same three-column format, which is one reason it's worth resisting the urge to build a separate, more detailed version for leadership. A shared format, viewed by different people for different reasons, is easier to keep honest than two roadmaps maintained in parallel." },
      { h2: "Choosing colours and icons without adding noise", p: "Colour and iconography can make a visual roadmap easier to scan, but only if they're used sparingly. A roadmap with five colours, three icon sets and a legend is harder to read than one using plain text labels. Stick to one colour per status and resist the urge to add more.", table: { caption: "Simple status colour conventions for a visual roadmap", head: ["Status", "Typical colour", "Common icon", "Meaning at a glance"], rows: [
        ["Planned", "Grey or blue", "Clock or list", "Accepted, not yet started"],
        ["In Progress", "Amber or orange", "Gear or hammer", "Actively being built"],
        ["Shipped", "Green", "Tick or check", "Live for all users"],
      ] } },
      { h2: "A quick example: two versions of the same roadmap", p: "A twenty-person SaaS team once ran two versions of the same roadmap for a month as a test. The first used six statuses, four colours and dated milestones. The second used three statuses, one colour per status and no dates at all. New users who saw the second version for the first time could explain what it showed within seconds. Users shown the first version needed a short explanation from a teammate before they understood which column meant what. The team switched to the simpler version permanently and reported fewer 'what does this mean?' questions from new customers within the first week." },
      { h2: "Connecting the visual roadmap to your feedback board", p: "The most powerful version of a visual roadmap is one that's connected to a feedback board. When customers vote for a feature and then see it appear on the roadmap, they understand their input had an effect. When it moves to Shipped and they get a notification, that connection is complete. This is what separates a decorative roadmap from a functional one. It also pays off in a way that's easy to underestimate. [Bain's research for Harvard Business Review](https://hbr.org/2014/10/the-value-of-keeping-the-right-customers) found that a 5% improvement in customer retention can lift profits by 25 to 95%, and a visible link between votes and outcomes is a cheap way to keep customers around long enough to feel that effect. For the mechanics of running the board itself, see our guide to a [feature request board](/blog/feature-request-board-guide)." },
      { h2: "Public vs internal visual roadmaps", p: "A public visual roadmap is visible to customers. An internal one is visible only to the team. The level of detail should differ. Public roadmaps should be clear about direction without committing to exact timelines. Internal roadmaps can include more detail: dependencies, assignees and release targets. Some teams maintain both, with the public version generated automatically from the internal one. If you haven't set up the public-facing version yet, our step-by-step guide to [building a public roadmap](/blog/how-to-build-public-roadmap) covers the setup in more detail." },
      { h2: "Keeping the roadmap current without it becoming a burden", p: "The main reason roadmaps go stale is that updating them requires too much manual effort. Choose a tool that makes status changes automatic: when an item moves to Shipped in your process, it should move to Shipped on the roadmap without a separate update. This matters for reasons beyond tidiness. Average subscription churn sits around 3.27% according to [Recurly's benchmark data](https://recurly.com/research/churn-rate-benchmarks/), and a visibly stale roadmap is one of the smaller, harder-to-trace contributors to that figure. Pairing the roadmap with a proper [changelog tool](/blog/changelog-tool-guide) removes most of the manual effort." },
      { h2: "Communicating changes to the roadmap", p: "Roadmaps change. That's normal. What matters is how changes are communicated. When a feature moves from Planned to deprioritised, it's better to tell customers proactively than to let them notice the item disappearing. [Zendesk's CX Trends research](https://cxtrends.zendesk.com/) found that 85% of CX leaders say customers will drop a brand entirely over unresolved issues, and a roadmap item that vanishes without a word reads as exactly that kind of unresolved issue. [Closing the feedback loop](/blog/close-the-feedback-loop) properly means explaining changes, not just making them. Silence, or a feature disappearing without explanation, breaks trust fast." },
      { h2: "How to launch a visual roadmap", ul: [
        "Start with a realistic set of items, not everything you've ever considered",
        "Use three status columns: Planned, In Progress, Shipped",
        "Set expectations clearly: the roadmap shows direction, not guarantees",
        "Share the link in your app, your changelog and your welcome email",
        "Review and update the roadmap at least once per sprint",
        "Notify customers when their specific requests move forward",
      ] },
      { p: "A visual roadmap is most valuable as a communication tool. Built and maintained well, it reduces the 'when is feature X coming?' questions, gives customers confidence that their feedback is being acted on and keeps stakeholders aligned without a monthly briefing. Feedlark's roadmap ships with this format built in, free to publish, with the [Pro plan](/pricing) adding a custom domain and private boards for teams that need them." },
    ],
    faqs: [
      { q: "How many colours should a visual roadmap use?", a: "One per status is plenty, usually three in total for Planned, In Progress and Shipped. Extra colours or icon sets tend to slow readers down rather than help them, which defeats the purpose of a visual format." },
      { q: "Should a visual roadmap show internal details like assignees?", a: "No, keep those for the internal version. A public visual roadmap should show what's happening in plain language, not who's working on it or which sprint it's assigned to." },
      { q: "What's the biggest visual roadmap mistake teams make?", a: "Adding too many statuses or too much detail per item. A roadmap that needs a legend and a paragraph of explanation per card has stopped being visual and become a document again." },
      { q: "How often should a visual roadmap be reviewed?", a: "At least once per sprint or every two weeks, whichever is more frequent for your team. Items that sit still for two quarters without moving should be reconsidered or explained, not left quietly in place." },
    ],
  },
  {
    slug: "how-to-create-a-product-roadmap",
    title: "How to create a product roadmap from scratch",
    description:
      "Starting a product roadmap from a blank page? This step-by-step guide covers structure, statuses, what to include, and keeping it fed by real feedback.",
    date: "2026-07-03",
    keyword: "create product roadmap",
    category: "Academy",
    author: "Priya Shah, Head of Product at Feedlark",
    authorBio: "Priya leads product at Feedlark and has built roadmaps for teams of every size.",
    schemaType: "HowTo",
    readMins: 8,
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=1080",
    imageAlt: "Team sketching out how to create a product roadmap on a whiteboard from scratch",
    takeaways: [
      "Start a roadmap from real votes and requests, not a blank whiteboard session.",
      "Three statuses, Planned, In Progress and Shipped, with clear entry criteria for each, keep it honest.",
      "Decide what to exclude as carefully as what to include; a selective roadmap stays credible.",
      "Publish it somewhere public and close the loop with a changelog entry every time you ship.",
    ],
    blocks: [
      { p: "A blank roadmap is one of the more intimidating documents in product management. There's no data on the page yet, no obvious starting point, and a nagging sense that whatever you build first will set the template for everything after it. It doesn't need to be complicated. Here's a practical, step-by-step way to create a product roadmap from nothing, covering structure, statuses, what belongs on it and how to keep it fed once it's live." },
      { h2: "Step 1: pick your format before you pick your tool", p: "Before opening any software, decide on the shape of the thing. Most working roadmaps use one of two formats: a timeline with dates, or a status board with columns like Planned, In Progress and Shipped. Timelines look precise but need constant rework as dates shift. Status boards are less precise but far easier to keep accurate, since a label like 'In Progress' stays true whether the work takes two weeks or two months. For a first roadmap, especially a public one, a status board is almost always the better starting point. You can always add a rough time horizon later once you've proven you can keep the board itself updated. Deciding this early saves a lot of back and forth, because the format you choose shapes almost every decision that follows, from what software you need to how you word each item." },
      { h2: "How to handle competing priorities early on", p: "Even a brand new roadmap has to deal with competing demands. Sales wants a feature that helps close one big deal. Support wants a fix for the issue generating the most tickets. Engineering wants time to pay down technical debt that slows everything else down. There's no formula that resolves this cleanly, but a public vote count gives you a shared, visible reference point everyone can argue from, rather than each team quietly assuming their priority is the obvious one. It won't remove the disagreement entirely, but it moves the conversation from opinion to evidence, which tends to be a shorter conversation." },
      { h2: "Step 2: choose three statuses and stick to them", p: "Resist the urge to add more than three statuses. Planned, In Progress and Shipped cover almost every situation a product team faces, and each one has a clear, testable definition for whether an item belongs there.", table: { caption: "Entry criteria for each roadmap status", head: ["Status", "Criteria to enter", "Example"], rows: [
        ["Planned", "The team has accepted it and expects to start within a few months", "Bulk export, accepted after repeated requests"],
        ["In Progress", "Someone is actively writing code or designing it right now", "Team calendars, in active development"],
        ["Shipped", "It's live for every user and has a changelog entry", "Dark mode, released and announced last week"],
      ] } },
      { h2: "Step 3: decide what goes on the roadmap and what doesn't", p: "A roadmap that lists everything the team has ever discussed stops being useful. Being deliberate about scope is what keeps it trustworthy.", ul: [
        "Include features and improvements with real, demonstrated demand",
        "Include work the team has actually accepted, not just floated in a meeting",
        "Include a short, plain-language description for each item",
        "Exclude speculative ideas that haven't been through any kind of review",
        "Exclude internal engineering work like migrations or refactors, unless it visibly affects customers",
        "Exclude anything you wouldn't be comfortable being asked about again in three months",
      ] },
      { h2: "Step 4: feed it from real votes, not guesses", p: "The single biggest difference between a roadmap that stays useful and one that quietly dies is where its items come from. Roadmaps built from internal opinion drift toward whoever argues loudest in planning meetings. Roadmaps built from a public feedback board reflect what users actually ask for, repeatedly, in their own words. Research from the [Nielsen Norman Group](https://www.nngroup.com/articles/discovery-study-guide/) on discovery methods makes a similar point about product decisions generally: structured, ongoing input beats occasional, informal conversations. If you don't already have a way to collect that input, start with our guide on [how to collect customer feedback](/blog/how-to-collect-customer-feedback) before you write a single roadmap item." },
      { h2: "Step 5: write each item in plain language", p: "Every item on the roadmap should be readable by someone who has never used your product. Avoid ticket numbers, internal codenames and engineering jargon. 'Add CSV export for reports' is a roadmap item. 'REPORT-482: async export pipeline' is not. This isn't just good manners, it's practical: a roadmap item that needs translating loses most of its value as a communication tool. The same plain-language instinct sits behind the [W3C's guidance on accessible writing](https://www.w3.org/WAI/tips/writing/), which recommends short sentences and familiar words for exactly this reason, so that the widest possible audience can follow along without extra effort." },
      { h2: "Step 6: set a review cadence", p: "A roadmap without a review schedule decays the same way a garden does without watering, slowly, and then all at once. Put a recurring slot on the calendar, weekly for a fast-moving team, fortnightly for a smaller one, and use it to move at least one item forward. This doesn't need to be a long meeting. Fifteen minutes checking which items should change status is usually enough. The habit matters more than the length. Attach the review to something that already happens, like the end of a sprint planning session, rather than creating a brand new meeting that's the first thing to get skipped when the week gets busy." },
      { h2: "Step 7: publish it somewhere public", p: "A roadmap that only the product team can see can't build trust with customers or reduce support questions. Host it on a page that needs no login, loads quickly, and can be shared in a support reply or a welcome email. Our guide on [building a public roadmap](/blog/how-to-build-public-roadmap) covers the setup in detail, including where to draw the line between what's public and what stays internal. Feedlark's roadmap is free to publish; the [Pro plan](/pricing) is only needed if you want a custom domain or private boards." },
      { h2: "Step 8: close the loop every time you ship", p: "The step teams most often skip is the simplest one: telling people when something they asked for is done. Move the item to Shipped, publish a short changelog entry, and notify everyone who voted for it. [HubSpot's service research](https://blog.hubspot.com/service/customer-service-stats) reflects a pattern that shows up across industries: customers who feel their feedback led somewhere are far more likely to stay engaged. Our guide on [how to write a changelog](/blog/how-to-write-a-changelog) covers a format that takes minutes, not hours, to keep current." },
      { h2: "A short anecdote: building one in an afternoon", p: "A five-person team we spoke with put off building a roadmap for over a year, worried it would turn into a big project. When they finally sat down to do it, the whole first version took under three hours. They exported forty support tickets and feature requests into a spreadsheet, grouped the repeats, sorted them into Planned, In Progress and Shipped, and published the result on a single page linked from their help centre. The hardest part, by their own account, wasn't the roadmap itself. It was trusting that three plain columns really were enough, after a year of assuming they'd need something far more elaborate." },
      { h2: "Common mistakes when building your first roadmap", ul: [
        "Trying to plan a full year in detail before publishing anything at all",
        "Adding a status for every possible edge case instead of sticking to three",
        "Copying internal ticket titles straight onto the public roadmap",
        "Forgetting to link roadmap items back to the [feature requests](/blog/how-to-track-feature-requests) that inspired them",
        "Treating the launch as finished, rather than as the start of a review habit",
      ] },
      { quote: { text: "We spent longer debating the name of the third column than we did building the actual roadmap. In hindsight, any of the options would have worked fine.", cite: "Founder, six-person productivity app" } },
    ],
    faqs: [
      { q: "What's the first step in creating a product roadmap?", a: "Start by collecting real feedback rather than opinions in a meeting room. A public feedback board with votes gives you actual demand data to build the first version from, rather than guesswork." },
      { q: "How many items should a first roadmap include?", a: "Keep it short, ideally under ten items split across three statuses. A long list of speculative ideas is harder to trust than a short list of things the team has genuinely accepted." },
      { q: "Do I need special software to create a product roadmap?", a: "Not strictly, a spreadsheet can work for a very small team. But dedicated roadmap software saves time once you need a public link, automatic voter notifications and a connected changelog, which most growing teams end up wanting." },
      { q: "How do I keep a new roadmap from stalling after launch?", a: "Set a recurring review, weekly or fortnightly, and commit to moving at least one item forward each time. Linking the roadmap to your feedback board and changelog removes most of the manual admin that causes roadmaps to stall." },
    ],
  },
];
